// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: mail_runtime.proto

package mailproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MailConsumerDesiredState int32

const (
	MailConsumerDesiredState_MAIL_CONSUMER_DESIRED_STATE_UNSPECIFIED MailConsumerDesiredState = 0
	MailConsumerDesiredState_MAIL_CONSUMER_DESIRED_STATE_PAUSED      MailConsumerDesiredState = 1
	MailConsumerDesiredState_MAIL_CONSUMER_DESIRED_STATE_ENABLED     MailConsumerDesiredState = 2
)

// Enum value maps for MailConsumerDesiredState.
var (
	MailConsumerDesiredState_name = map[int32]string{
		0: "MAIL_CONSUMER_DESIRED_STATE_UNSPECIFIED",
		1: "MAIL_CONSUMER_DESIRED_STATE_PAUSED",
		2: "MAIL_CONSUMER_DESIRED_STATE_ENABLED",
	}
	MailConsumerDesiredState_value = map[string]int32{
		"MAIL_CONSUMER_DESIRED_STATE_UNSPECIFIED": 0,
		"MAIL_CONSUMER_DESIRED_STATE_PAUSED":      1,
		"MAIL_CONSUMER_DESIRED_STATE_ENABLED":     2,
	}
)

func (x MailConsumerDesiredState) Enum() *MailConsumerDesiredState {
	p := new(MailConsumerDesiredState)
	*p = x
	return p
}

func (x MailConsumerDesiredState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MailConsumerDesiredState) Descriptor() protoreflect.EnumDescriptor {
	return file_mail_runtime_proto_enumTypes[0].Descriptor()
}

func (MailConsumerDesiredState) Type() protoreflect.EnumType {
	return &file_mail_runtime_proto_enumTypes[0]
}

func (x MailConsumerDesiredState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MailConsumerDesiredState.Descriptor instead.
func (MailConsumerDesiredState) EnumDescriptor() ([]byte, []int) {
	return file_mail_runtime_proto_rawDescGZIP(), []int{0}
}

type MailConsumerRuntimeState int32

const (
	MailConsumerRuntimeState_MAIL_CONSUMER_RUNTIME_STATE_UNSPECIFIED MailConsumerRuntimeState = 0
	MailConsumerRuntimeState_MAIL_CONSUMER_RUNTIME_STATE_STOPPED     MailConsumerRuntimeState = 1
	MailConsumerRuntimeState_MAIL_CONSUMER_RUNTIME_STATE_STARTING    MailConsumerRuntimeState = 2
	MailConsumerRuntimeState_MAIL_CONSUMER_RUNTIME_STATE_RUNNING     MailConsumerRuntimeState = 3
	MailConsumerRuntimeState_MAIL_CONSUMER_RUNTIME_STATE_PAUSED      MailConsumerRuntimeState = 4
	MailConsumerRuntimeState_MAIL_CONSUMER_RUNTIME_STATE_DRAINING    MailConsumerRuntimeState = 5
	MailConsumerRuntimeState_MAIL_CONSUMER_RUNTIME_STATE_ERROR       MailConsumerRuntimeState = 6
	MailConsumerRuntimeState_MAIL_CONSUMER_RUNTIME_STATE_DEGRADED    MailConsumerRuntimeState = 7
)

// Enum value maps for MailConsumerRuntimeState.
var (
	MailConsumerRuntimeState_name = map[int32]string{
		0: "MAIL_CONSUMER_RUNTIME_STATE_UNSPECIFIED",
		1: "MAIL_CONSUMER_RUNTIME_STATE_STOPPED",
		2: "MAIL_CONSUMER_RUNTIME_STATE_STARTING",
		3: "MAIL_CONSUMER_RUNTIME_STATE_RUNNING",
		4: "MAIL_CONSUMER_RUNTIME_STATE_PAUSED",
		5: "MAIL_CONSUMER_RUNTIME_STATE_DRAINING",
		6: "MAIL_CONSUMER_RUNTIME_STATE_ERROR",
		7: "MAIL_CONSUMER_RUNTIME_STATE_DEGRADED",
	}
	MailConsumerRuntimeState_value = map[string]int32{
		"MAIL_CONSUMER_RUNTIME_STATE_UNSPECIFIED": 0,
		"MAIL_CONSUMER_RUNTIME_STATE_STOPPED":     1,
		"MAIL_CONSUMER_RUNTIME_STATE_STARTING":    2,
		"MAIL_CONSUMER_RUNTIME_STATE_RUNNING":     3,
		"MAIL_CONSUMER_RUNTIME_STATE_PAUSED":      4,
		"MAIL_CONSUMER_RUNTIME_STATE_DRAINING":    5,
		"MAIL_CONSUMER_RUNTIME_STATE_ERROR":       6,
		"MAIL_CONSUMER_RUNTIME_STATE_DEGRADED":    7,
	}
)

func (x MailConsumerRuntimeState) Enum() *MailConsumerRuntimeState {
	p := new(MailConsumerRuntimeState)
	*p = x
	return p
}

func (x MailConsumerRuntimeState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MailConsumerRuntimeState) Descriptor() protoreflect.EnumDescriptor {
	return file_mail_runtime_proto_enumTypes[1].Descriptor()
}

func (MailConsumerRuntimeState) Type() protoreflect.EnumType {
	return &file_mail_runtime_proto_enumTypes[1]
}

func (x MailConsumerRuntimeState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MailConsumerRuntimeState.Descriptor instead.
func (MailConsumerRuntimeState) EnumDescriptor() ([]byte, []int) {
	return file_mail_runtime_proto_rawDescGZIP(), []int{1}
}

type MailExecutionStatus int32

const (
	MailExecutionStatus_MAIL_EXECUTION_STATUS_UNSPECIFIED     MailExecutionStatus = 0
	MailExecutionStatus_MAIL_EXECUTION_STATUS_CONSUMED        MailExecutionStatus = 1
	MailExecutionStatus_MAIL_EXECUTION_STATUS_RENDERED        MailExecutionStatus = 2
	MailExecutionStatus_MAIL_EXECUTION_STATUS_SUBMITTING      MailExecutionStatus = 3
	MailExecutionStatus_MAIL_EXECUTION_STATUS_RETRY_SCHEDULED MailExecutionStatus = 4
	MailExecutionStatus_MAIL_EXECUTION_STATUS_SUBMITTED       MailExecutionStatus = 5
	MailExecutionStatus_MAIL_EXECUTION_STATUS_REJECTED        MailExecutionStatus = 6
	MailExecutionStatus_MAIL_EXECUTION_STATUS_FAILED          MailExecutionStatus = 7
	MailExecutionStatus_MAIL_EXECUTION_STATUS_AMBIGUOUS       MailExecutionStatus = 8
)

// Enum value maps for MailExecutionStatus.
var (
	MailExecutionStatus_name = map[int32]string{
		0: "MAIL_EXECUTION_STATUS_UNSPECIFIED",
		1: "MAIL_EXECUTION_STATUS_CONSUMED",
		2: "MAIL_EXECUTION_STATUS_RENDERED",
		3: "MAIL_EXECUTION_STATUS_SUBMITTING",
		4: "MAIL_EXECUTION_STATUS_RETRY_SCHEDULED",
		5: "MAIL_EXECUTION_STATUS_SUBMITTED",
		6: "MAIL_EXECUTION_STATUS_REJECTED",
		7: "MAIL_EXECUTION_STATUS_FAILED",
		8: "MAIL_EXECUTION_STATUS_AMBIGUOUS",
	}
	MailExecutionStatus_value = map[string]int32{
		"MAIL_EXECUTION_STATUS_UNSPECIFIED":     0,
		"MAIL_EXECUTION_STATUS_CONSUMED":        1,
		"MAIL_EXECUTION_STATUS_RENDERED":        2,
		"MAIL_EXECUTION_STATUS_SUBMITTING":      3,
		"MAIL_EXECUTION_STATUS_RETRY_SCHEDULED": 4,
		"MAIL_EXECUTION_STATUS_SUBMITTED":       5,
		"MAIL_EXECUTION_STATUS_REJECTED":        6,
		"MAIL_EXECUTION_STATUS_FAILED":          7,
		"MAIL_EXECUTION_STATUS_AMBIGUOUS":       8,
	}
)

func (x MailExecutionStatus) Enum() *MailExecutionStatus {
	p := new(MailExecutionStatus)
	*p = x
	return p
}

func (x MailExecutionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MailExecutionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_mail_runtime_proto_enumTypes[2].Descriptor()
}

func (MailExecutionStatus) Type() protoreflect.EnumType {
	return &file_mail_runtime_proto_enumTypes[2]
}

func (x MailExecutionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MailExecutionStatus.Descriptor instead.
func (MailExecutionStatus) EnumDescriptor() ([]byte, []int) {
	return file_mail_runtime_proto_rawDescGZIP(), []int{2}
}

type MailEventMetadataV1 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// [COMMENT]: UUIDv5 16-byte id, deterministic từ aggregate id + version + event type.
	EventId []byte `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// [COMMENT]: Bằng 1 cho toàn bộ message V1 trong file này.
	SchemaVersion uint32 `protobuf:"varint,2,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	// [COMMENT]: Unix epoch milliseconds UTC do producer tạo event ghi nhận.
	OccurredAtUnixMs int64 `protobuf:"varint,3,opt,name=occurred_at_unix_ms,json=occurredAtUnixMs,proto3" json:"occurred_at_unix_ms,omitempty"`
	// [COMMENT]: W3C traceparent; không chứa baggage của khách hàng.
	Traceparent string `protobuf:"bytes,4,opt,name=traceparent,proto3" json:"traceparent,omitempty"`
	// [COMMENT]: Tên workload nội bộ tạo event, phục vụ audit chứ không dùng authorization.
	Producer      string `protobuf:"bytes,5,opt,name=producer,proto3" json:"producer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailEventMetadataV1) Reset() {
	*x = MailEventMetadataV1{}
	mi := &file_mail_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailEventMetadataV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailEventMetadataV1) ProtoMessage() {}

func (x *MailEventMetadataV1) ProtoReflect() protoreflect.Message {
	mi := &file_mail_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailEventMetadataV1.ProtoReflect.Descriptor instead.
func (*MailEventMetadataV1) Descriptor() ([]byte, []int) {
	return file_mail_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *MailEventMetadataV1) GetEventId() []byte {
	if x != nil {
		return x.EventId
	}
	return nil
}

func (x *MailEventMetadataV1) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *MailEventMetadataV1) GetOccurredAtUnixMs() int64 {
	if x != nil {
		return x.OccurredAtUnixMs
	}
	return 0
}

func (x *MailEventMetadataV1) GetTraceparent() string {
	if x != nil {
		return x.Traceparent
	}
	return ""
}

func (x *MailEventMetadataV1) GetProducer() string {
	if x != nil {
		return x.Producer
	}
	return ""
}

type KafkaSourceV1 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// [COMMENT]: UUID 16-byte của Kafka binding; CP derive secret ref từ trusted Workspace/Zone scope.
	BrokerResourceId []byte `protobuf:"bytes,1,opt,name=broker_resource_id,json=brokerResourceId,proto3" json:"broker_resource_id,omitempty"`
	// [COMMENT]: Opaque Vault/secret reference; tuyệt đối không phải credential plaintext.
	SourceConfigRef string `protobuf:"bytes,2,opt,name=source_config_ref,json=sourceConfigRef,proto3" json:"source_config_ref,omitempty"`
	// [COMMENT]: Topic cụ thể đã được authorization; DP không nhận topic từ từng Kafka message.
	Topic string `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	// [COMMENT]: Consumer group ổn định của connector.
	ConsumerGroup string `protobuf:"bytes,4,opt,name=consumer_group,json=consumerGroup,proto3" json:"consumer_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KafkaSourceV1) Reset() {
	*x = KafkaSourceV1{}
	mi := &file_mail_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KafkaSourceV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KafkaSourceV1) ProtoMessage() {}

func (x *KafkaSourceV1) ProtoReflect() protoreflect.Message {
	mi := &file_mail_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KafkaSourceV1.ProtoReflect.Descriptor instead.
func (*KafkaSourceV1) Descriptor() ([]byte, []int) {
	return file_mail_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *KafkaSourceV1) GetBrokerResourceId() []byte {
	if x != nil {
		return x.BrokerResourceId
	}
	return nil
}

func (x *KafkaSourceV1) GetSourceConfigRef() string {
	if x != nil {
		return x.SourceConfigRef
	}
	return ""
}

func (x *KafkaSourceV1) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *KafkaSourceV1) GetConsumerGroup() string {
	if x != nil {
		return x.ConsumerGroup
	}
	return ""
}

type MailMessageMappingV1 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// [COMMENT]: JSONPath tùy chọn lấy external event id cho audit; không dùng thay Kafka coordinate để dedupe.
	ExternalMessageIdJsonPath string `protobuf:"bytes,1,opt,name=external_message_id_json_path,json=externalMessageIdJsonPath,proto3" json:"external_message_id_json_path,omitempty"`
	// [COMMENT]: JSONPath bắt buộc trả đúng một recipient scalar.
	RecipientJsonPath string `protobuf:"bytes,2,opt,name=recipient_json_path,json=recipientJsonPath,proto3" json:"recipient_json_path,omitempty"`
	// [COMMENT]: Template variable name -> JSONPath scalar; object/array bị reject nếu schema không cho phép.
	VariableJsonPaths map[string]string `protobuf:"bytes,3,rep,name=variable_json_paths,json=variableJsonPaths,proto3" json:"variable_json_paths,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MailMessageMappingV1) Reset() {
	*x = MailMessageMappingV1{}
	mi := &file_mail_runtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailMessageMappingV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailMessageMappingV1) ProtoMessage() {}

func (x *MailMessageMappingV1) ProtoReflect() protoreflect.Message {
	mi := &file_mail_runtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailMessageMappingV1.ProtoReflect.Descriptor instead.
func (*MailMessageMappingV1) Descriptor() ([]byte, []int) {
	return file_mail_runtime_proto_rawDescGZIP(), []int{2}
}

func (x *MailMessageMappingV1) GetExternalMessageIdJsonPath() string {
	if x != nil {
		return x.ExternalMessageIdJsonPath
	}
	return ""
}

func (x *MailMessageMappingV1) GetRecipientJsonPath() string {
	if x != nil {
		return x.RecipientJsonPath
	}
	return ""
}

func (x *MailMessageMappingV1) GetVariableJsonPaths() map[string]string {
	if x != nil {
		return x.VariableJsonPaths
	}
	return nil
}

type MailConsumerUpsertV1 struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Metadata *MailEventMetadataV1   `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// [COMMENT]: UUID 16-byte của consumer aggregate; globally unique để DP không cần workspace prefix.
	ConsumerId []byte `protobuf:"bytes,2,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	// [COMMENT]: Monotonic version; DP chỉ apply version lớn hơn version hiện có.
	ConfigVersion uint64                `protobuf:"varint,3,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	Kafka         *KafkaSourceV1        `protobuf:"bytes,4,opt,name=kafka,proto3" json:"kafka,omitempty"`
	Mapping       *MailMessageMappingV1 `protobuf:"bytes,5,opt,name=mapping,proto3" json:"mapping,omitempty"`
	// [COMMENT]: Template identity được bind cố định tại config, không đọc từ Kafka payload.
	TemplateId string `protobuf:"bytes,6,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	// [COMMENT]: Immutable content version; luôn lớn hơn 0.
	TemplateVersion uint64 `protobuf:"varint,7,opt,name=template_version,json=templateVersion,proto3" json:"template_version,omitempty"`
	// [COMMENT]: Sender identity được bind cố định tại config, không đọc từ Kafka payload.
	SenderProfileId string `protobuf:"bytes,8,opt,name=sender_profile_id,json=senderProfileId,proto3" json:"sender_profile_id,omitempty"`
	// [COMMENT]: Immutable sender version; luôn lớn hơn 0.
	SenderVersion uint64                   `protobuf:"varint,9,opt,name=sender_version,json=senderVersion,proto3" json:"sender_version,omitempty"`
	DesiredState  MailConsumerDesiredState `protobuf:"varint,10,opt,name=desired_state,json=desiredState,proto3,enum=mail.runtime.v1.MailConsumerDesiredState" json:"desired_state,omitempty"`
	// [COMMENT]: Số runtime slots tối đa; lease/fencing tại Zone giới hạn số Kafka connection thực tế.
	Parallelism uint32 `protobuf:"varint,11,opt,name=parallelism,proto3" json:"parallelism,omitempty"`
	// [COMMENT]: SHA-256 32-byte của canonical config để phát hiện cùng version nhưng khác payload.
	ConfigSha256  []byte `protobuf:"bytes,12,opt,name=config_sha256,json=configSha256,proto3" json:"config_sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailConsumerUpsertV1) Reset() {
	*x = MailConsumerUpsertV1{}
	mi := &file_mail_runtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailConsumerUpsertV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailConsumerUpsertV1) ProtoMessage() {}

func (x *MailConsumerUpsertV1) ProtoReflect() protoreflect.Message {
	mi := &file_mail_runtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailConsumerUpsertV1.ProtoReflect.Descriptor instead.
func (*MailConsumerUpsertV1) Descriptor() ([]byte, []int) {
	return file_mail_runtime_proto_rawDescGZIP(), []int{3}
}

func (x *MailConsumerUpsertV1) GetMetadata() *MailEventMetadataV1 {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *MailConsumerUpsertV1) GetConsumerId() []byte {
	if x != nil {
		return x.ConsumerId
	}
	return nil
}

func (x *MailConsumerUpsertV1) GetConfigVersion() uint64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

func (x *MailConsumerUpsertV1) GetKafka() *KafkaSourceV1 {
	if x != nil {
		return x.Kafka
	}
	return nil
}

func (x *MailConsumerUpsertV1) GetMapping() *MailMessageMappingV1 {
	if x != nil {
		return x.Mapping
	}
	return nil
}

func (x *MailConsumerUpsertV1) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *MailConsumerUpsertV1) GetTemplateVersion() uint64 {
	if x != nil {
		return x.TemplateVersion
	}
	return 0
}

func (x *MailConsumerUpsertV1) GetSenderProfileId() string {
	if x != nil {
		return x.SenderProfileId
	}
	return ""
}

func (x *MailConsumerUpsertV1) GetSenderVersion() uint64 {
	if x != nil {
		return x.SenderVersion
	}
	return 0
}

func (x *MailConsumerUpsertV1) GetDesiredState() MailConsumerDesiredState {
	if x != nil {
		return x.DesiredState
	}
	return MailConsumerDesiredState_MAIL_CONSUMER_DESIRED_STATE_UNSPECIFIED
}

func (x *MailConsumerUpsertV1) GetParallelism() uint32 {
	if x != nil {
		return x.Parallelism
	}
	return 0
}

func (x *MailConsumerUpsertV1) GetConfigSha256() []byte {
	if x != nil {
		return x.ConfigSha256
	}
	return nil
}

type MailConsumerDeleteV1 struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Metadata   *MailEventMetadataV1   `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ConsumerId []byte                 `protobuf:"bytes,2,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	// [COMMENT]: Tombstone version phải lớn hơn mọi upsert version trước đó.
	ConfigVersion uint64 `protobuf:"varint,3,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	// [COMMENT]: DP ngừng poll, drain outstanding rồi đóng connection trong giới hạn này.
	DrainTimeoutSeconds uint32 `protobuf:"varint,4,opt,name=drain_timeout_seconds,json=drainTimeoutSeconds,proto3" json:"drain_timeout_seconds,omitempty"`
	// [COMMENT]: Sanitized operator reason; không chứa secret hoặc customer payload.
	Reason        string `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailConsumerDeleteV1) Reset() {
	*x = MailConsumerDeleteV1{}
	mi := &file_mail_runtime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailConsumerDeleteV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailConsumerDeleteV1) ProtoMessage() {}

func (x *MailConsumerDeleteV1) ProtoReflect() protoreflect.Message {
	mi := &file_mail_runtime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailConsumerDeleteV1.ProtoReflect.Descriptor instead.
func (*MailConsumerDeleteV1) Descriptor() ([]byte, []int) {
	return file_mail_runtime_proto_rawDescGZIP(), []int{4}
}

func (x *MailConsumerDeleteV1) GetMetadata() *MailEventMetadataV1 {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *MailConsumerDeleteV1) GetConsumerId() []byte {
	if x != nil {
		return x.ConsumerId
	}
	return nil
}

func (x *MailConsumerDeleteV1) GetConfigVersion() uint64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

func (x *MailConsumerDeleteV1) GetDrainTimeoutSeconds() uint32 {
	if x != nil {
		return x.DrainTimeoutSeconds
	}
	return 0
}

func (x *MailConsumerDeleteV1) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type MailConsumerRuntimeReportedV1 struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Metadata   *MailEventMetadataV1   `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ConsumerId []byte                 `protobuf:"bytes,2,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	// [COMMENT]: Config version mà runtime thực tế đã observe/apply.
	ConfigVersion uint64                   `protobuf:"varint,3,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	RuntimeState  MailConsumerRuntimeState `protobuf:"varint,4,opt,name=runtime_state,json=runtimeState,proto3,enum=mail.runtime.v1.MailConsumerRuntimeState" json:"runtime_state,omitempty"`
	// [COMMENT]: Pod/instance opaque id; chỉ dùng diagnostics, không dùng làm metric label.
	InstanceId string `protobuf:"bytes,5,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// [COMMENT]: Generation tăng sau mỗi COW swap/restart để fence runtime cũ.
	RuntimeGeneration uint64 `protobuf:"varint,6,opt,name=runtime_generation,json=runtimeGeneration,proto3" json:"runtime_generation,omitempty"`
	// [COMMENT]: Tổng lag snapshot, không phải source cho billing hay authorization.
	ConsumerLag uint64 `protobuf:"varint,7,opt,name=consumer_lag,json=consumerLag,proto3" json:"consumer_lag,omitempty"`
	// [COMMENT]: Error taxonomy ổn định; rỗng khi runtime không ERROR.
	ErrorCode string `protobuf:"bytes,8,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	// [COMMENT]: Sanitized diagnostics, không chứa endpoint credential/message payload.
	ErrorMessage string `protobuf:"bytes,9,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// [COMMENT]: Monotonic trong cùng instance+generation; tạo event id mới cho từng heartbeat.
	ReportSequence uint64 `protobuf:"varint,10,opt,name=report_sequence,json=reportSequence,proto3" json:"report_sequence,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MailConsumerRuntimeReportedV1) Reset() {
	*x = MailConsumerRuntimeReportedV1{}
	mi := &file_mail_runtime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailConsumerRuntimeReportedV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailConsumerRuntimeReportedV1) ProtoMessage() {}

func (x *MailConsumerRuntimeReportedV1) ProtoReflect() protoreflect.Message {
	mi := &file_mail_runtime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailConsumerRuntimeReportedV1.ProtoReflect.Descriptor instead.
func (*MailConsumerRuntimeReportedV1) Descriptor() ([]byte, []int) {
	return file_mail_runtime_proto_rawDescGZIP(), []int{5}
}

func (x *MailConsumerRuntimeReportedV1) GetMetadata() *MailEventMetadataV1 {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *MailConsumerRuntimeReportedV1) GetConsumerId() []byte {
	if x != nil {
		return x.ConsumerId
	}
	return nil
}

func (x *MailConsumerRuntimeReportedV1) GetConfigVersion() uint64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

func (x *MailConsumerRuntimeReportedV1) GetRuntimeState() MailConsumerRuntimeState {
	if x != nil {
		return x.RuntimeState
	}
	return MailConsumerRuntimeState_MAIL_CONSUMER_RUNTIME_STATE_UNSPECIFIED
}

func (x *MailConsumerRuntimeReportedV1) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *MailConsumerRuntimeReportedV1) GetRuntimeGeneration() uint64 {
	if x != nil {
		return x.RuntimeGeneration
	}
	return 0
}

func (x *MailConsumerRuntimeReportedV1) GetConsumerLag() uint64 {
	if x != nil {
		return x.ConsumerLag
	}
	return 0
}

func (x *MailConsumerRuntimeReportedV1) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *MailConsumerRuntimeReportedV1) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *MailConsumerRuntimeReportedV1) GetReportSequence() uint64 {
	if x != nil {
		return x.ReportSequence
	}
	return 0
}

type MailTemplateVersionPublishedV1 struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Metadata *MailEventMetadataV1   `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// [COMMENT]: Globally unique identity; scope/workspace đã được CP xử lý trước projection.
	TemplateId string `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	// [COMMENT]: Monotonic lifecycle revision dùng chống event publish/archive đến sai thứ tự.
	TemplateRevision uint64 `protobuf:"varint,3,opt,name=template_revision,json=templateRevision,proto3" json:"template_revision,omitempty"`
	// [COMMENT]: Immutable content version được consumer pin; luôn lớn hơn 0.
	TemplateVersion uint64 `protobuf:"varint,4,opt,name=template_version,json=templateVersion,proto3" json:"template_version,omitempty"`
	SubjectTemplate string `protobuf:"bytes,5,opt,name=subject_template,json=subjectTemplate,proto3" json:"subject_template,omitempty"`
	TextTemplate    string `protobuf:"bytes,6,opt,name=text_template,json=textTemplate,proto3" json:"text_template,omitempty"`
	HtmlTemplate    string `protobuf:"bytes,7,opt,name=html_template,json=htmlTemplate,proto3" json:"html_template,omitempty"`
	// [COMMENT]: Canonical UTF-8 JSON schema cho variables; DP validate trước render.
	VariableSchemaJson []byte `protobuf:"bytes,8,opt,name=variable_schema_json,json=variableSchemaJson,proto3" json:"variable_schema_json,omitempty"`
	// [COMMENT]: SHA-256 32-byte của canonical immutable template content.
	ContentSha256 []byte `protobuf:"bytes,9,opt,name=content_sha256,json=contentSha256,proto3" json:"content_sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailTemplateVersionPublishedV1) Reset() {
	*x = MailTemplateVersionPublishedV1{}
	mi := &file_mail_runtime_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailTemplateVersionPublishedV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailTemplateVersionPublishedV1) ProtoMessage() {}

func (x *MailTemplateVersionPublishedV1) ProtoReflect() protoreflect.Message {
	mi := &file_mail_runtime_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailTemplateVersionPublishedV1.ProtoReflect.Descriptor instead.
func (*MailTemplateVersionPublishedV1) Descriptor() ([]byte, []int) {
	return file_mail_runtime_proto_rawDescGZIP(), []int{6}
}

func (x *MailTemplateVersionPublishedV1) GetMetadata() *MailEventMetadataV1 {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *MailTemplateVersionPublishedV1) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *MailTemplateVersionPublishedV1) GetTemplateRevision() uint64 {
	if x != nil {
		return x.TemplateRevision
	}
	return 0
}

func (x *MailTemplateVersionPublishedV1) GetTemplateVersion() uint64 {
	if x != nil {
		return x.TemplateVersion
	}
	return 0
}

func (x *MailTemplateVersionPublishedV1) GetSubjectTemplate() string {
	if x != nil {
		return x.SubjectTemplate
	}
	return ""
}

func (x *MailTemplateVersionPublishedV1) GetTextTemplate() string {
	if x != nil {
		return x.TextTemplate
	}
	return ""
}

func (x *MailTemplateVersionPublishedV1) GetHtmlTemplate() string {
	if x != nil {
		return x.HtmlTemplate
	}
	return ""
}

func (x *MailTemplateVersionPublishedV1) GetVariableSchemaJson() []byte {
	if x != nil {
		return x.VariableSchemaJson
	}
	return nil
}

func (x *MailTemplateVersionPublishedV1) GetContentSha256() []byte {
	if x != nil {
		return x.ContentSha256
	}
	return nil
}

type MailTemplateArchivedV1 struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Metadata   *MailEventMetadataV1   `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	TemplateId string                 `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	// [COMMENT]: Revision tombstone lớn hơn mọi lifecycle revision trước đó.
	TemplateRevision uint64 `protobuf:"varint,3,opt,name=template_revision,json=templateRevision,proto3" json:"template_revision,omitempty"`
	// [COMMENT]: Version snapshots vẫn được giữ để drain consumer đã pin; archive không hard delete content.
	LastPublishedVersion uint64 `protobuf:"varint,4,opt,name=last_published_version,json=lastPublishedVersion,proto3" json:"last_published_version,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *MailTemplateArchivedV1) Reset() {
	*x = MailTemplateArchivedV1{}
	mi := &file_mail_runtime_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailTemplateArchivedV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailTemplateArchivedV1) ProtoMessage() {}

func (x *MailTemplateArchivedV1) ProtoReflect() protoreflect.Message {
	mi := &file_mail_runtime_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailTemplateArchivedV1.ProtoReflect.Descriptor instead.
func (*MailTemplateArchivedV1) Descriptor() ([]byte, []int) {
	return file_mail_runtime_proto_rawDescGZIP(), []int{7}
}

func (x *MailTemplateArchivedV1) GetMetadata() *MailEventMetadataV1 {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *MailTemplateArchivedV1) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *MailTemplateArchivedV1) GetTemplateRevision() uint64 {
	if x != nil {
		return x.TemplateRevision
	}
	return 0
}

func (x *MailTemplateArchivedV1) GetLastPublishedVersion() uint64 {
	if x != nil {
		return x.LastPublishedVersion
	}
	return 0
}

type KafkaMessageCoordinateV1 struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Topic     string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition int32                  `protobuf:"varint,2,opt,name=partition,proto3" json:"partition,omitempty"`
	Offset    int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	// [COMMENT]: Phase đầu luôn 0 vì một Kafka message tương ứng một recipient.
	RecipientIndex uint32 `protobuf:"varint,4,opt,name=recipient_index,json=recipientIndex,proto3" json:"recipient_index,omitempty"`
	// [COMMENT]: Giá trị audit tùy chọn lấy từ mapping; Kafka coordinate mới là dedupe authority.
	ExternalMessageId string `protobuf:"bytes,5,opt,name=external_message_id,json=externalMessageId,proto3" json:"external_message_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *KafkaMessageCoordinateV1) Reset() {
	*x = KafkaMessageCoordinateV1{}
	mi := &file_mail_runtime_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KafkaMessageCoordinateV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KafkaMessageCoordinateV1) ProtoMessage() {}

func (x *KafkaMessageCoordinateV1) ProtoReflect() protoreflect.Message {
	mi := &file_mail_runtime_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KafkaMessageCoordinateV1.ProtoReflect.Descriptor instead.
func (*KafkaMessageCoordinateV1) Descriptor() ([]byte, []int) {
	return file_mail_runtime_proto_rawDescGZIP(), []int{8}
}

func (x *KafkaMessageCoordinateV1) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *KafkaMessageCoordinateV1) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *KafkaMessageCoordinateV1) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *KafkaMessageCoordinateV1) GetRecipientIndex() uint32 {
	if x != nil {
		return x.RecipientIndex
	}
	return 0
}

func (x *KafkaMessageCoordinateV1) GetExternalMessageId() string {
	if x != nil {
		return x.ExternalMessageId
	}
	return ""
}

type MailExecutionResultV1 struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Metadata *MailEventMetadataV1   `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// [COMMENT]: UUIDv5 16-byte từ consumer + topic + partition + offset + recipient_index.
	SubmissionId []byte `protobuf:"bytes,2,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	// [COMMENT]: Monotonic per-submission state version; CP bỏ qua result cũ/out-of-order.
	StateVersion          uint64                    `protobuf:"varint,3,opt,name=state_version,json=stateVersion,proto3" json:"state_version,omitempty"`
	ConsumerId            []byte                    `protobuf:"bytes,4,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	ConsumerConfigVersion uint64                    `protobuf:"varint,5,opt,name=consumer_config_version,json=consumerConfigVersion,proto3" json:"consumer_config_version,omitempty"`
	Source                *KafkaMessageCoordinateV1 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	// [COMMENT]: PII cần cho history; không log/metric và phải mã hóa hoặc retention tại CP.
	Recipient       string              `protobuf:"bytes,7,opt,name=recipient,proto3" json:"recipient,omitempty"`
	TemplateId      string              `protobuf:"bytes,8,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	TemplateVersion uint64              `protobuf:"varint,9,opt,name=template_version,json=templateVersion,proto3" json:"template_version,omitempty"`
	SenderProfileId string              `protobuf:"bytes,10,opt,name=sender_profile_id,json=senderProfileId,proto3" json:"sender_profile_id,omitempty"`
	SenderVersion   uint64              `protobuf:"varint,11,opt,name=sender_version,json=senderVersion,proto3" json:"sender_version,omitempty"`
	Attempt         uint32              `protobuf:"varint,12,opt,name=attempt,proto3" json:"attempt,omitempty"`
	Status          MailExecutionStatus `protobuf:"varint,13,opt,name=status,proto3,enum=mail.runtime.v1.MailExecutionStatus" json:"status,omitempty"`
	// [COMMENT]: Chỉ true cho transient attempt; terminal status luôn false.
	Retryable bool   `protobuf:"varint,14,opt,name=retryable,proto3" json:"retryable,omitempty"`
	ErrorCode string `protobuf:"bytes,15,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	// [COMMENT]: Sanitized và bounded; không chứa raw JSON, variables hay rendered content.
	ErrorMessage string `protobuf:"bytes,16,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// [COMMENT]: Opaque JMAP submission id khi status SUBMITTED.
	JmapSubmissionId string `protobuf:"bytes,17,opt,name=jmap_submission_id,json=jmapSubmissionId,proto3" json:"jmap_submission_id,omitempty"`
	// [COMMENT]: SHA-256 32-byte phục vụ audit mà không lưu body.
	RenderedContentSha256 []byte `protobuf:"bytes,18,opt,name=rendered_content_sha256,json=renderedContentSha256,proto3" json:"rendered_content_sha256,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *MailExecutionResultV1) Reset() {
	*x = MailExecutionResultV1{}
	mi := &file_mail_runtime_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailExecutionResultV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailExecutionResultV1) ProtoMessage() {}

func (x *MailExecutionResultV1) ProtoReflect() protoreflect.Message {
	mi := &file_mail_runtime_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailExecutionResultV1.ProtoReflect.Descriptor instead.
func (*MailExecutionResultV1) Descriptor() ([]byte, []int) {
	return file_mail_runtime_proto_rawDescGZIP(), []int{9}
}

func (x *MailExecutionResultV1) GetMetadata() *MailEventMetadataV1 {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *MailExecutionResultV1) GetSubmissionId() []byte {
	if x != nil {
		return x.SubmissionId
	}
	return nil
}

func (x *MailExecutionResultV1) GetStateVersion() uint64 {
	if x != nil {
		return x.StateVersion
	}
	return 0
}

func (x *MailExecutionResultV1) GetConsumerId() []byte {
	if x != nil {
		return x.ConsumerId
	}
	return nil
}

func (x *MailExecutionResultV1) GetConsumerConfigVersion() uint64 {
	if x != nil {
		return x.ConsumerConfigVersion
	}
	return 0
}

func (x *MailExecutionResultV1) GetSource() *KafkaMessageCoordinateV1 {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *MailExecutionResultV1) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *MailExecutionResultV1) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *MailExecutionResultV1) GetTemplateVersion() uint64 {
	if x != nil {
		return x.TemplateVersion
	}
	return 0
}

func (x *MailExecutionResultV1) GetSenderProfileId() string {
	if x != nil {
		return x.SenderProfileId
	}
	return ""
}

func (x *MailExecutionResultV1) GetSenderVersion() uint64 {
	if x != nil {
		return x.SenderVersion
	}
	return 0
}

func (x *MailExecutionResultV1) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *MailExecutionResultV1) GetStatus() MailExecutionStatus {
	if x != nil {
		return x.Status
	}
	return MailExecutionStatus_MAIL_EXECUTION_STATUS_UNSPECIFIED
}

func (x *MailExecutionResultV1) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *MailExecutionResultV1) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *MailExecutionResultV1) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *MailExecutionResultV1) GetJmapSubmissionId() string {
	if x != nil {
		return x.JmapSubmissionId
	}
	return ""
}

func (x *MailExecutionResultV1) GetRenderedContentSha256() []byte {
	if x != nil {
		return x.RenderedContentSha256
	}
	return nil
}

var File_mail_runtime_proto protoreflect.FileDescriptor

const file_mail_runtime_proto_rawDesc = "" +
	"\n" +
	"\x12mail_runtime.proto\x12\x0fmail.runtime.v1\"\xc4\x01\n" +
	"\x13MailEventMetadataV1\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\fR\aeventId\x12%\n" +
	"\x0eschema_version\x18\x02 \x01(\rR\rschemaVersion\x12-\n" +
	"\x13occurred_at_unix_ms\x18\x03 \x01(\x03R\x10occurredAtUnixMs\x12 \n" +
	"\vtraceparent\x18\x04 \x01(\tR\vtraceparent\x12\x1a\n" +
	"\bproducer\x18\x05 \x01(\tR\bproducer\"\xa6\x01\n" +
	"\rKafkaSourceV1\x12,\n" +
	"\x12broker_resource_id\x18\x01 \x01(\fR\x10brokerResourceId\x12*\n" +
	"\x11source_config_ref\x18\x02 \x01(\tR\x0fsourceConfigRef\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12%\n" +
	"\x0econsumer_group\x18\x04 \x01(\tR\rconsumerGroup\"\xbc\x02\n" +
	"\x14MailMessageMappingV1\x12@\n" +
	"\x1dexternal_message_id_json_path\x18\x01 \x01(\tR\x19externalMessageIdJsonPath\x12.\n" +
	"\x13recipient_json_path\x18\x02 \x01(\tR\x11recipientJsonPath\x12l\n" +
	"\x13variable_json_paths\x18\x03 \x03(\v2<.mail.runtime.v1.MailMessageMappingV1.VariableJsonPathsEntryR\x11variableJsonPaths\x1aD\n" +
	"\x16VariableJsonPathsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcd\x04\n" +
	"\x14MailConsumerUpsertV1\x12@\n" +
	"\bmetadata\x18\x01 \x01(\v2$.mail.runtime.v1.MailEventMetadataV1R\bmetadata\x12\x1f\n" +
	"\vconsumer_id\x18\x02 \x01(\fR\n" +
	"consumerId\x12%\n" +
	"\x0econfig_version\x18\x03 \x01(\x04R\rconfigVersion\x124\n" +
	"\x05kafka\x18\x04 \x01(\v2\x1e.mail.runtime.v1.KafkaSourceV1R\x05kafka\x12?\n" +
	"\amapping\x18\x05 \x01(\v2%.mail.runtime.v1.MailMessageMappingV1R\amapping\x12\x1f\n" +
	"\vtemplate_id\x18\x06 \x01(\tR\n" +
	"templateId\x12)\n" +
	"\x10template_version\x18\a \x01(\x04R\x0ftemplateVersion\x12*\n" +
	"\x11sender_profile_id\x18\b \x01(\tR\x0fsenderProfileId\x12%\n" +
	"\x0esender_version\x18\t \x01(\x04R\rsenderVersion\x12N\n" +
	"\rdesired_state\x18\n" +
	" \x01(\x0e2).mail.runtime.v1.MailConsumerDesiredStateR\fdesiredState\x12 \n" +
	"\vparallelism\x18\v \x01(\rR\vparallelism\x12#\n" +
	"\rconfig_sha256\x18\f \x01(\fR\fconfigSha256\"\xec\x01\n" +
	"\x14MailConsumerDeleteV1\x12@\n" +
	"\bmetadata\x18\x01 \x01(\v2$.mail.runtime.v1.MailEventMetadataV1R\bmetadata\x12\x1f\n" +
	"\vconsumer_id\x18\x02 \x01(\fR\n" +
	"consumerId\x12%\n" +
	"\x0econfig_version\x18\x03 \x01(\x04R\rconfigVersion\x122\n" +
	"\x15drain_timeout_seconds\x18\x04 \x01(\rR\x13drainTimeoutSeconds\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"\xd9\x03\n" +
	"\x1dMailConsumerRuntimeReportedV1\x12@\n" +
	"\bmetadata\x18\x01 \x01(\v2$.mail.runtime.v1.MailEventMetadataV1R\bmetadata\x12\x1f\n" +
	"\vconsumer_id\x18\x02 \x01(\fR\n" +
	"consumerId\x12%\n" +
	"\x0econfig_version\x18\x03 \x01(\x04R\rconfigVersion\x12N\n" +
	"\rruntime_state\x18\x04 \x01(\x0e2).mail.runtime.v1.MailConsumerRuntimeStateR\fruntimeState\x12\x1f\n" +
	"\vinstance_id\x18\x05 \x01(\tR\n" +
	"instanceId\x12-\n" +
	"\x12runtime_generation\x18\x06 \x01(\x04R\x11runtimeGeneration\x12!\n" +
	"\fconsumer_lag\x18\a \x01(\x04R\vconsumerLag\x12\x1d\n" +
	"\n" +
	"error_code\x18\b \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\t \x01(\tR\ferrorMessage\x12'\n" +
	"\x0freport_sequence\x18\n" +
	" \x01(\x04R\x0ereportSequence\"\xa9\x03\n" +
	"\x1eMailTemplateVersionPublishedV1\x12@\n" +
	"\bmetadata\x18\x01 \x01(\v2$.mail.runtime.v1.MailEventMetadataV1R\bmetadata\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\x12+\n" +
	"\x11template_revision\x18\x03 \x01(\x04R\x10templateRevision\x12)\n" +
	"\x10template_version\x18\x04 \x01(\x04R\x0ftemplateVersion\x12)\n" +
	"\x10subject_template\x18\x05 \x01(\tR\x0fsubjectTemplate\x12#\n" +
	"\rtext_template\x18\x06 \x01(\tR\ftextTemplate\x12#\n" +
	"\rhtml_template\x18\a \x01(\tR\fhtmlTemplate\x120\n" +
	"\x14variable_schema_json\x18\b \x01(\fR\x12variableSchemaJson\x12%\n" +
	"\x0econtent_sha256\x18\t \x01(\fR\rcontentSha256\"\xde\x01\n" +
	"\x16MailTemplateArchivedV1\x12@\n" +
	"\bmetadata\x18\x01 \x01(\v2$.mail.runtime.v1.MailEventMetadataV1R\bmetadata\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\x12+\n" +
	"\x11template_revision\x18\x03 \x01(\x04R\x10templateRevision\x124\n" +
	"\x16last_published_version\x18\x04 \x01(\x04R\x14lastPublishedVersion\"\xbf\x01\n" +
	"\x18KafkaMessageCoordinateV1\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1c\n" +
	"\tpartition\x18\x02 \x01(\x05R\tpartition\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12'\n" +
	"\x0frecipient_index\x18\x04 \x01(\rR\x0erecipientIndex\x12.\n" +
	"\x13external_message_id\x18\x05 \x01(\tR\x11externalMessageId\"\x9c\x06\n" +
	"\x15MailExecutionResultV1\x12@\n" +
	"\bmetadata\x18\x01 \x01(\v2$.mail.runtime.v1.MailEventMetadataV1R\bmetadata\x12#\n" +
	"\rsubmission_id\x18\x02 \x01(\fR\fsubmissionId\x12#\n" +
	"\rstate_version\x18\x03 \x01(\x04R\fstateVersion\x12\x1f\n" +
	"\vconsumer_id\x18\x04 \x01(\fR\n" +
	"consumerId\x126\n" +
	"\x17consumer_config_version\x18\x05 \x01(\x04R\x15consumerConfigVersion\x12A\n" +
	"\x06source\x18\x06 \x01(\v2).mail.runtime.v1.KafkaMessageCoordinateV1R\x06source\x12\x1c\n" +
	"\trecipient\x18\a \x01(\tR\trecipient\x12\x1f\n" +
	"\vtemplate_id\x18\b \x01(\tR\n" +
	"templateId\x12)\n" +
	"\x10template_version\x18\t \x01(\x04R\x0ftemplateVersion\x12*\n" +
	"\x11sender_profile_id\x18\n" +
	" \x01(\tR\x0fsenderProfileId\x12%\n" +
	"\x0esender_version\x18\v \x01(\x04R\rsenderVersion\x12\x18\n" +
	"\aattempt\x18\f \x01(\rR\aattempt\x12<\n" +
	"\x06status\x18\r \x01(\x0e2$.mail.runtime.v1.MailExecutionStatusR\x06status\x12\x1c\n" +
	"\tretryable\x18\x0e \x01(\bR\tretryable\x12\x1d\n" +
	"\n" +
	"error_code\x18\x0f \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x10 \x01(\tR\ferrorMessage\x12,\n" +
	"\x12jmap_submission_id\x18\x11 \x01(\tR\x10jmapSubmissionId\x126\n" +
	"\x17rendered_content_sha256\x18\x12 \x01(\fR\x15renderedContentSha256*\x98\x01\n" +
	"\x18MailConsumerDesiredState\x12+\n" +
	"'MAIL_CONSUMER_DESIRED_STATE_UNSPECIFIED\x10\x00\x12&\n" +
	"\"MAIL_CONSUMER_DESIRED_STATE_PAUSED\x10\x01\x12'\n" +
	"#MAIL_CONSUMER_DESIRED_STATE_ENABLED\x10\x02*\xe6\x02\n" +
	"\x18MailConsumerRuntimeState\x12+\n" +
	"'MAIL_CONSUMER_RUNTIME_STATE_UNSPECIFIED\x10\x00\x12'\n" +
	"#MAIL_CONSUMER_RUNTIME_STATE_STOPPED\x10\x01\x12(\n" +
	"$MAIL_CONSUMER_RUNTIME_STATE_STARTING\x10\x02\x12'\n" +
	"#MAIL_CONSUMER_RUNTIME_STATE_RUNNING\x10\x03\x12&\n" +
	"\"MAIL_CONSUMER_RUNTIME_STATE_PAUSED\x10\x04\x12(\n" +
	"$MAIL_CONSUMER_RUNTIME_STATE_DRAINING\x10\x05\x12%\n" +
	"!MAIL_CONSUMER_RUNTIME_STATE_ERROR\x10\x06\x12(\n" +
	"$MAIL_CONSUMER_RUNTIME_STATE_DEGRADED\x10\a*\xe5\x02\n" +
	"\x13MailExecutionStatus\x12%\n" +
	"!MAIL_EXECUTION_STATUS_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eMAIL_EXECUTION_STATUS_CONSUMED\x10\x01\x12\"\n" +
	"\x1eMAIL_EXECUTION_STATUS_RENDERED\x10\x02\x12$\n" +
	" MAIL_EXECUTION_STATUS_SUBMITTING\x10\x03\x12)\n" +
	"%MAIL_EXECUTION_STATUS_RETRY_SCHEDULED\x10\x04\x12#\n" +
	"\x1fMAIL_EXECUTION_STATUS_SUBMITTED\x10\x05\x12\"\n" +
	"\x1eMAIL_EXECUTION_STATUS_REJECTED\x10\x06\x12 \n" +
	"\x1cMAIL_EXECUTION_STATUS_FAILED\x10\a\x12#\n" +
	"\x1fMAIL_EXECUTION_STATUS_AMBIGUOUS\x10\bB:Z8controlplane/internal/mail/transport/rpc/proto;mailprotob\x06proto3"

var (
	file_mail_runtime_proto_rawDescOnce sync.Once
	file_mail_runtime_proto_rawDescData []byte
)

func file_mail_runtime_proto_rawDescGZIP() []byte {
	file_mail_runtime_proto_rawDescOnce.Do(func() {
		file_mail_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mail_runtime_proto_rawDesc), len(file_mail_runtime_proto_rawDesc)))
	})
	return file_mail_runtime_proto_rawDescData
}

var file_mail_runtime_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_mail_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_mail_runtime_proto_goTypes = []any{
	(MailConsumerDesiredState)(0),          // 0: mail.runtime.v1.MailConsumerDesiredState
	(MailConsumerRuntimeState)(0),          // 1: mail.runtime.v1.MailConsumerRuntimeState
	(MailExecutionStatus)(0),               // 2: mail.runtime.v1.MailExecutionStatus
	(*MailEventMetadataV1)(nil),            // 3: mail.runtime.v1.MailEventMetadataV1
	(*KafkaSourceV1)(nil),                  // 4: mail.runtime.v1.KafkaSourceV1
	(*MailMessageMappingV1)(nil),           // 5: mail.runtime.v1.MailMessageMappingV1
	(*MailConsumerUpsertV1)(nil),           // 6: mail.runtime.v1.MailConsumerUpsertV1
	(*MailConsumerDeleteV1)(nil),           // 7: mail.runtime.v1.MailConsumerDeleteV1
	(*MailConsumerRuntimeReportedV1)(nil),  // 8: mail.runtime.v1.MailConsumerRuntimeReportedV1
	(*MailTemplateVersionPublishedV1)(nil), // 9: mail.runtime.v1.MailTemplateVersionPublishedV1
	(*MailTemplateArchivedV1)(nil),         // 10: mail.runtime.v1.MailTemplateArchivedV1
	(*KafkaMessageCoordinateV1)(nil),       // 11: mail.runtime.v1.KafkaMessageCoordinateV1
	(*MailExecutionResultV1)(nil),          // 12: mail.runtime.v1.MailExecutionResultV1
	nil,                                    // 13: mail.runtime.v1.MailMessageMappingV1.VariableJsonPathsEntry
}
var file_mail_runtime_proto_depIdxs = []int32{
	13, // 0: mail.runtime.v1.MailMessageMappingV1.variable_json_paths:type_name -> mail.runtime.v1.MailMessageMappingV1.VariableJsonPathsEntry
	3,  // 1: mail.runtime.v1.MailConsumerUpsertV1.metadata:type_name -> mail.runtime.v1.MailEventMetadataV1
	4,  // 2: mail.runtime.v1.MailConsumerUpsertV1.kafka:type_name -> mail.runtime.v1.KafkaSourceV1
	5,  // 3: mail.runtime.v1.MailConsumerUpsertV1.mapping:type_name -> mail.runtime.v1.MailMessageMappingV1
	0,  // 4: mail.runtime.v1.MailConsumerUpsertV1.desired_state:type_name -> mail.runtime.v1.MailConsumerDesiredState
	3,  // 5: mail.runtime.v1.MailConsumerDeleteV1.metadata:type_name -> mail.runtime.v1.MailEventMetadataV1
	3,  // 6: mail.runtime.v1.MailConsumerRuntimeReportedV1.metadata:type_name -> mail.runtime.v1.MailEventMetadataV1
	1,  // 7: mail.runtime.v1.MailConsumerRuntimeReportedV1.runtime_state:type_name -> mail.runtime.v1.MailConsumerRuntimeState
	3,  // 8: mail.runtime.v1.MailTemplateVersionPublishedV1.metadata:type_name -> mail.runtime.v1.MailEventMetadataV1
	3,  // 9: mail.runtime.v1.MailTemplateArchivedV1.metadata:type_name -> mail.runtime.v1.MailEventMetadataV1
	3,  // 10: mail.runtime.v1.MailExecutionResultV1.metadata:type_name -> mail.runtime.v1.MailEventMetadataV1
	11, // 11: mail.runtime.v1.MailExecutionResultV1.source:type_name -> mail.runtime.v1.KafkaMessageCoordinateV1
	2,  // 12: mail.runtime.v1.MailExecutionResultV1.status:type_name -> mail.runtime.v1.MailExecutionStatus
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_mail_runtime_proto_init() }
func file_mail_runtime_proto_init() {
	if File_mail_runtime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mail_runtime_proto_rawDesc), len(file_mail_runtime_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mail_runtime_proto_goTypes,
		DependencyIndexes: file_mail_runtime_proto_depIdxs,
		EnumInfos:         file_mail_runtime_proto_enumTypes,
		MessageInfos:      file_mail_runtime_proto_msgTypes,
	}.Build()
	File_mail_runtime_proto = out.File
	file_mail_runtime_proto_goTypes = nil
	file_mail_runtime_proto_depIdxs = nil
}
