// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: billing/pricing/storage/v1/storage_pricing_snapshot.proto

package storagepricingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StorageChargeKindV1 int32

const (
	StorageChargeKindV1_STORAGE_CHARGE_KIND_V1_UNSPECIFIED      StorageChargeKindV1 = 0
	StorageChargeKindV1_STORAGE_CHARGE_KIND_V1_CAPACITY_GB_HOUR StorageChargeKindV1 = 1
	StorageChargeKindV1_STORAGE_CHARGE_KIND_V1_NETWORK_IN_BYTE  StorageChargeKindV1 = 2
	StorageChargeKindV1_STORAGE_CHARGE_KIND_V1_NETWORK_OUT_BYTE StorageChargeKindV1 = 3
)

// Enum value maps for StorageChargeKindV1.
var (
	StorageChargeKindV1_name = map[int32]string{
		0: "STORAGE_CHARGE_KIND_V1_UNSPECIFIED",
		1: "STORAGE_CHARGE_KIND_V1_CAPACITY_GB_HOUR",
		2: "STORAGE_CHARGE_KIND_V1_NETWORK_IN_BYTE",
		3: "STORAGE_CHARGE_KIND_V1_NETWORK_OUT_BYTE",
	}
	StorageChargeKindV1_value = map[string]int32{
		"STORAGE_CHARGE_KIND_V1_UNSPECIFIED":      0,
		"STORAGE_CHARGE_KIND_V1_CAPACITY_GB_HOUR": 1,
		"STORAGE_CHARGE_KIND_V1_NETWORK_IN_BYTE":  2,
		"STORAGE_CHARGE_KIND_V1_NETWORK_OUT_BYTE": 3,
	}
)

func (x StorageChargeKindV1) Enum() *StorageChargeKindV1 {
	p := new(StorageChargeKindV1)
	*p = x
	return p
}

func (x StorageChargeKindV1) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StorageChargeKindV1) Descriptor() protoreflect.EnumDescriptor {
	return file_billing_pricing_storage_v1_storage_pricing_snapshot_proto_enumTypes[0].Descriptor()
}

func (StorageChargeKindV1) Type() protoreflect.EnumType {
	return &file_billing_pricing_storage_v1_storage_pricing_snapshot_proto_enumTypes[0]
}

func (x StorageChargeKindV1) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StorageChargeKindV1.Descriptor instead.
func (StorageChargeKindV1) EnumDescriptor() ([]byte, []int) {
	return file_billing_pricing_storage_v1_storage_pricing_snapshot_proto_rawDescGZIP(), []int{0}
}

type StoragePricingModelV1 int32

const (
	StoragePricingModelV1_STORAGE_PRICING_MODEL_V1_UNSPECIFIED      StoragePricingModelV1 = 0
	StoragePricingModelV1_STORAGE_PRICING_MODEL_V1_PROGRESSIVE_UNIT StoragePricingModelV1 = 1
)

// Enum value maps for StoragePricingModelV1.
var (
	StoragePricingModelV1_name = map[int32]string{
		0: "STORAGE_PRICING_MODEL_V1_UNSPECIFIED",
		1: "STORAGE_PRICING_MODEL_V1_PROGRESSIVE_UNIT",
	}
	StoragePricingModelV1_value = map[string]int32{
		"STORAGE_PRICING_MODEL_V1_UNSPECIFIED":      0,
		"STORAGE_PRICING_MODEL_V1_PROGRESSIVE_UNIT": 1,
	}
)

func (x StoragePricingModelV1) Enum() *StoragePricingModelV1 {
	p := new(StoragePricingModelV1)
	*p = x
	return p
}

func (x StoragePricingModelV1) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StoragePricingModelV1) Descriptor() protoreflect.EnumDescriptor {
	return file_billing_pricing_storage_v1_storage_pricing_snapshot_proto_enumTypes[1].Descriptor()
}

func (StoragePricingModelV1) Type() protoreflect.EnumType {
	return &file_billing_pricing_storage_v1_storage_pricing_snapshot_proto_enumTypes[1]
}

func (x StoragePricingModelV1) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StoragePricingModelV1.Descriptor instead.
func (StoragePricingModelV1) EnumDescriptor() ([]byte, []int) {
	return file_billing_pricing_storage_v1_storage_pricing_snapshot_proto_rawDescGZIP(), []int{1}
}

type StorageRawInputUnitV1 int32

const (
	StorageRawInputUnitV1_STORAGE_RAW_INPUT_UNIT_V1_UNSPECIFIED StorageRawInputUnitV1 = 0
	StorageRawInputUnitV1_STORAGE_RAW_INPUT_UNIT_V1_BYTE_HOUR   StorageRawInputUnitV1 = 1
	StorageRawInputUnitV1_STORAGE_RAW_INPUT_UNIT_V1_BYTE        StorageRawInputUnitV1 = 2
)

// Enum value maps for StorageRawInputUnitV1.
var (
	StorageRawInputUnitV1_name = map[int32]string{
		0: "STORAGE_RAW_INPUT_UNIT_V1_UNSPECIFIED",
		1: "STORAGE_RAW_INPUT_UNIT_V1_BYTE_HOUR",
		2: "STORAGE_RAW_INPUT_UNIT_V1_BYTE",
	}
	StorageRawInputUnitV1_value = map[string]int32{
		"STORAGE_RAW_INPUT_UNIT_V1_UNSPECIFIED": 0,
		"STORAGE_RAW_INPUT_UNIT_V1_BYTE_HOUR":   1,
		"STORAGE_RAW_INPUT_UNIT_V1_BYTE":        2,
	}
)

func (x StorageRawInputUnitV1) Enum() *StorageRawInputUnitV1 {
	p := new(StorageRawInputUnitV1)
	*p = x
	return p
}

func (x StorageRawInputUnitV1) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StorageRawInputUnitV1) Descriptor() protoreflect.EnumDescriptor {
	return file_billing_pricing_storage_v1_storage_pricing_snapshot_proto_enumTypes[2].Descriptor()
}

func (StorageRawInputUnitV1) Type() protoreflect.EnumType {
	return &file_billing_pricing_storage_v1_storage_pricing_snapshot_proto_enumTypes[2]
}

func (x StorageRawInputUnitV1) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StorageRawInputUnitV1.Descriptor instead.
func (StorageRawInputUnitV1) EnumDescriptor() ([]byte, []int) {
	return file_billing_pricing_storage_v1_storage_pricing_snapshot_proto_rawDescGZIP(), []int{2}
}

// StoragePricingSnapshotCacheEntryV1 is the Storage-owned binary value stored
// in its Redis L2 cache. It is not the cross-module pricing publish event.
type StoragePricingSnapshotCacheEntryV1 struct {
	state                   protoimpl.MessageState           `protogen:"open.v1"`
	PricingScheduleId       []byte                           `protobuf:"bytes,1,opt,name=pricing_schedule_id,json=pricingScheduleId,proto3" json:"pricing_schedule_id,omitempty"` // exactly 16 UUID bytes
	VersionId               []byte                           `protobuf:"bytes,2,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`                           // exactly 16 UUID bytes
	ScheduleCode            string                           `protobuf:"bytes,3,opt,name=schedule_code,json=scheduleCode,proto3" json:"schedule_code,omitempty"`
	ChargeKind              StorageChargeKindV1              `protobuf:"varint,4,opt,name=charge_kind,json=chargeKind,proto3,enum=billing.pricing.storage.v1.StorageChargeKindV1" json:"charge_kind,omitempty"`
	PricingModel            StoragePricingModelV1            `protobuf:"varint,5,opt,name=pricing_model,json=pricingModel,proto3,enum=billing.pricing.storage.v1.StoragePricingModelV1" json:"pricing_model,omitempty"`
	RawInputUnit            StorageRawInputUnitV1            `protobuf:"varint,6,opt,name=raw_input_unit,json=rawInputUnit,proto3,enum=billing.pricing.storage.v1.StorageRawInputUnitV1" json:"raw_input_unit,omitempty"`
	VersionNumber           uint32                           `protobuf:"varint,7,opt,name=version_number,json=versionNumber,proto3" json:"version_number,omitempty"`
	EffectiveFromUnixMicros int64                            `protobuf:"varint,8,opt,name=effective_from_unix_micros,json=effectiveFromUnixMicros,proto3" json:"effective_from_unix_micros,omitempty"`
	EffectiveToUnixMicros   *int64                           `protobuf:"varint,9,opt,name=effective_to_unix_micros,json=effectiveToUnixMicros,proto3,oneof" json:"effective_to_unix_micros,omitempty"`
	ChecksumSha256          []byte                           `protobuf:"bytes,10,opt,name=checksum_sha256,json=checksumSha256,proto3" json:"checksum_sha256,omitempty"` // exactly 32 bytes
	Currency                string                           `protobuf:"bytes,11,opt,name=currency,proto3" json:"currency,omitempty"`
	Brackets                []*StoragePricingScalarBracketV1 `protobuf:"bytes,12,rep,name=brackets,proto3" json:"brackets,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *StoragePricingSnapshotCacheEntryV1) Reset() {
	*x = StoragePricingSnapshotCacheEntryV1{}
	mi := &file_billing_pricing_storage_v1_storage_pricing_snapshot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoragePricingSnapshotCacheEntryV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoragePricingSnapshotCacheEntryV1) ProtoMessage() {}

func (x *StoragePricingSnapshotCacheEntryV1) ProtoReflect() protoreflect.Message {
	mi := &file_billing_pricing_storage_v1_storage_pricing_snapshot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoragePricingSnapshotCacheEntryV1.ProtoReflect.Descriptor instead.
func (*StoragePricingSnapshotCacheEntryV1) Descriptor() ([]byte, []int) {
	return file_billing_pricing_storage_v1_storage_pricing_snapshot_proto_rawDescGZIP(), []int{0}
}

func (x *StoragePricingSnapshotCacheEntryV1) GetPricingScheduleId() []byte {
	if x != nil {
		return x.PricingScheduleId
	}
	return nil
}

func (x *StoragePricingSnapshotCacheEntryV1) GetVersionId() []byte {
	if x != nil {
		return x.VersionId
	}
	return nil
}

func (x *StoragePricingSnapshotCacheEntryV1) GetScheduleCode() string {
	if x != nil {
		return x.ScheduleCode
	}
	return ""
}

func (x *StoragePricingSnapshotCacheEntryV1) GetChargeKind() StorageChargeKindV1 {
	if x != nil {
		return x.ChargeKind
	}
	return StorageChargeKindV1_STORAGE_CHARGE_KIND_V1_UNSPECIFIED
}

func (x *StoragePricingSnapshotCacheEntryV1) GetPricingModel() StoragePricingModelV1 {
	if x != nil {
		return x.PricingModel
	}
	return StoragePricingModelV1_STORAGE_PRICING_MODEL_V1_UNSPECIFIED
}

func (x *StoragePricingSnapshotCacheEntryV1) GetRawInputUnit() StorageRawInputUnitV1 {
	if x != nil {
		return x.RawInputUnit
	}
	return StorageRawInputUnitV1_STORAGE_RAW_INPUT_UNIT_V1_UNSPECIFIED
}

func (x *StoragePricingSnapshotCacheEntryV1) GetVersionNumber() uint32 {
	if x != nil {
		return x.VersionNumber
	}
	return 0
}

func (x *StoragePricingSnapshotCacheEntryV1) GetEffectiveFromUnixMicros() int64 {
	if x != nil {
		return x.EffectiveFromUnixMicros
	}
	return 0
}

func (x *StoragePricingSnapshotCacheEntryV1) GetEffectiveToUnixMicros() int64 {
	if x != nil && x.EffectiveToUnixMicros != nil {
		return *x.EffectiveToUnixMicros
	}
	return 0
}

func (x *StoragePricingSnapshotCacheEntryV1) GetChecksumSha256() []byte {
	if x != nil {
		return x.ChecksumSha256
	}
	return nil
}

func (x *StoragePricingSnapshotCacheEntryV1) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *StoragePricingSnapshotCacheEntryV1) GetBrackets() []*StoragePricingScalarBracketV1 {
	if x != nil {
		return x.Brackets
	}
	return nil
}

type StoragePricingScalarBracketV1 struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Id                       []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // exactly 16 UUID bytes
	RangeStartQuantity       int64                  `protobuf:"varint,2,opt,name=range_start_quantity,json=rangeStartQuantity,proto3" json:"range_start_quantity,omitempty"`
	RangeEndQuantity         *int64                 `protobuf:"varint,3,opt,name=range_end_quantity,json=rangeEndQuantity,proto3,oneof" json:"range_end_quantity,omitempty"`
	PriceNumeratorMicroUnits int64                  `protobuf:"varint,4,opt,name=price_numerator_micro_units,json=priceNumeratorMicroUnits,proto3" json:"price_numerator_micro_units,omitempty"`
	PriceDenominatorQuantity int64                  `protobuf:"varint,5,opt,name=price_denominator_quantity,json=priceDenominatorQuantity,proto3" json:"price_denominator_quantity,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *StoragePricingScalarBracketV1) Reset() {
	*x = StoragePricingScalarBracketV1{}
	mi := &file_billing_pricing_storage_v1_storage_pricing_snapshot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoragePricingScalarBracketV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoragePricingScalarBracketV1) ProtoMessage() {}

func (x *StoragePricingScalarBracketV1) ProtoReflect() protoreflect.Message {
	mi := &file_billing_pricing_storage_v1_storage_pricing_snapshot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoragePricingScalarBracketV1.ProtoReflect.Descriptor instead.
func (*StoragePricingScalarBracketV1) Descriptor() ([]byte, []int) {
	return file_billing_pricing_storage_v1_storage_pricing_snapshot_proto_rawDescGZIP(), []int{1}
}

func (x *StoragePricingScalarBracketV1) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *StoragePricingScalarBracketV1) GetRangeStartQuantity() int64 {
	if x != nil {
		return x.RangeStartQuantity
	}
	return 0
}

func (x *StoragePricingScalarBracketV1) GetRangeEndQuantity() int64 {
	if x != nil && x.RangeEndQuantity != nil {
		return *x.RangeEndQuantity
	}
	return 0
}

func (x *StoragePricingScalarBracketV1) GetPriceNumeratorMicroUnits() int64 {
	if x != nil {
		return x.PriceNumeratorMicroUnits
	}
	return 0
}

func (x *StoragePricingScalarBracketV1) GetPriceDenominatorQuantity() int64 {
	if x != nil {
		return x.PriceDenominatorQuantity
	}
	return 0
}

var File_billing_pricing_storage_v1_storage_pricing_snapshot_proto protoreflect.FileDescriptor

const file_billing_pricing_storage_v1_storage_pricing_snapshot_proto_rawDesc = "" +
	"\n" +
	"9billing/pricing/storage/v1/storage_pricing_snapshot.proto\x12\x1abilling.pricing.storage.v1\"\xfc\x05\n" +
	"\"StoragePricingSnapshotCacheEntryV1\x12.\n" +
	"\x13pricing_schedule_id\x18\x01 \x01(\fR\x11pricingScheduleId\x12\x1d\n" +
	"\n" +
	"version_id\x18\x02 \x01(\fR\tversionId\x12#\n" +
	"\rschedule_code\x18\x03 \x01(\tR\fscheduleCode\x12P\n" +
	"\vcharge_kind\x18\x04 \x01(\x0e2/.billing.pricing.storage.v1.StorageChargeKindV1R\n" +
	"chargeKind\x12V\n" +
	"\rpricing_model\x18\x05 \x01(\x0e21.billing.pricing.storage.v1.StoragePricingModelV1R\fpricingModel\x12W\n" +
	"\x0eraw_input_unit\x18\x06 \x01(\x0e21.billing.pricing.storage.v1.StorageRawInputUnitV1R\frawInputUnit\x12%\n" +
	"\x0eversion_number\x18\a \x01(\rR\rversionNumber\x12;\n" +
	"\x1aeffective_from_unix_micros\x18\b \x01(\x03R\x17effectiveFromUnixMicros\x12<\n" +
	"\x18effective_to_unix_micros\x18\t \x01(\x03H\x00R\x15effectiveToUnixMicros\x88\x01\x01\x12'\n" +
	"\x0fchecksum_sha256\x18\n" +
	" \x01(\fR\x0echecksumSha256\x12\x1a\n" +
	"\bcurrency\x18\v \x01(\tR\bcurrency\x12U\n" +
	"\bbrackets\x18\f \x03(\v29.billing.pricing.storage.v1.StoragePricingScalarBracketV1R\bbracketsB\x1b\n" +
	"\x19_effective_to_unix_microsJ\x04\b\r\x10\x15\"\xae\x02\n" +
	"\x1dStoragePricingScalarBracketV1\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x120\n" +
	"\x14range_start_quantity\x18\x02 \x01(\x03R\x12rangeStartQuantity\x121\n" +
	"\x12range_end_quantity\x18\x03 \x01(\x03H\x00R\x10rangeEndQuantity\x88\x01\x01\x12=\n" +
	"\x1bprice_numerator_micro_units\x18\x04 \x01(\x03R\x18priceNumeratorMicroUnits\x12<\n" +
	"\x1aprice_denominator_quantity\x18\x05 \x01(\x03R\x18priceDenominatorQuantityB\x15\n" +
	"\x13_range_end_quantityJ\x04\b\x06\x10\v*\xc3\x01\n" +
	"\x13StorageChargeKindV1\x12&\n" +
	"\"STORAGE_CHARGE_KIND_V1_UNSPECIFIED\x10\x00\x12+\n" +
	"'STORAGE_CHARGE_KIND_V1_CAPACITY_GB_HOUR\x10\x01\x12*\n" +
	"&STORAGE_CHARGE_KIND_V1_NETWORK_IN_BYTE\x10\x02\x12+\n" +
	"'STORAGE_CHARGE_KIND_V1_NETWORK_OUT_BYTE\x10\x03*p\n" +
	"\x15StoragePricingModelV1\x12(\n" +
	"$STORAGE_PRICING_MODEL_V1_UNSPECIFIED\x10\x00\x12-\n" +
	")STORAGE_PRICING_MODEL_V1_PROGRESSIVE_UNIT\x10\x01*\x8f\x01\n" +
	"\x15StorageRawInputUnitV1\x12)\n" +
	"%STORAGE_RAW_INPUT_UNIT_V1_UNSPECIFIED\x10\x00\x12'\n" +
	"#STORAGE_RAW_INPUT_UNIT_V1_BYTE_HOUR\x10\x01\x12\"\n" +
	"\x1eSTORAGE_RAW_INPUT_UNIT_V1_BYTE\x10\x02BPZNcost-manager/api/internal/genproto/billing/pricing/storage/v1;storagepricingv1b\x06proto3"

var (
	file_billing_pricing_storage_v1_storage_pricing_snapshot_proto_rawDescOnce sync.Once
	file_billing_pricing_storage_v1_storage_pricing_snapshot_proto_rawDescData []byte
)

func file_billing_pricing_storage_v1_storage_pricing_snapshot_proto_rawDescGZIP() []byte {
	file_billing_pricing_storage_v1_storage_pricing_snapshot_proto_rawDescOnce.Do(func() {
		file_billing_pricing_storage_v1_storage_pricing_snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_billing_pricing_storage_v1_storage_pricing_snapshot_proto_rawDesc), len(file_billing_pricing_storage_v1_storage_pricing_snapshot_proto_rawDesc)))
	})
	return file_billing_pricing_storage_v1_storage_pricing_snapshot_proto_rawDescData
}

var file_billing_pricing_storage_v1_storage_pricing_snapshot_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_billing_pricing_storage_v1_storage_pricing_snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_billing_pricing_storage_v1_storage_pricing_snapshot_proto_goTypes = []any{
	(StorageChargeKindV1)(0),                   // 0: billing.pricing.storage.v1.StorageChargeKindV1
	(StoragePricingModelV1)(0),                 // 1: billing.pricing.storage.v1.StoragePricingModelV1
	(StorageRawInputUnitV1)(0),                 // 2: billing.pricing.storage.v1.StorageRawInputUnitV1
	(*StoragePricingSnapshotCacheEntryV1)(nil), // 3: billing.pricing.storage.v1.StoragePricingSnapshotCacheEntryV1
	(*StoragePricingScalarBracketV1)(nil),      // 4: billing.pricing.storage.v1.StoragePricingScalarBracketV1
}
var file_billing_pricing_storage_v1_storage_pricing_snapshot_proto_depIdxs = []int32{
	0, // 0: billing.pricing.storage.v1.StoragePricingSnapshotCacheEntryV1.charge_kind:type_name -> billing.pricing.storage.v1.StorageChargeKindV1
	1, // 1: billing.pricing.storage.v1.StoragePricingSnapshotCacheEntryV1.pricing_model:type_name -> billing.pricing.storage.v1.StoragePricingModelV1
	2, // 2: billing.pricing.storage.v1.StoragePricingSnapshotCacheEntryV1.raw_input_unit:type_name -> billing.pricing.storage.v1.StorageRawInputUnitV1
	4, // 3: billing.pricing.storage.v1.StoragePricingSnapshotCacheEntryV1.brackets:type_name -> billing.pricing.storage.v1.StoragePricingScalarBracketV1
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_billing_pricing_storage_v1_storage_pricing_snapshot_proto_init() }
func file_billing_pricing_storage_v1_storage_pricing_snapshot_proto_init() {
	if File_billing_pricing_storage_v1_storage_pricing_snapshot_proto != nil {
		return
	}
	file_billing_pricing_storage_v1_storage_pricing_snapshot_proto_msgTypes[0].OneofWrappers = []any{}
	file_billing_pricing_storage_v1_storage_pricing_snapshot_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_billing_pricing_storage_v1_storage_pricing_snapshot_proto_rawDesc), len(file_billing_pricing_storage_v1_storage_pricing_snapshot_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_billing_pricing_storage_v1_storage_pricing_snapshot_proto_goTypes,
		DependencyIndexes: file_billing_pricing_storage_v1_storage_pricing_snapshot_proto_depIdxs,
		EnumInfos:         file_billing_pricing_storage_v1_storage_pricing_snapshot_proto_enumTypes,
		MessageInfos:      file_billing_pricing_storage_v1_storage_pricing_snapshot_proto_msgTypes,
	}.Build()
	File_billing_pricing_storage_v1_storage_pricing_snapshot_proto = out.File
	file_billing_pricing_storage_v1_storage_pricing_snapshot_proto_goTypes = nil
	file_billing_pricing_storage_v1_storage_pricing_snapshot_proto_depIdxs = nil
}
