// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: internal/hierarchy/transport/proto/zone.proto

package hierarchyproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetZoneListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetZoneListRequest) Reset() {
	*x = GetZoneListRequest{}
	mi := &file_internal_hierarchy_transport_proto_zone_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetZoneListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetZoneListRequest) ProtoMessage() {}

func (x *GetZoneListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_hierarchy_transport_proto_zone_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetZoneListRequest.ProtoReflect.Descriptor instead.
func (*GetZoneListRequest) Descriptor() ([]byte, []int) {
	return file_internal_hierarchy_transport_proto_zone_proto_rawDescGZIP(), []int{0}
}

type ZoneEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneId        string                 `protobuf:"bytes,1,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	ZoneCode      string                 `protobuf:"bytes,2,opt,name=zone_code,json=zoneCode,proto3" json:"zone_code,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // Trạng thái hoạt động của zone (active, planned, draining, etc.)
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZoneEntry) Reset() {
	*x = ZoneEntry{}
	mi := &file_internal_hierarchy_transport_proto_zone_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoneEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneEntry) ProtoMessage() {}

func (x *ZoneEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_hierarchy_transport_proto_zone_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneEntry.ProtoReflect.Descriptor instead.
func (*ZoneEntry) Descriptor() ([]byte, []int) {
	return file_internal_hierarchy_transport_proto_zone_proto_rawDescGZIP(), []int{1}
}

func (x *ZoneEntry) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *ZoneEntry) GetZoneCode() string {
	if x != nil {
		return x.ZoneCode
	}
	return ""
}

func (x *ZoneEntry) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ZoneEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetZoneListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zones         []*ZoneEntry           `protobuf:"bytes,1,rep,name=zones,proto3" json:"zones,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetZoneListResponse) Reset() {
	*x = GetZoneListResponse{}
	mi := &file_internal_hierarchy_transport_proto_zone_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetZoneListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetZoneListResponse) ProtoMessage() {}

func (x *GetZoneListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_hierarchy_transport_proto_zone_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetZoneListResponse.ProtoReflect.Descriptor instead.
func (*GetZoneListResponse) Descriptor() ([]byte, []int) {
	return file_internal_hierarchy_transport_proto_zone_proto_rawDescGZIP(), []int{2}
}

func (x *GetZoneListResponse) GetZones() []*ZoneEntry {
	if x != nil {
		return x.Zones
	}
	return nil
}

type ResolveZoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneCode      string                 `protobuf:"bytes,1,opt,name=zone_code,json=zoneCode,proto3" json:"zone_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveZoneRequest) Reset() {
	*x = ResolveZoneRequest{}
	mi := &file_internal_hierarchy_transport_proto_zone_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveZoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveZoneRequest) ProtoMessage() {}

func (x *ResolveZoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_hierarchy_transport_proto_zone_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveZoneRequest.ProtoReflect.Descriptor instead.
func (*ResolveZoneRequest) Descriptor() ([]byte, []int) {
	return file_internal_hierarchy_transport_proto_zone_proto_rawDescGZIP(), []int{3}
}

func (x *ResolveZoneRequest) GetZoneCode() string {
	if x != nil {
		return x.ZoneCode
	}
	return ""
}

type ResolveZoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	ZoneId        string                 `protobuf:"bytes,2,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveZoneResponse) Reset() {
	*x = ResolveZoneResponse{}
	mi := &file_internal_hierarchy_transport_proto_zone_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveZoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveZoneResponse) ProtoMessage() {}

func (x *ResolveZoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_hierarchy_transport_proto_zone_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveZoneResponse.ProtoReflect.Descriptor instead.
func (*ResolveZoneResponse) Descriptor() ([]byte, []int) {
	return file_internal_hierarchy_transport_proto_zone_proto_rawDescGZIP(), []int{4}
}

func (x *ResolveZoneResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *ResolveZoneResponse) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *ResolveZoneResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ResolveZoneResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ZoneInvalidatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneId        string                 `protobuf:"bytes,1,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	ZoneCode      string                 `protobuf:"bytes,2,opt,name=zone_code,json=zoneCode,proto3" json:"zone_code,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Deleted       bool                   `protobuf:"varint,5,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZoneInvalidatedEvent) Reset() {
	*x = ZoneInvalidatedEvent{}
	mi := &file_internal_hierarchy_transport_proto_zone_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoneInvalidatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneInvalidatedEvent) ProtoMessage() {}

func (x *ZoneInvalidatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_hierarchy_transport_proto_zone_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneInvalidatedEvent.ProtoReflect.Descriptor instead.
func (*ZoneInvalidatedEvent) Descriptor() ([]byte, []int) {
	return file_internal_hierarchy_transport_proto_zone_proto_rawDescGZIP(), []int{5}
}

func (x *ZoneInvalidatedEvent) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *ZoneInvalidatedEvent) GetZoneCode() string {
	if x != nil {
		return x.ZoneCode
	}
	return ""
}

func (x *ZoneInvalidatedEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ZoneInvalidatedEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ZoneInvalidatedEvent) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

var File_internal_hierarchy_transport_proto_zone_proto protoreflect.FileDescriptor

const file_internal_hierarchy_transport_proto_zone_proto_rawDesc = "" +
	"\n" +
	"-internal/hierarchy/transport/proto/zone.proto\x12\rhierarchy.rpc\"\x14\n" +
	"\x12GetZoneListRequest\"m\n" +
	"\tZoneEntry\x12\x17\n" +
	"\azone_id\x18\x01 \x01(\tR\x06zoneId\x12\x1b\n" +
	"\tzone_code\x18\x02 \x01(\tR\bzoneCode\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"E\n" +
	"\x13GetZoneListResponse\x12.\n" +
	"\x05zones\x18\x01 \x03(\v2\x18.hierarchy.rpc.ZoneEntryR\x05zones\"1\n" +
	"\x12ResolveZoneRequest\x12\x1b\n" +
	"\tzone_code\x18\x01 \x01(\tR\bzoneCode\"p\n" +
	"\x13ResolveZoneResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x17\n" +
	"\azone_id\x18\x02 \x01(\tR\x06zoneId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"\x92\x01\n" +
	"\x14ZoneInvalidatedEvent\x12\x17\n" +
	"\azone_id\x18\x01 \x01(\tR\x06zoneId\x12\x1b\n" +
	"\tzone_code\x18\x02 \x01(\tR\bzoneCode\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x18\n" +
	"\adeleted\x18\x05 \x01(\bR\adeleted2\xb9\x01\n" +
	"\vZoneService\x12T\n" +
	"\vGetZoneList\x12!.hierarchy.rpc.GetZoneListRequest\x1a\".hierarchy.rpc.GetZoneListResponse\x12T\n" +
	"\vResolveZone\x12!.hierarchy.rpc.ResolveZoneRequest\x1a\".hierarchy.rpc.ResolveZoneResponseB@Z>controlplane/internal/hierarchy/transport/proto;hierarchyprotob\x06proto3"

var (
	file_internal_hierarchy_transport_proto_zone_proto_rawDescOnce sync.Once
	file_internal_hierarchy_transport_proto_zone_proto_rawDescData []byte
)

func file_internal_hierarchy_transport_proto_zone_proto_rawDescGZIP() []byte {
	file_internal_hierarchy_transport_proto_zone_proto_rawDescOnce.Do(func() {
		file_internal_hierarchy_transport_proto_zone_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_hierarchy_transport_proto_zone_proto_rawDesc), len(file_internal_hierarchy_transport_proto_zone_proto_rawDesc)))
	})
	return file_internal_hierarchy_transport_proto_zone_proto_rawDescData
}

var file_internal_hierarchy_transport_proto_zone_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_hierarchy_transport_proto_zone_proto_goTypes = []any{
	(*GetZoneListRequest)(nil),   // 0: hierarchy.rpc.GetZoneListRequest
	(*ZoneEntry)(nil),            // 1: hierarchy.rpc.ZoneEntry
	(*GetZoneListResponse)(nil),  // 2: hierarchy.rpc.GetZoneListResponse
	(*ResolveZoneRequest)(nil),   // 3: hierarchy.rpc.ResolveZoneRequest
	(*ResolveZoneResponse)(nil),  // 4: hierarchy.rpc.ResolveZoneResponse
	(*ZoneInvalidatedEvent)(nil), // 5: hierarchy.rpc.ZoneInvalidatedEvent
}
var file_internal_hierarchy_transport_proto_zone_proto_depIdxs = []int32{
	1, // 0: hierarchy.rpc.GetZoneListResponse.zones:type_name -> hierarchy.rpc.ZoneEntry
	0, // 1: hierarchy.rpc.ZoneService.GetZoneList:input_type -> hierarchy.rpc.GetZoneListRequest
	3, // 2: hierarchy.rpc.ZoneService.ResolveZone:input_type -> hierarchy.rpc.ResolveZoneRequest
	2, // 3: hierarchy.rpc.ZoneService.GetZoneList:output_type -> hierarchy.rpc.GetZoneListResponse
	4, // 4: hierarchy.rpc.ZoneService.ResolveZone:output_type -> hierarchy.rpc.ResolveZoneResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_hierarchy_transport_proto_zone_proto_init() }
func file_internal_hierarchy_transport_proto_zone_proto_init() {
	if File_internal_hierarchy_transport_proto_zone_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_hierarchy_transport_proto_zone_proto_rawDesc), len(file_internal_hierarchy_transport_proto_zone_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_hierarchy_transport_proto_zone_proto_goTypes,
		DependencyIndexes: file_internal_hierarchy_transport_proto_zone_proto_depIdxs,
		MessageInfos:      file_internal_hierarchy_transport_proto_zone_proto_msgTypes,
	}.Build()
	File_internal_hierarchy_transport_proto_zone_proto = out.File
	file_internal_hierarchy_transport_proto_zone_proto_goTypes = nil
	file_internal_hierarchy_transport_proto_zone_proto_depIdxs = nil
}
