-- Migration: Add advanced bucket configuration options
-- Thêm các cột cho Encryption, Versioning, Object Locking, Replication, Tags, Retention, Legal Hold

ALTER TABLE personal_buckets
ADD COLUMN IF NOT EXISTS encrypt_enabled BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS versioning_enabled BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS object_locking_enabled BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS replication_enabled BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS retention_days INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS legal_hold_enabled BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS tags JSONB NOT NULL DEFAULT '{}';

ALTER TABLE tenant_buckets
ADD COLUMN IF NOT EXISTS encrypt_enabled BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS versioning_enabled BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS object_locking_enabled BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS replication_enabled BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS retention_days INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS legal_hold_enabled BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS tags JSONB NOT NULL DEFAULT '{}';
