// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: auth.proto

package iamproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request xác thực Opaque Refresh Token
type VerifyOpaqueRefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	TenantId      *string                `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3,oneof" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyOpaqueRefreshTokenRequest) Reset() {
	*x = VerifyOpaqueRefreshTokenRequest{}
	mi := &file_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyOpaqueRefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyOpaqueRefreshTokenRequest) ProtoMessage() {}

func (x *VerifyOpaqueRefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyOpaqueRefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*VerifyOpaqueRefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyOpaqueRefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *VerifyOpaqueRefreshTokenRequest) GetTenantId() string {
	if x != nil && x.TenantId != nil {
		return *x.TenantId
	}
	return ""
}

func (x *VerifyOpaqueRefreshTokenRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Response trả về khi xác thực Opaque Refresh Token
type VerifyOpaqueRefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	Level         int32                  `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Username      string                 `protobuf:"bytes,7,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyOpaqueRefreshTokenResponse) Reset() {
	*x = VerifyOpaqueRefreshTokenResponse{}
	mi := &file_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyOpaqueRefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyOpaqueRefreshTokenResponse) ProtoMessage() {}

func (x *VerifyOpaqueRefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyOpaqueRefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*VerifyOpaqueRefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyOpaqueRefreshTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyOpaqueRefreshTokenResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VerifyOpaqueRefreshTokenResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *VerifyOpaqueRefreshTokenResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *VerifyOpaqueRefreshTokenResponse) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *VerifyOpaqueRefreshTokenResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *VerifyOpaqueRefreshTokenResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// [COMMENT]: Request chứa raw refresh token từ client cookie để CP hash & revoke
type RevokeOpaqueRefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeOpaqueRefreshTokenRequest) Reset() {
	*x = RevokeOpaqueRefreshTokenRequest{}
	mi := &file_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeOpaqueRefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeOpaqueRefreshTokenRequest) ProtoMessage() {}

func (x *RevokeOpaqueRefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeOpaqueRefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RevokeOpaqueRefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{2}
}

func (x *RevokeOpaqueRefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

// [COMMENT]: Response rỗng phục vụ tín hiệu hoàn tất cho rpc call
type RevokeOpaqueRefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeOpaqueRefreshTokenResponse) Reset() {
	*x = RevokeOpaqueRefreshTokenResponse{}
	mi := &file_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeOpaqueRefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeOpaqueRefreshTokenResponse) ProtoMessage() {}

func (x *RevokeOpaqueRefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeOpaqueRefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RevokeOpaqueRefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{3}
}

// [COMMENT]: Request xác thực thông tin đăng nhập thô từ client gửi lên gateway
type VerifyUserCredentialsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Username       string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`                                     // Tên đăng nhập hoặc Email của người dùng
	Password       string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`                                     // Mật khẩu dạng plain-text cần xác thực
	ClientDeviceId string                 `protobuf:"bytes,3,opt,name=client_device_id,json=clientDeviceId,proto3" json:"client_device_id,omitempty"` // UUID định danh thiết bị gửi lên từ cookie (nếu có)
	DeviceName     string                 `protobuf:"bytes,4,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`               // Tên hiển thị của thiết bị (ví dụ: Chrome on Windows)
	DeviceType     string                 `protobuf:"bytes,5,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`               // OS/Platform và phiên bản của thiết bị (ví dụ: "Windows 11", "macOS 14", "iOS 17")
	PublicKey      string                 `protobuf:"bytes,6,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`                  // Khóa Ed25519 public key dạng base64 phục vụ xác thực chữ ký/thiết bị tin cậy
	Signature      string                 `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`                                   // Chữ ký bảo mật (signature) nếu có
	TrustDevice    bool                   `protobuf:"varint,8,opt,name=trust_device,json=trustDevice,proto3" json:"trust_device,omitempty"`           // Cờ xác định có cấp refresh token hay không (trusted device)
	ClientIp       string                 `protobuf:"bytes,9,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`                     // Địa chỉ IP của Client (trích xuất từ X-Forwarded-For hoặc Envoy context)
	UserAgent      string                 `protobuf:"bytes,10,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`                 // Chuỗi User-Agent của client phục vụ tracking
	// [COMMENT]: Nếu username có định dạng user@tenant_domain, ACR sẽ tách và điền field này.
	// Rỗng = đăng nhập global, có giá trị = đăng nhập vào tenant context.
	TenantDomain  string `protobuf:"bytes,11,opt,name=tenant_domain,json=tenantDomain,proto3" json:"tenant_domain,omitempty"` // Domain của Tenant (ví dụ: acme.io) — để CP JOIN tenant_domains + tenant_memberships
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyUserCredentialsRequest) Reset() {
	*x = VerifyUserCredentialsRequest{}
	mi := &file_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyUserCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyUserCredentialsRequest) ProtoMessage() {}

func (x *VerifyUserCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyUserCredentialsRequest.ProtoReflect.Descriptor instead.
func (*VerifyUserCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{4}
}

func (x *VerifyUserCredentialsRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *VerifyUserCredentialsRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *VerifyUserCredentialsRequest) GetClientDeviceId() string {
	if x != nil {
		return x.ClientDeviceId
	}
	return ""
}

func (x *VerifyUserCredentialsRequest) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *VerifyUserCredentialsRequest) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *VerifyUserCredentialsRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *VerifyUserCredentialsRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *VerifyUserCredentialsRequest) GetTrustDevice() bool {
	if x != nil {
		return x.TrustDevice
	}
	return false
}

func (x *VerifyUserCredentialsRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *VerifyUserCredentialsRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *VerifyUserCredentialsRequest) GetTenantDomain() string {
	if x != nil {
		return x.TenantDomain
	}
	return ""
}

// [COMMENT]: Response trả về trạng thái xác thực và các thông tin định danh/claim
type VerifyUserCredentialsResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Valid                 bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`                                                                   // Cờ báo hiệu xác thực thông tin thành công hay thất bại
	UserId                string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                                    // UUID của người dùng dưới dạng chuỗi
	RoleId                string                 `protobuf:"bytes,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`                                                    // UUID của Role đang hoạt động của người dùng (dưới dạng chuỗi)
	Level                 int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`                                                                   // Cấp độ quyền (level)
	TenantId              string                 `protobuf:"bytes,5,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                                              // ID/Context của Tenant liên đới (nếu có)
	ClientDeviceId        string                 `protobuf:"bytes,6,opt,name=client_device_id,json=clientDeviceId,proto3" json:"client_device_id,omitempty"`                          // UUID thiết bị được ghi nhận/sinh mới sau khi gắn kết thành công
	RefreshToken          string                 `protobuf:"bytes,7,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`                                  // Opaque Refresh Token được sinh bởi CP để ACR ghi nhận cookie (nếu trust_device=true)
	ErrorMessage          string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`                                  // Mô tả lỗi chi tiết nếu valid = false
	Username              string                 `protobuf:"bytes,9,opt,name=username,proto3" json:"username,omitempty"`                                                              // Tên đăng nhập của người dùng
	ClientProofPublicKey  string                 `protobuf:"bytes,10,opt,name=client_proof_public_key,json=clientProofPublicKey,proto3" json:"client_proof_public_key,omitempty"`     // Canonical Ed25519 public key đã được IAM persist/resolve
	RefreshTokenExpiresAt int64                  `protobuf:"varint,11,opt,name=refresh_token_expires_at,json=refreshTokenExpiresAt,proto3" json:"refresh_token_expires_at,omitempty"` // Unix seconds của expiry đã persist; ACR dùng làm Max-Age cookie
	MfaRequired           bool                   `protobuf:"varint,12,opt,name=mfa_required,json=mfaRequired,proto3" json:"mfa_required,omitempty"`                                   // Primary credential đúng nhưng cần hoàn tất MFA trước khi issue session
	MfaSettingId          string                 `protobuf:"bytes,13,opt,name=mfa_setting_id,json=mfaSettingId,proto3" json:"mfa_setting_id,omitempty"`                               // Enrollment fence bound into the short-lived MFA challenge
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *VerifyUserCredentialsResponse) Reset() {
	*x = VerifyUserCredentialsResponse{}
	mi := &file_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyUserCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyUserCredentialsResponse) ProtoMessage() {}

func (x *VerifyUserCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyUserCredentialsResponse.ProtoReflect.Descriptor instead.
func (*VerifyUserCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{5}
}

func (x *VerifyUserCredentialsResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyUserCredentialsResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VerifyUserCredentialsResponse) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *VerifyUserCredentialsResponse) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *VerifyUserCredentialsResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *VerifyUserCredentialsResponse) GetClientDeviceId() string {
	if x != nil {
		return x.ClientDeviceId
	}
	return ""
}

func (x *VerifyUserCredentialsResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *VerifyUserCredentialsResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *VerifyUserCredentialsResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *VerifyUserCredentialsResponse) GetClientProofPublicKey() string {
	if x != nil {
		return x.ClientProofPublicKey
	}
	return ""
}

func (x *VerifyUserCredentialsResponse) GetRefreshTokenExpiresAt() int64 {
	if x != nil {
		return x.RefreshTokenExpiresAt
	}
	return 0
}

func (x *VerifyUserCredentialsResponse) GetMfaRequired() bool {
	if x != nil {
		return x.MfaRequired
	}
	return false
}

func (x *VerifyUserCredentialsResponse) GetMfaSettingId() string {
	if x != nil {
		return x.MfaSettingId
	}
	return ""
}

// [COMMENT]: Identity OAuth/OIDC đã được ACR parse, verify chữ ký/claims và canonicalize.
// Controlplane không nhận raw provider JSON, authorization code hoặc provider token.
type VerifyExternalIdentityRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OperationId     string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	SchemaVersion   uint32                 `protobuf:"varint,2,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Provider        string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	ProviderSubject string                 `protobuf:"bytes,4,opt,name=provider_subject,json=providerSubject,proto3" json:"provider_subject,omitempty"`
	ProviderEmail   string                 `protobuf:"bytes,5,opt,name=provider_email,json=providerEmail,proto3" json:"provider_email,omitempty"`
	EmailVerifiedAt int64                  `protobuf:"varint,6,opt,name=email_verified_at,json=emailVerifiedAt,proto3" json:"email_verified_at,omitempty"`
	DisplayName     string                 `protobuf:"bytes,7,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AvatarUrl       string                 `protobuf:"bytes,8,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	ClientDeviceId  string                 `protobuf:"bytes,9,opt,name=client_device_id,json=clientDeviceId,proto3" json:"client_device_id,omitempty"`
	DeviceName      string                 `protobuf:"bytes,10,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	DeviceType      string                 `protobuf:"bytes,11,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	PublicKey       string                 `protobuf:"bytes,12,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	TrustDevice     bool                   `protobuf:"varint,13,opt,name=trust_device,json=trustDevice,proto3" json:"trust_device,omitempty"`
	ZoneCode        string                 `protobuf:"bytes,14,opt,name=zone_code,json=zoneCode,proto3" json:"zone_code,omitempty"`
	ClientIp        string                 `protobuf:"bytes,15,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	UserAgent       string                 `protobuf:"bytes,16,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VerifyExternalIdentityRequest) Reset() {
	*x = VerifyExternalIdentityRequest{}
	mi := &file_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyExternalIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyExternalIdentityRequest) ProtoMessage() {}

func (x *VerifyExternalIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyExternalIdentityRequest.ProtoReflect.Descriptor instead.
func (*VerifyExternalIdentityRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{6}
}

func (x *VerifyExternalIdentityRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *VerifyExternalIdentityRequest) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *VerifyExternalIdentityRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *VerifyExternalIdentityRequest) GetProviderSubject() string {
	if x != nil {
		return x.ProviderSubject
	}
	return ""
}

func (x *VerifyExternalIdentityRequest) GetProviderEmail() string {
	if x != nil {
		return x.ProviderEmail
	}
	return ""
}

func (x *VerifyExternalIdentityRequest) GetEmailVerifiedAt() int64 {
	if x != nil {
		return x.EmailVerifiedAt
	}
	return 0
}

func (x *VerifyExternalIdentityRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *VerifyExternalIdentityRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *VerifyExternalIdentityRequest) GetClientDeviceId() string {
	if x != nil {
		return x.ClientDeviceId
	}
	return ""
}

func (x *VerifyExternalIdentityRequest) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *VerifyExternalIdentityRequest) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *VerifyExternalIdentityRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *VerifyExternalIdentityRequest) GetTrustDevice() bool {
	if x != nil {
		return x.TrustDevice
	}
	return false
}

func (x *VerifyExternalIdentityRequest) GetZoneCode() string {
	if x != nil {
		return x.ZoneCode
	}
	return ""
}

func (x *VerifyExternalIdentityRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *VerifyExternalIdentityRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

type VerifyExternalIdentityResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Valid                 bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	UserId                string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleId                string                 `protobuf:"bytes,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	Level                 int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	TenantId              string                 `protobuf:"bytes,5,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ClientDeviceId        string                 `protobuf:"bytes,6,opt,name=client_device_id,json=clientDeviceId,proto3" json:"client_device_id,omitempty"`
	RefreshToken          string                 `protobuf:"bytes,7,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ErrorMessage          string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Username              string                 `protobuf:"bytes,9,opt,name=username,proto3" json:"username,omitempty"`
	ClientProofPublicKey  string                 `protobuf:"bytes,10,opt,name=client_proof_public_key,json=clientProofPublicKey,proto3" json:"client_proof_public_key,omitempty"`
	RefreshTokenExpiresAt int64                  `protobuf:"varint,11,opt,name=refresh_token_expires_at,json=refreshTokenExpiresAt,proto3" json:"refresh_token_expires_at,omitempty"`
	ZoneCode              string                 `protobuf:"bytes,12,opt,name=zone_code,json=zoneCode,proto3" json:"zone_code,omitempty"`
	MfaRequired           bool                   `protobuf:"varint,15,opt,name=mfa_required,json=mfaRequired,proto3" json:"mfa_required,omitempty"`
	MfaSettingId          string                 `protobuf:"bytes,16,opt,name=mfa_setting_id,json=mfaSettingId,proto3" json:"mfa_setting_id,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *VerifyExternalIdentityResponse) Reset() {
	*x = VerifyExternalIdentityResponse{}
	mi := &file_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyExternalIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyExternalIdentityResponse) ProtoMessage() {}

func (x *VerifyExternalIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyExternalIdentityResponse.ProtoReflect.Descriptor instead.
func (*VerifyExternalIdentityResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{7}
}

func (x *VerifyExternalIdentityResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyExternalIdentityResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VerifyExternalIdentityResponse) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *VerifyExternalIdentityResponse) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *VerifyExternalIdentityResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *VerifyExternalIdentityResponse) GetClientDeviceId() string {
	if x != nil {
		return x.ClientDeviceId
	}
	return ""
}

func (x *VerifyExternalIdentityResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *VerifyExternalIdentityResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *VerifyExternalIdentityResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *VerifyExternalIdentityResponse) GetClientProofPublicKey() string {
	if x != nil {
		return x.ClientProofPublicKey
	}
	return ""
}

func (x *VerifyExternalIdentityResponse) GetRefreshTokenExpiresAt() int64 {
	if x != nil {
		return x.RefreshTokenExpiresAt
	}
	return 0
}

func (x *VerifyExternalIdentityResponse) GetZoneCode() string {
	if x != nil {
		return x.ZoneCode
	}
	return ""
}

func (x *VerifyExternalIdentityResponse) GetMfaRequired() bool {
	if x != nil {
		return x.MfaRequired
	}
	return false
}

func (x *VerifyExternalIdentityResponse) GetMfaSettingId() string {
	if x != nil {
		return x.MfaSettingId
	}
	return ""
}

// Canonical provider identity accepted only after ACR completed a critical
// session-proof start and verified the provider callback.
type LinkExternalIdentityRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OperationId     string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	SchemaVersion   uint32                 `protobuf:"varint,2,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	UserId          string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Provider        string                 `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	ProviderSubject string                 `protobuf:"bytes,5,opt,name=provider_subject,json=providerSubject,proto3" json:"provider_subject,omitempty"`
	ProviderEmail   string                 `protobuf:"bytes,6,opt,name=provider_email,json=providerEmail,proto3" json:"provider_email,omitempty"`
	EmailVerifiedAt int64                  `protobuf:"varint,7,opt,name=email_verified_at,json=emailVerifiedAt,proto3" json:"email_verified_at,omitempty"`
	DisplayName     string                 `protobuf:"bytes,8,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AvatarUrl       string                 `protobuf:"bytes,9,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LinkExternalIdentityRequest) Reset() {
	*x = LinkExternalIdentityRequest{}
	mi := &file_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkExternalIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkExternalIdentityRequest) ProtoMessage() {}

func (x *LinkExternalIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkExternalIdentityRequest.ProtoReflect.Descriptor instead.
func (*LinkExternalIdentityRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{8}
}

func (x *LinkExternalIdentityRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *LinkExternalIdentityRequest) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *LinkExternalIdentityRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LinkExternalIdentityRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *LinkExternalIdentityRequest) GetProviderSubject() string {
	if x != nil {
		return x.ProviderSubject
	}
	return ""
}

func (x *LinkExternalIdentityRequest) GetProviderEmail() string {
	if x != nil {
		return x.ProviderEmail
	}
	return ""
}

func (x *LinkExternalIdentityRequest) GetEmailVerifiedAt() int64 {
	if x != nil {
		return x.EmailVerifiedAt
	}
	return 0
}

func (x *LinkExternalIdentityRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *LinkExternalIdentityRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type LinkExternalIdentityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Linked        bool                   `protobuf:"varint,1,opt,name=linked,proto3" json:"linked,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkExternalIdentityResponse) Reset() {
	*x = LinkExternalIdentityResponse{}
	mi := &file_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkExternalIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkExternalIdentityResponse) ProtoMessage() {}

func (x *LinkExternalIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkExternalIdentityResponse.ProtoReflect.Descriptor instead.
func (*LinkExternalIdentityResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{9}
}

func (x *LinkExternalIdentityResponse) GetLinked() bool {
	if x != nil {
		return x.Linked
	}
	return false
}

func (x *LinkExternalIdentityResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type VerifyMfaChallengeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OperationId    string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username       string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	TenantDomain   string                 `protobuf:"bytes,4,opt,name=tenant_domain,json=tenantDomain,proto3" json:"tenant_domain,omitempty"`
	Method         string                 `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`
	Code           string                 `protobuf:"bytes,6,opt,name=code,proto3" json:"code,omitempty"`
	ClientDeviceId string                 `protobuf:"bytes,7,opt,name=client_device_id,json=clientDeviceId,proto3" json:"client_device_id,omitempty"`
	DeviceName     string                 `protobuf:"bytes,8,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	DeviceType     string                 `protobuf:"bytes,9,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	PublicKey      string                 `protobuf:"bytes,10,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	TrustDevice    bool                   `protobuf:"varint,11,opt,name=trust_device,json=trustDevice,proto3" json:"trust_device,omitempty"`
	ClientIp       string                 `protobuf:"bytes,12,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	UserAgent      string                 `protobuf:"bytes,13,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	MfaSettingId   string                 `protobuf:"bytes,14,opt,name=mfa_setting_id,json=mfaSettingId,proto3" json:"mfa_setting_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VerifyMfaChallengeRequest) Reset() {
	*x = VerifyMfaChallengeRequest{}
	mi := &file_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyMfaChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyMfaChallengeRequest) ProtoMessage() {}

func (x *VerifyMfaChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyMfaChallengeRequest.ProtoReflect.Descriptor instead.
func (*VerifyMfaChallengeRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{10}
}

func (x *VerifyMfaChallengeRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *VerifyMfaChallengeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VerifyMfaChallengeRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *VerifyMfaChallengeRequest) GetTenantDomain() string {
	if x != nil {
		return x.TenantDomain
	}
	return ""
}

func (x *VerifyMfaChallengeRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *VerifyMfaChallengeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *VerifyMfaChallengeRequest) GetClientDeviceId() string {
	if x != nil {
		return x.ClientDeviceId
	}
	return ""
}

func (x *VerifyMfaChallengeRequest) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *VerifyMfaChallengeRequest) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *VerifyMfaChallengeRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *VerifyMfaChallengeRequest) GetTrustDevice() bool {
	if x != nil {
		return x.TrustDevice
	}
	return false
}

func (x *VerifyMfaChallengeRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *VerifyMfaChallengeRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *VerifyMfaChallengeRequest) GetMfaSettingId() string {
	if x != nil {
		return x.MfaSettingId
	}
	return ""
}

type VerifyMfaChallengeResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Valid                 bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	UserId                string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleId                string                 `protobuf:"bytes,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	Level                 int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	TenantId              string                 `protobuf:"bytes,5,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ClientDeviceId        string                 `protobuf:"bytes,6,opt,name=client_device_id,json=clientDeviceId,proto3" json:"client_device_id,omitempty"`
	RefreshToken          string                 `protobuf:"bytes,7,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ErrorMessage          string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Username              string                 `protobuf:"bytes,9,opt,name=username,proto3" json:"username,omitempty"`
	ClientProofPublicKey  string                 `protobuf:"bytes,10,opt,name=client_proof_public_key,json=clientProofPublicKey,proto3" json:"client_proof_public_key,omitempty"`
	RefreshTokenExpiresAt int64                  `protobuf:"varint,11,opt,name=refresh_token_expires_at,json=refreshTokenExpiresAt,proto3" json:"refresh_token_expires_at,omitempty"`
	TenantCode            string                 `protobuf:"bytes,12,opt,name=tenant_code,json=tenantCode,proto3" json:"tenant_code,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *VerifyMfaChallengeResponse) Reset() {
	*x = VerifyMfaChallengeResponse{}
	mi := &file_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyMfaChallengeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyMfaChallengeResponse) ProtoMessage() {}

func (x *VerifyMfaChallengeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyMfaChallengeResponse.ProtoReflect.Descriptor instead.
func (*VerifyMfaChallengeResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{11}
}

func (x *VerifyMfaChallengeResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyMfaChallengeResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VerifyMfaChallengeResponse) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *VerifyMfaChallengeResponse) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *VerifyMfaChallengeResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *VerifyMfaChallengeResponse) GetClientDeviceId() string {
	if x != nil {
		return x.ClientDeviceId
	}
	return ""
}

func (x *VerifyMfaChallengeResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *VerifyMfaChallengeResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *VerifyMfaChallengeResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *VerifyMfaChallengeResponse) GetClientProofPublicKey() string {
	if x != nil {
		return x.ClientProofPublicKey
	}
	return ""
}

func (x *VerifyMfaChallengeResponse) GetRefreshTokenExpiresAt() int64 {
	if x != nil {
		return x.RefreshTokenExpiresAt
	}
	return 0
}

func (x *VerifyMfaChallengeResponse) GetTenantCode() string {
	if x != nil {
		return x.TenantCode
	}
	return ""
}

// [COMMENT]: Thông tin danh sách quyền hạn của một Role để lưu cache L1/L2
type RoleEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   []string               `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleEntry) Reset() {
	*x = RoleEntry{}
	mi := &file_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleEntry) ProtoMessage() {}

func (x *RoleEntry) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleEntry.ProtoReflect.Descriptor instead.
func (*RoleEntry) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{12}
}

func (x *RoleEntry) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

// Pending self-user MFA enrollment stored in Auth-State Redis.
// This is an internal short-lived record; it is not a public HTTP payload.
type MfaSetupPending struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SetupId          string                 `protobuf:"bytes,1,opt,name=setup_id,json=setupId,proto3" json:"setup_id,omitempty"`
	UserId           string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SettingId        string                 `protobuf:"bytes,3,opt,name=setting_id,json=settingId,proto3" json:"setting_id,omitempty"`
	SecretCiphertext string                 `protobuf:"bytes,4,opt,name=secret_ciphertext,json=secretCiphertext,proto3" json:"secret_ciphertext,omitempty"`
	SecretKeyId      string                 `protobuf:"bytes,5,opt,name=secret_key_id,json=secretKeyId,proto3" json:"secret_key_id,omitempty"`
	SchemaVersion    uint32                 `protobuf:"varint,6,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MfaSetupPending) Reset() {
	*x = MfaSetupPending{}
	mi := &file_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MfaSetupPending) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MfaSetupPending) ProtoMessage() {}

func (x *MfaSetupPending) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MfaSetupPending.ProtoReflect.Descriptor instead.
func (*MfaSetupPending) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{13}
}

func (x *MfaSetupPending) GetSetupId() string {
	if x != nil {
		return x.SetupId
	}
	return ""
}

func (x *MfaSetupPending) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MfaSetupPending) GetSettingId() string {
	if x != nil {
		return x.SettingId
	}
	return ""
}

func (x *MfaSetupPending) GetSecretCiphertext() string {
	if x != nil {
		return x.SecretCiphertext
	}
	return ""
}

func (x *MfaSetupPending) GetSecretKeyId() string {
	if x != nil {
		return x.SecretKeyId
	}
	return ""
}

func (x *MfaSetupPending) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

var File_auth_proto protoreflect.FileDescriptor

const file_auth_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"auth.proto\x12\aiam.rpc\"\x8f\x01\n" +
	"\x1fVerifyOpaqueRefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\x12 \n" +
	"\ttenant_id\x18\x02 \x01(\tH\x00R\btenantId\x88\x01\x01\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userIdB\f\n" +
	"\n" +
	"_tenant_id\"\xd9\x01\n" +
	" VerifyOpaqueRefreshTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x14\n" +
	"\x05level\x18\x05 \x01(\x05R\x05level\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x12\x1a\n" +
	"\busername\x18\a \x01(\tR\busername\"F\n" +
	"\x1fRevokeOpaqueRefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"\"\n" +
	" RevokeOpaqueRefreshTokenResponse\"\x83\x03\n" +
	"\x1cVerifyUserCredentialsRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12(\n" +
	"\x10client_device_id\x18\x03 \x01(\tR\x0eclientDeviceId\x12\x1f\n" +
	"\vdevice_name\x18\x04 \x01(\tR\n" +
	"deviceName\x12\x1f\n" +
	"\vdevice_type\x18\x05 \x01(\tR\n" +
	"deviceType\x12\x1d\n" +
	"\n" +
	"public_key\x18\x06 \x01(\tR\tpublicKey\x12\x1c\n" +
	"\tsignature\x18\a \x01(\tR\tsignature\x12!\n" +
	"\ftrust_device\x18\b \x01(\bR\vtrustDevice\x12\x1b\n" +
	"\tclient_ip\x18\t \x01(\tR\bclientIp\x12\x1d\n" +
	"\n" +
	"user_agent\x18\n" +
	" \x01(\tR\tuserAgent\x12#\n" +
	"\rtenant_domain\x18\v \x01(\tR\ftenantDomain\"\xe3\x03\n" +
	"\x1dVerifyUserCredentialsResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\arole_id\x18\x03 \x01(\tR\x06roleId\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\x1b\n" +
	"\ttenant_id\x18\x05 \x01(\tR\btenantId\x12(\n" +
	"\x10client_device_id\x18\x06 \x01(\tR\x0eclientDeviceId\x12#\n" +
	"\rrefresh_token\x18\a \x01(\tR\frefreshToken\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\x12\x1a\n" +
	"\busername\x18\t \x01(\tR\busername\x125\n" +
	"\x17client_proof_public_key\x18\n" +
	" \x01(\tR\x14clientProofPublicKey\x127\n" +
	"\x18refresh_token_expires_at\x18\v \x01(\x03R\x15refreshTokenExpiresAt\x12!\n" +
	"\fmfa_required\x18\f \x01(\bR\vmfaRequired\x12$\n" +
	"\x0emfa_setting_id\x18\r \x01(\tR\fmfaSettingId\"\xcc\x04\n" +
	"\x1dVerifyExternalIdentityRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12%\n" +
	"\x0eschema_version\x18\x02 \x01(\rR\rschemaVersion\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12)\n" +
	"\x10provider_subject\x18\x04 \x01(\tR\x0fproviderSubject\x12%\n" +
	"\x0eprovider_email\x18\x05 \x01(\tR\rproviderEmail\x12*\n" +
	"\x11email_verified_at\x18\x06 \x01(\x03R\x0femailVerifiedAt\x12!\n" +
	"\fdisplay_name\x18\a \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\b \x01(\tR\tavatarUrl\x12(\n" +
	"\x10client_device_id\x18\t \x01(\tR\x0eclientDeviceId\x12\x1f\n" +
	"\vdevice_name\x18\n" +
	" \x01(\tR\n" +
	"deviceName\x12\x1f\n" +
	"\vdevice_type\x18\v \x01(\tR\n" +
	"deviceType\x12\x1d\n" +
	"\n" +
	"public_key\x18\f \x01(\tR\tpublicKey\x12!\n" +
	"\ftrust_device\x18\r \x01(\bR\vtrustDevice\x12\x1b\n" +
	"\tzone_code\x18\x0e \x01(\tR\bzoneCode\x12\x1b\n" +
	"\tclient_ip\x18\x0f \x01(\tR\bclientIp\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x10 \x01(\tR\tuserAgent\"\xb6\x04\n" +
	"\x1eVerifyExternalIdentityResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\arole_id\x18\x03 \x01(\tR\x06roleId\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\x1b\n" +
	"\ttenant_id\x18\x05 \x01(\tR\btenantId\x12(\n" +
	"\x10client_device_id\x18\x06 \x01(\tR\x0eclientDeviceId\x12#\n" +
	"\rrefresh_token\x18\a \x01(\tR\frefreshToken\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\x12\x1a\n" +
	"\busername\x18\t \x01(\tR\busername\x125\n" +
	"\x17client_proof_public_key\x18\n" +
	" \x01(\tR\x14clientProofPublicKey\x127\n" +
	"\x18refresh_token_expires_at\x18\v \x01(\x03R\x15refreshTokenExpiresAt\x12\x1b\n" +
	"\tzone_code\x18\f \x01(\tR\bzoneCode\x12!\n" +
	"\fmfa_required\x18\x0f \x01(\bR\vmfaRequired\x12$\n" +
	"\x0emfa_setting_id\x18\x10 \x01(\tR\fmfaSettingIdJ\x04\b\r\x10\x0eJ\x04\b\x0e\x10\x0fR\x10onboarding_tokenR\x15onboarding_expires_at\"\xdc\x02\n" +
	"\x1bLinkExternalIdentityRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12%\n" +
	"\x0eschema_version\x18\x02 \x01(\rR\rschemaVersion\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bprovider\x12)\n" +
	"\x10provider_subject\x18\x05 \x01(\tR\x0fproviderSubject\x12%\n" +
	"\x0eprovider_email\x18\x06 \x01(\tR\rproviderEmail\x12*\n" +
	"\x11email_verified_at\x18\a \x01(\x03R\x0femailVerifiedAt\x12!\n" +
	"\fdisplay_name\x18\b \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\t \x01(\tR\tavatarUrl\"[\n" +
	"\x1cLinkExternalIdentityResponse\x12\x16\n" +
	"\x06linked\x18\x01 \x01(\bR\x06linked\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\xd4\x03\n" +
	"\x19VerifyMfaChallengeRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12#\n" +
	"\rtenant_domain\x18\x04 \x01(\tR\ftenantDomain\x12\x16\n" +
	"\x06method\x18\x05 \x01(\tR\x06method\x12\x12\n" +
	"\x04code\x18\x06 \x01(\tR\x04code\x12(\n" +
	"\x10client_device_id\x18\a \x01(\tR\x0eclientDeviceId\x12\x1f\n" +
	"\vdevice_name\x18\b \x01(\tR\n" +
	"deviceName\x12\x1f\n" +
	"\vdevice_type\x18\t \x01(\tR\n" +
	"deviceType\x12\x1d\n" +
	"\n" +
	"public_key\x18\n" +
	" \x01(\tR\tpublicKey\x12!\n" +
	"\ftrust_device\x18\v \x01(\bR\vtrustDevice\x12\x1b\n" +
	"\tclient_ip\x18\f \x01(\tR\bclientIp\x12\x1d\n" +
	"\n" +
	"user_agent\x18\r \x01(\tR\tuserAgent\x12$\n" +
	"\x0emfa_setting_id\x18\x0e \x01(\tR\fmfaSettingId\"\xb8\x03\n" +
	"\x1aVerifyMfaChallengeResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\arole_id\x18\x03 \x01(\tR\x06roleId\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\x1b\n" +
	"\ttenant_id\x18\x05 \x01(\tR\btenantId\x12(\n" +
	"\x10client_device_id\x18\x06 \x01(\tR\x0eclientDeviceId\x12#\n" +
	"\rrefresh_token\x18\a \x01(\tR\frefreshToken\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\x12\x1a\n" +
	"\busername\x18\t \x01(\tR\busername\x125\n" +
	"\x17client_proof_public_key\x18\n" +
	" \x01(\tR\x14clientProofPublicKey\x127\n" +
	"\x18refresh_token_expires_at\x18\v \x01(\x03R\x15refreshTokenExpiresAt\x12\x1f\n" +
	"\vtenant_code\x18\f \x01(\tR\n" +
	"tenantCode\"-\n" +
	"\tRoleEntry\x12 \n" +
	"\vpermissions\x18\x01 \x03(\tR\vpermissions\"\xdc\x01\n" +
	"\x0fMfaSetupPending\x12\x19\n" +
	"\bsetup_id\x18\x01 \x01(\tR\asetupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"setting_id\x18\x03 \x01(\tR\tsettingId\x12+\n" +
	"\x11secret_ciphertext\x18\x04 \x01(\tR\x10secretCiphertext\x12\"\n" +
	"\rsecret_key_id\x18\x05 \x01(\tR\vsecretKeyId\x12%\n" +
	"\x0eschema_version\x18\x06 \x01(\rR\rschemaVersion2\xd7\x02\n" +
	"\vAuthService\x12o\n" +
	"\x18VerifyOpaqueRefreshToken\x12(.iam.rpc.VerifyOpaqueRefreshTokenRequest\x1a).iam.rpc.VerifyOpaqueRefreshTokenResponse\x12o\n" +
	"\x18RevokeOpaqueRefreshToken\x12(.iam.rpc.RevokeOpaqueRefreshTokenRequest\x1a).iam.rpc.RevokeOpaqueRefreshTokenResponse\x12f\n" +
	"\x15VerifyUserCredentials\x12%.iam.rpc.VerifyUserCredentialsRequest\x1a&.iam.rpc.VerifyUserCredentialsResponseB8Z6controlplane/internal/iam/transport/rpc/proto;iamprotob\x06proto3"

var (
	file_auth_proto_rawDescOnce sync.Once
	file_auth_proto_rawDescData []byte
)

func file_auth_proto_rawDescGZIP() []byte {
	file_auth_proto_rawDescOnce.Do(func() {
		file_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)))
	})
	return file_auth_proto_rawDescData
}

var file_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_auth_proto_goTypes = []any{
	(*VerifyOpaqueRefreshTokenRequest)(nil),  // 0: iam.rpc.VerifyOpaqueRefreshTokenRequest
	(*VerifyOpaqueRefreshTokenResponse)(nil), // 1: iam.rpc.VerifyOpaqueRefreshTokenResponse
	(*RevokeOpaqueRefreshTokenRequest)(nil),  // 2: iam.rpc.RevokeOpaqueRefreshTokenRequest
	(*RevokeOpaqueRefreshTokenResponse)(nil), // 3: iam.rpc.RevokeOpaqueRefreshTokenResponse
	(*VerifyUserCredentialsRequest)(nil),     // 4: iam.rpc.VerifyUserCredentialsRequest
	(*VerifyUserCredentialsResponse)(nil),    // 5: iam.rpc.VerifyUserCredentialsResponse
	(*VerifyExternalIdentityRequest)(nil),    // 6: iam.rpc.VerifyExternalIdentityRequest
	(*VerifyExternalIdentityResponse)(nil),   // 7: iam.rpc.VerifyExternalIdentityResponse
	(*LinkExternalIdentityRequest)(nil),      // 8: iam.rpc.LinkExternalIdentityRequest
	(*LinkExternalIdentityResponse)(nil),     // 9: iam.rpc.LinkExternalIdentityResponse
	(*VerifyMfaChallengeRequest)(nil),        // 10: iam.rpc.VerifyMfaChallengeRequest
	(*VerifyMfaChallengeResponse)(nil),       // 11: iam.rpc.VerifyMfaChallengeResponse
	(*RoleEntry)(nil),                        // 12: iam.rpc.RoleEntry
	(*MfaSetupPending)(nil),                  // 13: iam.rpc.MfaSetupPending
}
var file_auth_proto_depIdxs = []int32{
	0, // 0: iam.rpc.AuthService.VerifyOpaqueRefreshToken:input_type -> iam.rpc.VerifyOpaqueRefreshTokenRequest
	2, // 1: iam.rpc.AuthService.RevokeOpaqueRefreshToken:input_type -> iam.rpc.RevokeOpaqueRefreshTokenRequest
	4, // 2: iam.rpc.AuthService.VerifyUserCredentials:input_type -> iam.rpc.VerifyUserCredentialsRequest
	1, // 3: iam.rpc.AuthService.VerifyOpaqueRefreshToken:output_type -> iam.rpc.VerifyOpaqueRefreshTokenResponse
	3, // 4: iam.rpc.AuthService.RevokeOpaqueRefreshToken:output_type -> iam.rpc.RevokeOpaqueRefreshTokenResponse
	5, // 5: iam.rpc.AuthService.VerifyUserCredentials:output_type -> iam.rpc.VerifyUserCredentialsResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_proto_init() }
func file_auth_proto_init() {
	if File_auth_proto != nil {
		return
	}
	file_auth_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_proto_goTypes,
		DependencyIndexes: file_auth_proto_depIdxs,
		MessageInfos:      file_auth_proto_msgTypes,
	}.Build()
	File_auth_proto = out.File
	file_auth_proto_goTypes = nil
	file_auth_proto_depIdxs = nil
}
