// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.30.2
// source: auth.proto

package iamproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthService_VerifyAdminTrinityToken_FullMethodName  = "/iam.rpc.AuthService/VerifyAdminTrinityToken"
	AuthService_VerifyUserTrinityToken_FullMethodName   = "/iam.rpc.AuthService/VerifyUserTrinityToken"
	AuthService_VerifyOpaqueRefreshToken_FullMethodName = "/iam.rpc.AuthService/VerifyOpaqueRefreshToken"
	AuthService_RevokeOpaqueRefreshToken_FullMethodName = "/iam.rpc.AuthService/RevokeOpaqueRefreshToken"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Dịch vụ xác thực Trinity Token gRPC kết nối giữa Notification Service (Rust) và Controlplane (Go)
type AuthServiceClient interface {
	// Xác thực Trinity credentials cho Admin/SRE quản trị hệ thống
	VerifyAdminTrinityToken(ctx context.Context, in *VerifyAdminTrinityTokenRequest, opts ...grpc.CallOption) (*VerifyAdminTrinityTokenResponse, error)
	// Xác thực Trinity credentials cho người dùng (End-User) thông thường
	VerifyUserTrinityToken(ctx context.Context, in *VerifyUserTrinityTokenRequest, opts ...grpc.CallOption) (*VerifyUserTrinityTokenResponse, error)
	// Xác thực Opaque Refresh Token lưu trong database (gọi nội bộ từ ACL Service)
	VerifyOpaqueRefreshToken(ctx context.Context, in *VerifyOpaqueRefreshTokenRequest, opts ...grpc.CallOption) (*VerifyOpaqueRefreshTokenResponse, error)
	// [COMMENT]: Thu hồi Opaque Refresh Token bất đồng bộ khi user thực hiện logout qua Gateway
	RevokeOpaqueRefreshToken(ctx context.Context, in *RevokeOpaqueRefreshTokenRequest, opts ...grpc.CallOption) (*RevokeOpaqueRefreshTokenResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) VerifyAdminTrinityToken(ctx context.Context, in *VerifyAdminTrinityTokenRequest, opts ...grpc.CallOption) (*VerifyAdminTrinityTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyAdminTrinityTokenResponse)
	err := c.cc.Invoke(ctx, AuthService_VerifyAdminTrinityToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) VerifyUserTrinityToken(ctx context.Context, in *VerifyUserTrinityTokenRequest, opts ...grpc.CallOption) (*VerifyUserTrinityTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyUserTrinityTokenResponse)
	err := c.cc.Invoke(ctx, AuthService_VerifyUserTrinityToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) VerifyOpaqueRefreshToken(ctx context.Context, in *VerifyOpaqueRefreshTokenRequest, opts ...grpc.CallOption) (*VerifyOpaqueRefreshTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyOpaqueRefreshTokenResponse)
	err := c.cc.Invoke(ctx, AuthService_VerifyOpaqueRefreshToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RevokeOpaqueRefreshToken(ctx context.Context, in *RevokeOpaqueRefreshTokenRequest, opts ...grpc.CallOption) (*RevokeOpaqueRefreshTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeOpaqueRefreshTokenResponse)
	err := c.cc.Invoke(ctx, AuthService_RevokeOpaqueRefreshToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility.
//
// Dịch vụ xác thực Trinity Token gRPC kết nối giữa Notification Service (Rust) và Controlplane (Go)
type AuthServiceServer interface {
	// Xác thực Trinity credentials cho Admin/SRE quản trị hệ thống
	VerifyAdminTrinityToken(context.Context, *VerifyAdminTrinityTokenRequest) (*VerifyAdminTrinityTokenResponse, error)
	// Xác thực Trinity credentials cho người dùng (End-User) thông thường
	VerifyUserTrinityToken(context.Context, *VerifyUserTrinityTokenRequest) (*VerifyUserTrinityTokenResponse, error)
	// Xác thực Opaque Refresh Token lưu trong database (gọi nội bộ từ ACL Service)
	VerifyOpaqueRefreshToken(context.Context, *VerifyOpaqueRefreshTokenRequest) (*VerifyOpaqueRefreshTokenResponse, error)
	// [COMMENT]: Thu hồi Opaque Refresh Token bất đồng bộ khi user thực hiện logout qua Gateway
	RevokeOpaqueRefreshToken(context.Context, *RevokeOpaqueRefreshTokenRequest) (*RevokeOpaqueRefreshTokenResponse, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) VerifyAdminTrinityToken(context.Context, *VerifyAdminTrinityTokenRequest) (*VerifyAdminTrinityTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyAdminTrinityToken not implemented")
}
func (UnimplementedAuthServiceServer) VerifyUserTrinityToken(context.Context, *VerifyUserTrinityTokenRequest) (*VerifyUserTrinityTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyUserTrinityToken not implemented")
}
func (UnimplementedAuthServiceServer) VerifyOpaqueRefreshToken(context.Context, *VerifyOpaqueRefreshTokenRequest) (*VerifyOpaqueRefreshTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyOpaqueRefreshToken not implemented")
}
func (UnimplementedAuthServiceServer) RevokeOpaqueRefreshToken(context.Context, *RevokeOpaqueRefreshTokenRequest) (*RevokeOpaqueRefreshTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeOpaqueRefreshToken not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}
func (UnimplementedAuthServiceServer) testEmbeddedByValue()                     {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_VerifyAdminTrinityToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyAdminTrinityTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).VerifyAdminTrinityToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_VerifyAdminTrinityToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).VerifyAdminTrinityToken(ctx, req.(*VerifyAdminTrinityTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_VerifyUserTrinityToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyUserTrinityTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).VerifyUserTrinityToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_VerifyUserTrinityToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).VerifyUserTrinityToken(ctx, req.(*VerifyUserTrinityTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_VerifyOpaqueRefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyOpaqueRefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).VerifyOpaqueRefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_VerifyOpaqueRefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).VerifyOpaqueRefreshToken(ctx, req.(*VerifyOpaqueRefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RevokeOpaqueRefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeOpaqueRefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RevokeOpaqueRefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_RevokeOpaqueRefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RevokeOpaqueRefreshToken(ctx, req.(*RevokeOpaqueRefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "iam.rpc.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyAdminTrinityToken",
			Handler:    _AuthService_VerifyAdminTrinityToken_Handler,
		},
		{
			MethodName: "VerifyUserTrinityToken",
			Handler:    _AuthService_VerifyUserTrinityToken_Handler,
		},
		{
			MethodName: "VerifyOpaqueRefreshToken",
			Handler:    _AuthService_VerifyOpaqueRefreshToken_Handler,
		},
		{
			MethodName: "RevokeOpaqueRefreshToken",
			Handler:    _AuthService_RevokeOpaqueRefreshToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
