// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: internal/iam/transport/rpc/proto/iam_cache.proto

package iamproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoleEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   []string               `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleEntry) Reset() {
	*x = RoleEntry{}
	mi := &file_internal_iam_transport_rpc_proto_iam_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleEntry) ProtoMessage() {}

func (x *RoleEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_iam_transport_rpc_proto_iam_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleEntry.ProtoReflect.Descriptor instead.
func (*RoleEntry) Descriptor() ([]byte, []int) {
	return file_internal_iam_transport_rpc_proto_iam_cache_proto_rawDescGZIP(), []int{0}
}

func (x *RoleEntry) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type AdminAPIKey struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // UUID string
	KeyHash         string                 `protobuf:"bytes,2,opt,name=key_hash,json=keyHash,proto3" json:"key_hash,omitempty"`
	CreatedBy       string                 `protobuf:"bytes,3,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAtUnixNs int64                  `protobuf:"varint,4,opt,name=created_at_unix_ns,json=createdAtUnixNs,proto3" json:"created_at_unix_ns,omitempty"`
	ExpiresAtUnixNs int64                  `protobuf:"varint,5,opt,name=expires_at_unix_ns,json=expiresAtUnixNs,proto3" json:"expires_at_unix_ns,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AdminAPIKey) Reset() {
	*x = AdminAPIKey{}
	mi := &file_internal_iam_transport_rpc_proto_iam_cache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminAPIKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminAPIKey) ProtoMessage() {}

func (x *AdminAPIKey) ProtoReflect() protoreflect.Message {
	mi := &file_internal_iam_transport_rpc_proto_iam_cache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminAPIKey.ProtoReflect.Descriptor instead.
func (*AdminAPIKey) Descriptor() ([]byte, []int) {
	return file_internal_iam_transport_rpc_proto_iam_cache_proto_rawDescGZIP(), []int{1}
}

func (x *AdminAPIKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AdminAPIKey) GetKeyHash() string {
	if x != nil {
		return x.KeyHash
	}
	return ""
}

func (x *AdminAPIKey) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *AdminAPIKey) GetCreatedAtUnixNs() int64 {
	if x != nil {
		return x.CreatedAtUnixNs
	}
	return 0
}

func (x *AdminAPIKey) GetExpiresAtUnixNs() int64 {
	if x != nil {
		return x.ExpiresAtUnixNs
	}
	return 0
}

var File_internal_iam_transport_rpc_proto_iam_cache_proto protoreflect.FileDescriptor

const file_internal_iam_transport_rpc_proto_iam_cache_proto_rawDesc = "" +
	"\n" +
	"0internal/iam/transport/rpc/proto/iam_cache.proto\x12\aiam.rpc\"-\n" +
	"\tRoleEntry\x12 \n" +
	"\vpermissions\x18\x01 \x03(\tR\vpermissions\"\xb1\x01\n" +
	"\vAdminAPIKey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bkey_hash\x18\x02 \x01(\tR\akeyHash\x12\x1d\n" +
	"\n" +
	"created_by\x18\x03 \x01(\tR\tcreatedBy\x12+\n" +
	"\x12created_at_unix_ns\x18\x04 \x01(\x03R\x0fcreatedAtUnixNs\x12+\n" +
	"\x12expires_at_unix_ns\x18\x05 \x01(\x03R\x0fexpiresAtUnixNsB8Z6controlplane/internal/iam/transport/rpc/proto;iamprotob\x06proto3"

var (
	file_internal_iam_transport_rpc_proto_iam_cache_proto_rawDescOnce sync.Once
	file_internal_iam_transport_rpc_proto_iam_cache_proto_rawDescData []byte
)

func file_internal_iam_transport_rpc_proto_iam_cache_proto_rawDescGZIP() []byte {
	file_internal_iam_transport_rpc_proto_iam_cache_proto_rawDescOnce.Do(func() {
		file_internal_iam_transport_rpc_proto_iam_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_iam_transport_rpc_proto_iam_cache_proto_rawDesc), len(file_internal_iam_transport_rpc_proto_iam_cache_proto_rawDesc)))
	})
	return file_internal_iam_transport_rpc_proto_iam_cache_proto_rawDescData
}

var file_internal_iam_transport_rpc_proto_iam_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_iam_transport_rpc_proto_iam_cache_proto_goTypes = []any{
	(*RoleEntry)(nil),   // 0: iam.rpc.RoleEntry
	(*AdminAPIKey)(nil), // 1: iam.rpc.AdminAPIKey
}
var file_internal_iam_transport_rpc_proto_iam_cache_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_iam_transport_rpc_proto_iam_cache_proto_init() }
func file_internal_iam_transport_rpc_proto_iam_cache_proto_init() {
	if File_internal_iam_transport_rpc_proto_iam_cache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_iam_transport_rpc_proto_iam_cache_proto_rawDesc), len(file_internal_iam_transport_rpc_proto_iam_cache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_iam_transport_rpc_proto_iam_cache_proto_goTypes,
		DependencyIndexes: file_internal_iam_transport_rpc_proto_iam_cache_proto_depIdxs,
		MessageInfos:      file_internal_iam_transport_rpc_proto_iam_cache_proto_msgTypes,
	}.Build()
	File_internal_iam_transport_rpc_proto_iam_cache_proto = out.File
	file_internal_iam_transport_rpc_proto_iam_cache_proto_goTypes = nil
	file_internal_iam_transport_rpc_proto_iam_cache_proto_depIdxs = nil
}
