syntax = "proto3";
package storage;

// Cấu hình đồng bộ hóa Bucket vật lý từ Controlplane sang Dataplane
message BucketSync {
  string name = 1;                // Tên vật lý của bucket
  string access_key = 2;          // Access Key sẽ được tạo trên MinIO
  string secret_key = 3;          // Secret Key (plaintext trong payload, transit qua internal infra)
  string policy = 4;              // JSON policy giới hạn quyền truy cập chỉ vào bucket này
}

// Cấu hình đồng bộ hóa Credential vật lý từ Controlplane sang Dataplane
message CredentialSync {
  string id = 1;                  // ID credential dạng UUID string
  string bucket_id = 2;           // ID bucket liên kết
  string access_key = 3;          // Access Key MinIO
  string secret_key = 4;          // Secret Key MinIO
  string policy = 5;              // JSON policy
  string status = 6;              // Trạng thái hoạt động (active, revoked)
}
