// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: storage/bucket_lifecycle/v1/bucket_lifecycle.proto

package storageproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Cấu hình đồng bộ hóa Bucket vật lý từ Controlplane sang Dataplane
type BucketCreateSync struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Name                       string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AccessKey                  string                 `protobuf:"bytes,2,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	SecretKey                  string                 `protobuf:"bytes,3,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	Policy                     string                 `protobuf:"bytes,4,opt,name=policy,proto3" json:"policy,omitempty"`
	EncryptEnabled             bool                   `protobuf:"varint,5,opt,name=encrypt_enabled,json=encryptEnabled,proto3" json:"encrypt_enabled,omitempty"`
	VersioningEnabled          bool                   `protobuf:"varint,6,opt,name=versioning_enabled,json=versioningEnabled,proto3" json:"versioning_enabled,omitempty"`
	ObjectLockingEnabled       bool                   `protobuf:"varint,7,opt,name=object_locking_enabled,json=objectLockingEnabled,proto3" json:"object_locking_enabled,omitempty"`
	ReplicationEnabled         bool                   `protobuf:"varint,8,opt,name=replication_enabled,json=replicationEnabled,proto3" json:"replication_enabled,omitempty"`
	RetentionDays              int64                  `protobuf:"varint,9,opt,name=retention_days,json=retentionDays,proto3" json:"retention_days,omitempty"`
	LegalHoldEnabled           bool                   `protobuf:"varint,10,opt,name=legal_hold_enabled,json=legalHoldEnabled,proto3" json:"legal_hold_enabled,omitempty"`
	Tags                       string                 `protobuf:"bytes,11,opt,name=tags,proto3" json:"tags,omitempty"`
	QuotaBytes                 int64                  `protobuf:"varint,12,opt,name=quota_bytes,json=quotaBytes,proto3" json:"quota_bytes,omitempty"`
	BucketId                   []byte                 `protobuf:"bytes,13,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	OwnerId                    []byte                 `protobuf:"bytes,14,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	OwnerType                  string                 `protobuf:"bytes,15,opt,name=owner_type,json=ownerType,proto3" json:"owner_type,omitempty"`
	WorkspaceId                []byte                 `protobuf:"bytes,16,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	ZoneId                     []byte                 `protobuf:"bytes,17,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	SchemaVersion              uint32                 `protobuf:"varint,18,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	AdmissionPolicyVersion     int64                  `protobuf:"varint,19,opt,name=admission_policy_version,json=admissionPolicyVersion,proto3" json:"admission_policy_version,omitempty"`
	AdmissionDecision          string                 `protobuf:"bytes,20,opt,name=admission_decision,json=admissionDecision,proto3" json:"admission_decision,omitempty"`
	AdmissionEffectiveAt       string                 `protobuf:"bytes,21,opt,name=admission_effective_at,json=admissionEffectiveAt,proto3" json:"admission_effective_at,omitempty"`
	AdmissionValidUntil        string                 `protobuf:"bytes,22,opt,name=admission_valid_until,json=admissionValidUntil,proto3" json:"admission_valid_until,omitempty"`
	AdmissionSourceEventId     string                 `protobuf:"bytes,23,opt,name=admission_source_event_id,json=admissionSourceEventId,proto3" json:"admission_source_event_id,omitempty"`
	AdmissionRestrictionReason string                 `protobuf:"bytes,24,opt,name=admission_restriction_reason,json=admissionRestrictionReason,proto3" json:"admission_restriction_reason,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *BucketCreateSync) Reset() {
	*x = BucketCreateSync{}
	mi := &file_storage_bucket_lifecycle_v1_bucket_lifecycle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BucketCreateSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketCreateSync) ProtoMessage() {}

func (x *BucketCreateSync) ProtoReflect() protoreflect.Message {
	mi := &file_storage_bucket_lifecycle_v1_bucket_lifecycle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketCreateSync.ProtoReflect.Descriptor instead.
func (*BucketCreateSync) Descriptor() ([]byte, []int) {
	return file_storage_bucket_lifecycle_v1_bucket_lifecycle_proto_rawDescGZIP(), []int{0}
}

func (x *BucketCreateSync) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BucketCreateSync) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *BucketCreateSync) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *BucketCreateSync) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

func (x *BucketCreateSync) GetEncryptEnabled() bool {
	if x != nil {
		return x.EncryptEnabled
	}
	return false
}

func (x *BucketCreateSync) GetVersioningEnabled() bool {
	if x != nil {
		return x.VersioningEnabled
	}
	return false
}

func (x *BucketCreateSync) GetObjectLockingEnabled() bool {
	if x != nil {
		return x.ObjectLockingEnabled
	}
	return false
}

func (x *BucketCreateSync) GetReplicationEnabled() bool {
	if x != nil {
		return x.ReplicationEnabled
	}
	return false
}

func (x *BucketCreateSync) GetRetentionDays() int64 {
	if x != nil {
		return x.RetentionDays
	}
	return 0
}

func (x *BucketCreateSync) GetLegalHoldEnabled() bool {
	if x != nil {
		return x.LegalHoldEnabled
	}
	return false
}

func (x *BucketCreateSync) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *BucketCreateSync) GetQuotaBytes() int64 {
	if x != nil {
		return x.QuotaBytes
	}
	return 0
}

func (x *BucketCreateSync) GetBucketId() []byte {
	if x != nil {
		return x.BucketId
	}
	return nil
}

func (x *BucketCreateSync) GetOwnerId() []byte {
	if x != nil {
		return x.OwnerId
	}
	return nil
}

func (x *BucketCreateSync) GetOwnerType() string {
	if x != nil {
		return x.OwnerType
	}
	return ""
}

func (x *BucketCreateSync) GetWorkspaceId() []byte {
	if x != nil {
		return x.WorkspaceId
	}
	return nil
}

func (x *BucketCreateSync) GetZoneId() []byte {
	if x != nil {
		return x.ZoneId
	}
	return nil
}

func (x *BucketCreateSync) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *BucketCreateSync) GetAdmissionPolicyVersion() int64 {
	if x != nil {
		return x.AdmissionPolicyVersion
	}
	return 0
}

func (x *BucketCreateSync) GetAdmissionDecision() string {
	if x != nil {
		return x.AdmissionDecision
	}
	return ""
}

func (x *BucketCreateSync) GetAdmissionEffectiveAt() string {
	if x != nil {
		return x.AdmissionEffectiveAt
	}
	return ""
}

func (x *BucketCreateSync) GetAdmissionValidUntil() string {
	if x != nil {
		return x.AdmissionValidUntil
	}
	return ""
}

func (x *BucketCreateSync) GetAdmissionSourceEventId() string {
	if x != nil {
		return x.AdmissionSourceEventId
	}
	return ""
}

func (x *BucketCreateSync) GetAdmissionRestrictionReason() string {
	if x != nil {
		return x.AdmissionRestrictionReason
	}
	return ""
}

type BucketResizeSync struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	BucketId            string                 `protobuf:"bytes,1,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CurrentQuotaBytes   int64                  `protobuf:"varint,3,opt,name=current_quota_bytes,json=currentQuotaBytes,proto3" json:"current_quota_bytes,omitempty"`
	RequestedQuotaBytes int64                  `protobuf:"varint,4,opt,name=requested_quota_bytes,json=requestedQuotaBytes,proto3" json:"requested_quota_bytes,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BucketResizeSync) Reset() {
	*x = BucketResizeSync{}
	mi := &file_storage_bucket_lifecycle_v1_bucket_lifecycle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BucketResizeSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketResizeSync) ProtoMessage() {}

func (x *BucketResizeSync) ProtoReflect() protoreflect.Message {
	mi := &file_storage_bucket_lifecycle_v1_bucket_lifecycle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketResizeSync.ProtoReflect.Descriptor instead.
func (*BucketResizeSync) Descriptor() ([]byte, []int) {
	return file_storage_bucket_lifecycle_v1_bucket_lifecycle_proto_rawDescGZIP(), []int{1}
}

func (x *BucketResizeSync) GetBucketId() string {
	if x != nil {
		return x.BucketId
	}
	return ""
}

func (x *BucketResizeSync) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BucketResizeSync) GetCurrentQuotaBytes() int64 {
	if x != nil {
		return x.CurrentQuotaBytes
	}
	return 0
}

func (x *BucketResizeSync) GetRequestedQuotaBytes() int64 {
	if x != nil {
		return x.RequestedQuotaBytes
	}
	return 0
}

type BucketDeleteSync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AccessKeys    []string               `protobuf:"bytes,2,rep,name=access_keys,json=accessKeys,proto3" json:"access_keys,omitempty"`
	BucketId      []byte                 `protobuf:"bytes,3,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	OwnerId       []byte                 `protobuf:"bytes,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	OwnerType     string                 `protobuf:"bytes,5,opt,name=owner_type,json=ownerType,proto3" json:"owner_type,omitempty"`
	WorkspaceId   []byte                 `protobuf:"bytes,6,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	ZoneId        []byte                 `protobuf:"bytes,7,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	SchemaVersion uint32                 `protobuf:"varint,8,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BucketDeleteSync) Reset() {
	*x = BucketDeleteSync{}
	mi := &file_storage_bucket_lifecycle_v1_bucket_lifecycle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BucketDeleteSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketDeleteSync) ProtoMessage() {}

func (x *BucketDeleteSync) ProtoReflect() protoreflect.Message {
	mi := &file_storage_bucket_lifecycle_v1_bucket_lifecycle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketDeleteSync.ProtoReflect.Descriptor instead.
func (*BucketDeleteSync) Descriptor() ([]byte, []int) {
	return file_storage_bucket_lifecycle_v1_bucket_lifecycle_proto_rawDescGZIP(), []int{2}
}

func (x *BucketDeleteSync) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BucketDeleteSync) GetAccessKeys() []string {
	if x != nil {
		return x.AccessKeys
	}
	return nil
}

func (x *BucketDeleteSync) GetBucketId() []byte {
	if x != nil {
		return x.BucketId
	}
	return nil
}

func (x *BucketDeleteSync) GetOwnerId() []byte {
	if x != nil {
		return x.OwnerId
	}
	return nil
}

func (x *BucketDeleteSync) GetOwnerType() string {
	if x != nil {
		return x.OwnerType
	}
	return ""
}

func (x *BucketDeleteSync) GetWorkspaceId() []byte {
	if x != nil {
		return x.WorkspaceId
	}
	return nil
}

func (x *BucketDeleteSync) GetZoneId() []byte {
	if x != nil {
		return x.ZoneId
	}
	return nil
}

func (x *BucketDeleteSync) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

type BucketVersioningSync struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BucketId          string                 `protobuf:"bytes,1,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	VersioningEnabled bool                   `protobuf:"varint,3,opt,name=versioning_enabled,json=versioningEnabled,proto3" json:"versioning_enabled,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BucketVersioningSync) Reset() {
	*x = BucketVersioningSync{}
	mi := &file_storage_bucket_lifecycle_v1_bucket_lifecycle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BucketVersioningSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketVersioningSync) ProtoMessage() {}

func (x *BucketVersioningSync) ProtoReflect() protoreflect.Message {
	mi := &file_storage_bucket_lifecycle_v1_bucket_lifecycle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketVersioningSync.ProtoReflect.Descriptor instead.
func (*BucketVersioningSync) Descriptor() ([]byte, []int) {
	return file_storage_bucket_lifecycle_v1_bucket_lifecycle_proto_rawDescGZIP(), []int{3}
}

func (x *BucketVersioningSync) GetBucketId() string {
	if x != nil {
		return x.BucketId
	}
	return ""
}

func (x *BucketVersioningSync) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BucketVersioningSync) GetVersioningEnabled() bool {
	if x != nil {
		return x.VersioningEnabled
	}
	return false
}

type LifecycleRuleSync struct {
	state                              protoimpl.MessageState `protogen:"open.v1"`
	Id                                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Enabled                            bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Prefix                             string                 `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
	ExpirationDays                     int32                  `protobuf:"varint,4,opt,name=expiration_days,json=expirationDays,proto3" json:"expiration_days,omitempty"`
	NoncurrentVersionExpirationDays    int32                  `protobuf:"varint,5,opt,name=noncurrent_version_expiration_days,json=noncurrentVersionExpirationDays,proto3" json:"noncurrent_version_expiration_days,omitempty"`
	AbortIncompleteMultipartUploadDays int32                  `protobuf:"varint,6,opt,name=abort_incomplete_multipart_upload_days,json=abortIncompleteMultipartUploadDays,proto3" json:"abort_incomplete_multipart_upload_days,omitempty"`
	unknownFields                      protoimpl.UnknownFields
	sizeCache                          protoimpl.SizeCache
}

func (x *LifecycleRuleSync) Reset() {
	*x = LifecycleRuleSync{}
	mi := &file_storage_bucket_lifecycle_v1_bucket_lifecycle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LifecycleRuleSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifecycleRuleSync) ProtoMessage() {}

func (x *LifecycleRuleSync) ProtoReflect() protoreflect.Message {
	mi := &file_storage_bucket_lifecycle_v1_bucket_lifecycle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifecycleRuleSync.ProtoReflect.Descriptor instead.
func (*LifecycleRuleSync) Descriptor() ([]byte, []int) {
	return file_storage_bucket_lifecycle_v1_bucket_lifecycle_proto_rawDescGZIP(), []int{4}
}

func (x *LifecycleRuleSync) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LifecycleRuleSync) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *LifecycleRuleSync) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *LifecycleRuleSync) GetExpirationDays() int32 {
	if x != nil {
		return x.ExpirationDays
	}
	return 0
}

func (x *LifecycleRuleSync) GetNoncurrentVersionExpirationDays() int32 {
	if x != nil {
		return x.NoncurrentVersionExpirationDays
	}
	return 0
}

func (x *LifecycleRuleSync) GetAbortIncompleteMultipartUploadDays() int32 {
	if x != nil {
		return x.AbortIncompleteMultipartUploadDays
	}
	return 0
}

type BucketLifecycleSync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BucketId      string                 `protobuf:"bytes,1,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Rules         []*LifecycleRuleSync   `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BucketLifecycleSync) Reset() {
	*x = BucketLifecycleSync{}
	mi := &file_storage_bucket_lifecycle_v1_bucket_lifecycle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BucketLifecycleSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketLifecycleSync) ProtoMessage() {}

func (x *BucketLifecycleSync) ProtoReflect() protoreflect.Message {
	mi := &file_storage_bucket_lifecycle_v1_bucket_lifecycle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketLifecycleSync.ProtoReflect.Descriptor instead.
func (*BucketLifecycleSync) Descriptor() ([]byte, []int) {
	return file_storage_bucket_lifecycle_v1_bucket_lifecycle_proto_rawDescGZIP(), []int{5}
}

func (x *BucketLifecycleSync) GetBucketId() string {
	if x != nil {
		return x.BucketId
	}
	return ""
}

func (x *BucketLifecycleSync) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BucketLifecycleSync) GetRules() []*LifecycleRuleSync {
	if x != nil {
		return x.Rules
	}
	return nil
}

// Dataplane emits these typed settlement payloads only after the matching
// MinIO mutation returns success. JO promotes these actual values into Central
// SoT; the generic outbox never stores Storage-specific target columns.
type BucketQuotaAppliedV1 struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion    uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	BucketId         string                 `protobuf:"bytes,2,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	ActualQuotaBytes int64                  `protobuf:"varint,3,opt,name=actual_quota_bytes,json=actualQuotaBytes,proto3" json:"actual_quota_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BucketQuotaAppliedV1) Reset() {
	*x = BucketQuotaAppliedV1{}
	mi := &file_storage_bucket_lifecycle_v1_bucket_lifecycle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BucketQuotaAppliedV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketQuotaAppliedV1) ProtoMessage() {}

func (x *BucketQuotaAppliedV1) ProtoReflect() protoreflect.Message {
	mi := &file_storage_bucket_lifecycle_v1_bucket_lifecycle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketQuotaAppliedV1.ProtoReflect.Descriptor instead.
func (*BucketQuotaAppliedV1) Descriptor() ([]byte, []int) {
	return file_storage_bucket_lifecycle_v1_bucket_lifecycle_proto_rawDescGZIP(), []int{6}
}

func (x *BucketQuotaAppliedV1) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *BucketQuotaAppliedV1) GetBucketId() string {
	if x != nil {
		return x.BucketId
	}
	return ""
}

func (x *BucketQuotaAppliedV1) GetActualQuotaBytes() int64 {
	if x != nil {
		return x.ActualQuotaBytes
	}
	return 0
}

type BucketVersioningAppliedV1 struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion           uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	BucketId                string                 `protobuf:"bytes,2,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	ActualVersioningEnabled bool                   `protobuf:"varint,3,opt,name=actual_versioning_enabled,json=actualVersioningEnabled,proto3" json:"actual_versioning_enabled,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *BucketVersioningAppliedV1) Reset() {
	*x = BucketVersioningAppliedV1{}
	mi := &file_storage_bucket_lifecycle_v1_bucket_lifecycle_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BucketVersioningAppliedV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketVersioningAppliedV1) ProtoMessage() {}

func (x *BucketVersioningAppliedV1) ProtoReflect() protoreflect.Message {
	mi := &file_storage_bucket_lifecycle_v1_bucket_lifecycle_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketVersioningAppliedV1.ProtoReflect.Descriptor instead.
func (*BucketVersioningAppliedV1) Descriptor() ([]byte, []int) {
	return file_storage_bucket_lifecycle_v1_bucket_lifecycle_proto_rawDescGZIP(), []int{7}
}

func (x *BucketVersioningAppliedV1) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *BucketVersioningAppliedV1) GetBucketId() string {
	if x != nil {
		return x.BucketId
	}
	return ""
}

func (x *BucketVersioningAppliedV1) GetActualVersioningEnabled() bool {
	if x != nil {
		return x.ActualVersioningEnabled
	}
	return false
}

type BucketLifecycleAppliedV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	BucketId      string                 `protobuf:"bytes,2,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	ActualRules   []*LifecycleRuleSync   `protobuf:"bytes,3,rep,name=actual_rules,json=actualRules,proto3" json:"actual_rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BucketLifecycleAppliedV1) Reset() {
	*x = BucketLifecycleAppliedV1{}
	mi := &file_storage_bucket_lifecycle_v1_bucket_lifecycle_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BucketLifecycleAppliedV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketLifecycleAppliedV1) ProtoMessage() {}

func (x *BucketLifecycleAppliedV1) ProtoReflect() protoreflect.Message {
	mi := &file_storage_bucket_lifecycle_v1_bucket_lifecycle_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketLifecycleAppliedV1.ProtoReflect.Descriptor instead.
func (*BucketLifecycleAppliedV1) Descriptor() ([]byte, []int) {
	return file_storage_bucket_lifecycle_v1_bucket_lifecycle_proto_rawDescGZIP(), []int{8}
}

func (x *BucketLifecycleAppliedV1) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *BucketLifecycleAppliedV1) GetBucketId() string {
	if x != nil {
		return x.BucketId
	}
	return ""
}

func (x *BucketLifecycleAppliedV1) GetActualRules() []*LifecycleRuleSync {
	if x != nil {
		return x.ActualRules
	}
	return nil
}

var File_storage_bucket_lifecycle_v1_bucket_lifecycle_proto protoreflect.FileDescriptor

const file_storage_bucket_lifecycle_v1_bucket_lifecycle_proto_rawDesc = "" +
	"\n" +
	"2storage/bucket_lifecycle/v1/bucket_lifecycle.proto\x12\astorage\"\xcf\a\n" +
	"\x10BucketCreateSync\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"access_key\x18\x02 \x01(\tR\taccessKey\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x03 \x01(\tR\tsecretKey\x12\x16\n" +
	"\x06policy\x18\x04 \x01(\tR\x06policy\x12'\n" +
	"\x0fencrypt_enabled\x18\x05 \x01(\bR\x0eencryptEnabled\x12-\n" +
	"\x12versioning_enabled\x18\x06 \x01(\bR\x11versioningEnabled\x124\n" +
	"\x16object_locking_enabled\x18\a \x01(\bR\x14objectLockingEnabled\x12/\n" +
	"\x13replication_enabled\x18\b \x01(\bR\x12replicationEnabled\x12%\n" +
	"\x0eretention_days\x18\t \x01(\x03R\rretentionDays\x12,\n" +
	"\x12legal_hold_enabled\x18\n" +
	" \x01(\bR\x10legalHoldEnabled\x12\x12\n" +
	"\x04tags\x18\v \x01(\tR\x04tags\x12\x1f\n" +
	"\vquota_bytes\x18\f \x01(\x03R\n" +
	"quotaBytes\x12\x1b\n" +
	"\tbucket_id\x18\r \x01(\fR\bbucketId\x12\x19\n" +
	"\bowner_id\x18\x0e \x01(\fR\aownerId\x12\x1d\n" +
	"\n" +
	"owner_type\x18\x0f \x01(\tR\townerType\x12!\n" +
	"\fworkspace_id\x18\x10 \x01(\fR\vworkspaceId\x12\x17\n" +
	"\azone_id\x18\x11 \x01(\fR\x06zoneId\x12%\n" +
	"\x0eschema_version\x18\x12 \x01(\rR\rschemaVersion\x128\n" +
	"\x18admission_policy_version\x18\x13 \x01(\x03R\x16admissionPolicyVersion\x12-\n" +
	"\x12admission_decision\x18\x14 \x01(\tR\x11admissionDecision\x124\n" +
	"\x16admission_effective_at\x18\x15 \x01(\tR\x14admissionEffectiveAt\x122\n" +
	"\x15admission_valid_until\x18\x16 \x01(\tR\x13admissionValidUntil\x129\n" +
	"\x19admission_source_event_id\x18\x17 \x01(\tR\x16admissionSourceEventId\x12@\n" +
	"\x1cadmission_restriction_reason\x18\x18 \x01(\tR\x1aadmissionRestrictionReason\"\xa7\x01\n" +
	"\x10BucketResizeSync\x12\x1b\n" +
	"\tbucket_id\x18\x01 \x01(\tR\bbucketId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12.\n" +
	"\x13current_quota_bytes\x18\x03 \x01(\x03R\x11currentQuotaBytes\x122\n" +
	"\x15requested_quota_bytes\x18\x04 \x01(\x03R\x13requestedQuotaBytes\"\x81\x02\n" +
	"\x10BucketDeleteSync\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vaccess_keys\x18\x02 \x03(\tR\n" +
	"accessKeys\x12\x1b\n" +
	"\tbucket_id\x18\x03 \x01(\fR\bbucketId\x12\x19\n" +
	"\bowner_id\x18\x04 \x01(\fR\aownerId\x12\x1d\n" +
	"\n" +
	"owner_type\x18\x05 \x01(\tR\townerType\x12!\n" +
	"\fworkspace_id\x18\x06 \x01(\fR\vworkspaceId\x12\x17\n" +
	"\azone_id\x18\a \x01(\fR\x06zoneId\x12%\n" +
	"\x0eschema_version\x18\b \x01(\rR\rschemaVersion\"v\n" +
	"\x14BucketVersioningSync\x12\x1b\n" +
	"\tbucket_id\x18\x01 \x01(\tR\bbucketId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12-\n" +
	"\x12versioning_enabled\x18\x03 \x01(\bR\x11versioningEnabled\"\x9f\x02\n" +
	"\x11LifecycleRuleSync\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x12\x16\n" +
	"\x06prefix\x18\x03 \x01(\tR\x06prefix\x12'\n" +
	"\x0fexpiration_days\x18\x04 \x01(\x05R\x0eexpirationDays\x12K\n" +
	"\"noncurrent_version_expiration_days\x18\x05 \x01(\x05R\x1fnoncurrentVersionExpirationDays\x12R\n" +
	"&abort_incomplete_multipart_upload_days\x18\x06 \x01(\x05R\"abortIncompleteMultipartUploadDays\"x\n" +
	"\x13BucketLifecycleSync\x12\x1b\n" +
	"\tbucket_id\x18\x01 \x01(\tR\bbucketId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x120\n" +
	"\x05rules\x18\x03 \x03(\v2\x1a.storage.LifecycleRuleSyncR\x05rules\"\x88\x01\n" +
	"\x14BucketQuotaAppliedV1\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x1b\n" +
	"\tbucket_id\x18\x02 \x01(\tR\bbucketId\x12,\n" +
	"\x12actual_quota_bytes\x18\x03 \x01(\x03R\x10actualQuotaBytes\"\x9b\x01\n" +
	"\x19BucketVersioningAppliedV1\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x1b\n" +
	"\tbucket_id\x18\x02 \x01(\tR\bbucketId\x12:\n" +
	"\x19actual_versioning_enabled\x18\x03 \x01(\bR\x17actualVersioningEnabled\"\x9d\x01\n" +
	"\x18BucketLifecycleAppliedV1\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x1b\n" +
	"\tbucket_id\x18\x02 \x01(\tR\bbucketId\x12=\n" +
	"\factual_rules\x18\x03 \x03(\v2\x1a.storage.LifecycleRuleSyncR\vactualRulesB<Z:controlplane/internal/storage/transport/proto;storageprotob\x06proto3"

var (
	file_storage_bucket_lifecycle_v1_bucket_lifecycle_proto_rawDescOnce sync.Once
	file_storage_bucket_lifecycle_v1_bucket_lifecycle_proto_rawDescData []byte
)

func file_storage_bucket_lifecycle_v1_bucket_lifecycle_proto_rawDescGZIP() []byte {
	file_storage_bucket_lifecycle_v1_bucket_lifecycle_proto_rawDescOnce.Do(func() {
		file_storage_bucket_lifecycle_v1_bucket_lifecycle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_bucket_lifecycle_v1_bucket_lifecycle_proto_rawDesc), len(file_storage_bucket_lifecycle_v1_bucket_lifecycle_proto_rawDesc)))
	})
	return file_storage_bucket_lifecycle_v1_bucket_lifecycle_proto_rawDescData
}

var file_storage_bucket_lifecycle_v1_bucket_lifecycle_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_storage_bucket_lifecycle_v1_bucket_lifecycle_proto_goTypes = []any{
	(*BucketCreateSync)(nil),          // 0: storage.BucketCreateSync
	(*BucketResizeSync)(nil),          // 1: storage.BucketResizeSync
	(*BucketDeleteSync)(nil),          // 2: storage.BucketDeleteSync
	(*BucketVersioningSync)(nil),      // 3: storage.BucketVersioningSync
	(*LifecycleRuleSync)(nil),         // 4: storage.LifecycleRuleSync
	(*BucketLifecycleSync)(nil),       // 5: storage.BucketLifecycleSync
	(*BucketQuotaAppliedV1)(nil),      // 6: storage.BucketQuotaAppliedV1
	(*BucketVersioningAppliedV1)(nil), // 7: storage.BucketVersioningAppliedV1
	(*BucketLifecycleAppliedV1)(nil),  // 8: storage.BucketLifecycleAppliedV1
}
var file_storage_bucket_lifecycle_v1_bucket_lifecycle_proto_depIdxs = []int32{
	4, // 0: storage.BucketLifecycleSync.rules:type_name -> storage.LifecycleRuleSync
	4, // 1: storage.BucketLifecycleAppliedV1.actual_rules:type_name -> storage.LifecycleRuleSync
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_storage_bucket_lifecycle_v1_bucket_lifecycle_proto_init() }
func file_storage_bucket_lifecycle_v1_bucket_lifecycle_proto_init() {
	if File_storage_bucket_lifecycle_v1_bucket_lifecycle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_bucket_lifecycle_v1_bucket_lifecycle_proto_rawDesc), len(file_storage_bucket_lifecycle_v1_bucket_lifecycle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_storage_bucket_lifecycle_v1_bucket_lifecycle_proto_goTypes,
		DependencyIndexes: file_storage_bucket_lifecycle_v1_bucket_lifecycle_proto_depIdxs,
		MessageInfos:      file_storage_bucket_lifecycle_v1_bucket_lifecycle_proto_msgTypes,
	}.Build()
	File_storage_bucket_lifecycle_v1_bucket_lifecycle_proto = out.File
	file_storage_bucket_lifecycle_v1_bucket_lifecycle_proto_goTypes = nil
	file_storage_bucket_lifecycle_v1_bucket_lifecycle_proto_depIdxs = nil
}
