// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: controlplane/storage/commercial_admission.proto

package storageproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CommercialAdmissionChangedV1 exposes only the owner-scoped commercial
// decision required by the storage module.
type CommercialAdmissionChangedV1 struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	EventId           string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	OwnerId           string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	OwnerType         string                 `protobuf:"bytes,3,opt,name=owner_type,json=ownerType,proto3" json:"owner_type,omitempty"`
	PolicyVersion     int64                  `protobuf:"varint,4,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	Decision          string                 `protobuf:"bytes,5,opt,name=decision,proto3" json:"decision,omitempty"`
	RestrictionReason string                 `protobuf:"bytes,6,opt,name=restriction_reason,json=restrictionReason,proto3" json:"restriction_reason,omitempty"`
	EffectiveAt       string                 `protobuf:"bytes,7,opt,name=effective_at,json=effectiveAt,proto3" json:"effective_at,omitempty"`
	ValidUntil        string                 `protobuf:"bytes,8,opt,name=valid_until,json=validUntil,proto3" json:"valid_until,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CommercialAdmissionChangedV1) Reset() {
	*x = CommercialAdmissionChangedV1{}
	mi := &file_controlplane_storage_commercial_admission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommercialAdmissionChangedV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommercialAdmissionChangedV1) ProtoMessage() {}

func (x *CommercialAdmissionChangedV1) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_storage_commercial_admission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommercialAdmissionChangedV1.ProtoReflect.Descriptor instead.
func (*CommercialAdmissionChangedV1) Descriptor() ([]byte, []int) {
	return file_controlplane_storage_commercial_admission_proto_rawDescGZIP(), []int{0}
}

func (x *CommercialAdmissionChangedV1) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *CommercialAdmissionChangedV1) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *CommercialAdmissionChangedV1) GetOwnerType() string {
	if x != nil {
		return x.OwnerType
	}
	return ""
}

func (x *CommercialAdmissionChangedV1) GetPolicyVersion() int64 {
	if x != nil {
		return x.PolicyVersion
	}
	return 0
}

func (x *CommercialAdmissionChangedV1) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *CommercialAdmissionChangedV1) GetRestrictionReason() string {
	if x != nil {
		return x.RestrictionReason
	}
	return ""
}

func (x *CommercialAdmissionChangedV1) GetEffectiveAt() string {
	if x != nil {
		return x.EffectiveAt
	}
	return ""
}

func (x *CommercialAdmissionChangedV1) GetValidUntil() string {
	if x != nil {
		return x.ValidUntil
	}
	return ""
}

var File_controlplane_storage_commercial_admission_proto protoreflect.FileDescriptor

const file_controlplane_storage_commercial_admission_proto_rawDesc = "" +
	"\n" +
	"/controlplane/storage/commercial_admission.proto\x12!controlplane.storage.admission.v1\"\xa9\x02\n" +
	"\x1cCommercialAdmissionChangedV1\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x1d\n" +
	"\n" +
	"owner_type\x18\x03 \x01(\tR\townerType\x12%\n" +
	"\x0epolicy_version\x18\x04 \x01(\x03R\rpolicyVersion\x12\x1a\n" +
	"\bdecision\x18\x05 \x01(\tR\bdecision\x12-\n" +
	"\x12restriction_reason\x18\x06 \x01(\tR\x11restrictionReason\x12!\n" +
	"\feffective_at\x18\a \x01(\tR\veffectiveAt\x12\x1f\n" +
	"\vvalid_until\x18\b \x01(\tR\n" +
	"validUntilB<Z:controlplane/internal/storage/transport/proto;storageprotob\x06proto3"

var (
	file_controlplane_storage_commercial_admission_proto_rawDescOnce sync.Once
	file_controlplane_storage_commercial_admission_proto_rawDescData []byte
)

func file_controlplane_storage_commercial_admission_proto_rawDescGZIP() []byte {
	file_controlplane_storage_commercial_admission_proto_rawDescOnce.Do(func() {
		file_controlplane_storage_commercial_admission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_controlplane_storage_commercial_admission_proto_rawDesc), len(file_controlplane_storage_commercial_admission_proto_rawDesc)))
	})
	return file_controlplane_storage_commercial_admission_proto_rawDescData
}

var file_controlplane_storage_commercial_admission_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_controlplane_storage_commercial_admission_proto_goTypes = []any{
	(*CommercialAdmissionChangedV1)(nil), // 0: controlplane.storage.admission.v1.CommercialAdmissionChangedV1
}
var file_controlplane_storage_commercial_admission_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_controlplane_storage_commercial_admission_proto_init() }
func file_controlplane_storage_commercial_admission_proto_init() {
	if File_controlplane_storage_commercial_admission_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controlplane_storage_commercial_admission_proto_rawDesc), len(file_controlplane_storage_commercial_admission_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_controlplane_storage_commercial_admission_proto_goTypes,
		DependencyIndexes: file_controlplane_storage_commercial_admission_proto_depIdxs,
		MessageInfos:      file_controlplane_storage_commercial_admission_proto_msgTypes,
	}.Build()
	File_controlplane_storage_commercial_admission_proto = out.File
	file_controlplane_storage_commercial_admission_proto_goTypes = nil
	file_controlplane_storage_commercial_admission_proto_depIdxs = nil
}
