// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: internal/mail/proto/mail_job.proto

package mailproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Cấu hình kiểm tra kết nối SMTP gửi từ Controlplane sang Dataplane
type SmtpTestConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	TlsMode       string                 `protobuf:"bytes,5,opt,name=tls_mode,json=tlsMode,proto3" json:"tls_mode,omitempty"`
	CaCertPem     *string                `protobuf:"bytes,6,opt,name=ca_cert_pem,json=caCertPem,proto3,oneof" json:"ca_cert_pem,omitempty"`
	ClientCertPem *string                `protobuf:"bytes,7,opt,name=client_cert_pem,json=clientCertPem,proto3,oneof" json:"client_cert_pem,omitempty"`
	ClientKeyPem  *string                `protobuf:"bytes,8,opt,name=client_key_pem,json=clientKeyPem,proto3,oneof" json:"client_key_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SmtpTestConfig) Reset() {
	*x = SmtpTestConfig{}
	mi := &file_internal_mail_proto_mail_job_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmtpTestConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmtpTestConfig) ProtoMessage() {}

func (x *SmtpTestConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_mail_proto_mail_job_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmtpTestConfig.ProtoReflect.Descriptor instead.
func (*SmtpTestConfig) Descriptor() ([]byte, []int) {
	return file_internal_mail_proto_mail_job_proto_rawDescGZIP(), []int{0}
}

func (x *SmtpTestConfig) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *SmtpTestConfig) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *SmtpTestConfig) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SmtpTestConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SmtpTestConfig) GetTlsMode() string {
	if x != nil {
		return x.TlsMode
	}
	return ""
}

func (x *SmtpTestConfig) GetCaCertPem() string {
	if x != nil && x.CaCertPem != nil {
		return *x.CaCertPem
	}
	return ""
}

func (x *SmtpTestConfig) GetClientCertPem() string {
	if x != nil && x.ClientCertPem != nil {
		return *x.ClientCertPem
	}
	return ""
}

func (x *SmtpTestConfig) GetClientKeyPem() string {
	if x != nil && x.ClientKeyPem != nil {
		return *x.ClientKeyPem
	}
	return ""
}

var File_internal_mail_proto_mail_job_proto protoreflect.FileDescriptor

const file_internal_mail_proto_mail_job_proto_rawDesc = "" +
	"\n" +
	"\"internal/mail/proto/mail_job.proto\x12\x04mail\"\xbf\x02\n" +
	"\x0eSmtpTestConfig\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x19\n" +
	"\btls_mode\x18\x05 \x01(\tR\atlsMode\x12#\n" +
	"\vca_cert_pem\x18\x06 \x01(\tH\x00R\tcaCertPem\x88\x01\x01\x12+\n" +
	"\x0fclient_cert_pem\x18\a \x01(\tH\x01R\rclientCertPem\x88\x01\x01\x12)\n" +
	"\x0eclient_key_pem\x18\b \x01(\tH\x02R\fclientKeyPem\x88\x01\x01B\x0e\n" +
	"\f_ca_cert_pemB\x12\n" +
	"\x10_client_cert_pemB\x11\n" +
	"\x0f_client_key_pemB,Z*controlplane/internal/mail/proto;mailprotob\x06proto3"

var (
	file_internal_mail_proto_mail_job_proto_rawDescOnce sync.Once
	file_internal_mail_proto_mail_job_proto_rawDescData []byte
)

func file_internal_mail_proto_mail_job_proto_rawDescGZIP() []byte {
	file_internal_mail_proto_mail_job_proto_rawDescOnce.Do(func() {
		file_internal_mail_proto_mail_job_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_mail_proto_mail_job_proto_rawDesc), len(file_internal_mail_proto_mail_job_proto_rawDesc)))
	})
	return file_internal_mail_proto_mail_job_proto_rawDescData
}

var file_internal_mail_proto_mail_job_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_mail_proto_mail_job_proto_goTypes = []any{
	(*SmtpTestConfig)(nil), // 0: mail.SmtpTestConfig
}
var file_internal_mail_proto_mail_job_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_mail_proto_mail_job_proto_init() }
func file_internal_mail_proto_mail_job_proto_init() {
	if File_internal_mail_proto_mail_job_proto != nil {
		return
	}
	file_internal_mail_proto_mail_job_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_mail_proto_mail_job_proto_rawDesc), len(file_internal_mail_proto_mail_job_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_mail_proto_mail_job_proto_goTypes,
		DependencyIndexes: file_internal_mail_proto_mail_job_proto_depIdxs,
		MessageInfos:      file_internal_mail_proto_mail_job_proto_msgTypes,
	}.Build()
	File_internal_mail_proto_mail_job_proto = out.File
	file_internal_mail_proto_mail_job_proto_goTypes = nil
	file_internal_mail_proto_mail_job_proto_depIdxs = nil
}
