// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: cost-manager/api/billing/pricing/hypervisor/v1/hypervisor_pricing_snapshot.proto

package hypervisorpricingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HypervisorPricingSnapshotCacheEntryV1 struct {
	state                  protoimpl.MessageState              `protogen:"open.v1"`
	PricingScheduleId      []byte                              `protobuf:"bytes,1,opt,name=pricing_schedule_id,json=pricingScheduleId,proto3" json:"pricing_schedule_id,omitempty"`
	VersionId              []byte                              `protobuf:"bytes,2,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	Code                   string                              `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	ChargeKindCode         string                              `protobuf:"bytes,4,opt,name=charge_kind_code,json=chargeKindCode,proto3" json:"charge_kind_code,omitempty"`
	Currency               string                              `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	VersionNumber          int32                               `protobuf:"varint,6,opt,name=version_number,json=versionNumber,proto3" json:"version_number,omitempty"`
	EffectiveFromUnixMicro int64                               `protobuf:"varint,7,opt,name=effective_from_unix_micro,json=effectiveFromUnixMicro,proto3" json:"effective_from_unix_micro,omitempty"`
	EffectiveToUnixMicro   *int64                              `protobuf:"varint,8,opt,name=effective_to_unix_micro,json=effectiveToUnixMicro,proto3,oneof" json:"effective_to_unix_micro,omitempty"`
	ChecksumSha256         []byte                              `protobuf:"bytes,9,opt,name=checksum_sha256,json=checksumSha256,proto3" json:"checksum_sha256,omitempty"`
	Brackets               []*HypervisorPricingScalarBracketV1 `protobuf:"bytes,10,rep,name=brackets,proto3" json:"brackets,omitempty"`
	RawInputUnit           string                              `protobuf:"bytes,11,opt,name=raw_input_unit,json=rawInputUnit,proto3" json:"raw_input_unit,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *HypervisorPricingSnapshotCacheEntryV1) Reset() {
	*x = HypervisorPricingSnapshotCacheEntryV1{}
	mi := &file_cost_manager_api_billing_pricing_hypervisor_v1_hypervisor_pricing_snapshot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HypervisorPricingSnapshotCacheEntryV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HypervisorPricingSnapshotCacheEntryV1) ProtoMessage() {}

func (x *HypervisorPricingSnapshotCacheEntryV1) ProtoReflect() protoreflect.Message {
	mi := &file_cost_manager_api_billing_pricing_hypervisor_v1_hypervisor_pricing_snapshot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HypervisorPricingSnapshotCacheEntryV1.ProtoReflect.Descriptor instead.
func (*HypervisorPricingSnapshotCacheEntryV1) Descriptor() ([]byte, []int) {
	return file_cost_manager_api_billing_pricing_hypervisor_v1_hypervisor_pricing_snapshot_proto_rawDescGZIP(), []int{0}
}

func (x *HypervisorPricingSnapshotCacheEntryV1) GetPricingScheduleId() []byte {
	if x != nil {
		return x.PricingScheduleId
	}
	return nil
}

func (x *HypervisorPricingSnapshotCacheEntryV1) GetVersionId() []byte {
	if x != nil {
		return x.VersionId
	}
	return nil
}

func (x *HypervisorPricingSnapshotCacheEntryV1) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *HypervisorPricingSnapshotCacheEntryV1) GetChargeKindCode() string {
	if x != nil {
		return x.ChargeKindCode
	}
	return ""
}

func (x *HypervisorPricingSnapshotCacheEntryV1) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *HypervisorPricingSnapshotCacheEntryV1) GetVersionNumber() int32 {
	if x != nil {
		return x.VersionNumber
	}
	return 0
}

func (x *HypervisorPricingSnapshotCacheEntryV1) GetEffectiveFromUnixMicro() int64 {
	if x != nil {
		return x.EffectiveFromUnixMicro
	}
	return 0
}

func (x *HypervisorPricingSnapshotCacheEntryV1) GetEffectiveToUnixMicro() int64 {
	if x != nil && x.EffectiveToUnixMicro != nil {
		return *x.EffectiveToUnixMicro
	}
	return 0
}

func (x *HypervisorPricingSnapshotCacheEntryV1) GetChecksumSha256() []byte {
	if x != nil {
		return x.ChecksumSha256
	}
	return nil
}

func (x *HypervisorPricingSnapshotCacheEntryV1) GetBrackets() []*HypervisorPricingScalarBracketV1 {
	if x != nil {
		return x.Brackets
	}
	return nil
}

func (x *HypervisorPricingSnapshotCacheEntryV1) GetRawInputUnit() string {
	if x != nil {
		return x.RawInputUnit
	}
	return ""
}

type HypervisorPricingScalarBracketV1 struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	RangeStartQuantity       int64                  `protobuf:"varint,1,opt,name=range_start_quantity,json=rangeStartQuantity,proto3" json:"range_start_quantity,omitempty"`
	RangeEndQuantity         *int64                 `protobuf:"varint,2,opt,name=range_end_quantity,json=rangeEndQuantity,proto3,oneof" json:"range_end_quantity,omitempty"`
	PriceNumeratorMicroUnits int64                  `protobuf:"varint,3,opt,name=price_numerator_micro_units,json=priceNumeratorMicroUnits,proto3" json:"price_numerator_micro_units,omitempty"`
	PriceDenominatorQuantity int64                  `protobuf:"varint,4,opt,name=price_denominator_quantity,json=priceDenominatorQuantity,proto3" json:"price_denominator_quantity,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *HypervisorPricingScalarBracketV1) Reset() {
	*x = HypervisorPricingScalarBracketV1{}
	mi := &file_cost_manager_api_billing_pricing_hypervisor_v1_hypervisor_pricing_snapshot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HypervisorPricingScalarBracketV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HypervisorPricingScalarBracketV1) ProtoMessage() {}

func (x *HypervisorPricingScalarBracketV1) ProtoReflect() protoreflect.Message {
	mi := &file_cost_manager_api_billing_pricing_hypervisor_v1_hypervisor_pricing_snapshot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HypervisorPricingScalarBracketV1.ProtoReflect.Descriptor instead.
func (*HypervisorPricingScalarBracketV1) Descriptor() ([]byte, []int) {
	return file_cost_manager_api_billing_pricing_hypervisor_v1_hypervisor_pricing_snapshot_proto_rawDescGZIP(), []int{1}
}

func (x *HypervisorPricingScalarBracketV1) GetRangeStartQuantity() int64 {
	if x != nil {
		return x.RangeStartQuantity
	}
	return 0
}

func (x *HypervisorPricingScalarBracketV1) GetRangeEndQuantity() int64 {
	if x != nil && x.RangeEndQuantity != nil {
		return *x.RangeEndQuantity
	}
	return 0
}

func (x *HypervisorPricingScalarBracketV1) GetPriceNumeratorMicroUnits() int64 {
	if x != nil {
		return x.PriceNumeratorMicroUnits
	}
	return 0
}

func (x *HypervisorPricingScalarBracketV1) GetPriceDenominatorQuantity() int64 {
	if x != nil {
		return x.PriceDenominatorQuantity
	}
	return 0
}

var File_cost_manager_api_billing_pricing_hypervisor_v1_hypervisor_pricing_snapshot_proto protoreflect.FileDescriptor

const file_cost_manager_api_billing_pricing_hypervisor_v1_hypervisor_pricing_snapshot_proto_rawDesc = "" +
	"\n" +
	"Pcost-manager/api/billing/pricing/hypervisor/v1/hypervisor_pricing_snapshot.proto\x12-costmanager.api.billing.pricing.hypervisor.v1\"\xc6\x04\n" +
	"%HypervisorPricingSnapshotCacheEntryV1\x12.\n" +
	"\x13pricing_schedule_id\x18\x01 \x01(\fR\x11pricingScheduleId\x12\x1d\n" +
	"\n" +
	"version_id\x18\x02 \x01(\fR\tversionId\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12(\n" +
	"\x10charge_kind_code\x18\x04 \x01(\tR\x0echargeKindCode\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12%\n" +
	"\x0eversion_number\x18\x06 \x01(\x05R\rversionNumber\x129\n" +
	"\x19effective_from_unix_micro\x18\a \x01(\x03R\x16effectiveFromUnixMicro\x12:\n" +
	"\x17effective_to_unix_micro\x18\b \x01(\x03H\x00R\x14effectiveToUnixMicro\x88\x01\x01\x12'\n" +
	"\x0fchecksum_sha256\x18\t \x01(\fR\x0echecksumSha256\x12k\n" +
	"\bbrackets\x18\n" +
	" \x03(\v2O.costmanager.api.billing.pricing.hypervisor.v1.HypervisorPricingScalarBracketV1R\bbrackets\x12$\n" +
	"\x0eraw_input_unit\x18\v \x01(\tR\frawInputUnitB\x1a\n" +
	"\x18_effective_to_unix_micro\"\x9b\x02\n" +
	" HypervisorPricingScalarBracketV1\x120\n" +
	"\x14range_start_quantity\x18\x01 \x01(\x03R\x12rangeStartQuantity\x121\n" +
	"\x12range_end_quantity\x18\x02 \x01(\x03H\x00R\x10rangeEndQuantity\x88\x01\x01\x12=\n" +
	"\x1bprice_numerator_micro_units\x18\x03 \x01(\x03R\x18priceNumeratorMicroUnits\x12<\n" +
	"\x1aprice_denominator_quantity\x18\x04 \x01(\x03R\x18priceDenominatorQuantityB\x15\n" +
	"\x13_range_end_quantityBVZTcost-manager/api/internal/genproto/billing/pricing/hypervisor/v1;hypervisorpricingv1b\x06proto3"

var (
	file_cost_manager_api_billing_pricing_hypervisor_v1_hypervisor_pricing_snapshot_proto_rawDescOnce sync.Once
	file_cost_manager_api_billing_pricing_hypervisor_v1_hypervisor_pricing_snapshot_proto_rawDescData []byte
)

func file_cost_manager_api_billing_pricing_hypervisor_v1_hypervisor_pricing_snapshot_proto_rawDescGZIP() []byte {
	file_cost_manager_api_billing_pricing_hypervisor_v1_hypervisor_pricing_snapshot_proto_rawDescOnce.Do(func() {
		file_cost_manager_api_billing_pricing_hypervisor_v1_hypervisor_pricing_snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cost_manager_api_billing_pricing_hypervisor_v1_hypervisor_pricing_snapshot_proto_rawDesc), len(file_cost_manager_api_billing_pricing_hypervisor_v1_hypervisor_pricing_snapshot_proto_rawDesc)))
	})
	return file_cost_manager_api_billing_pricing_hypervisor_v1_hypervisor_pricing_snapshot_proto_rawDescData
}

var file_cost_manager_api_billing_pricing_hypervisor_v1_hypervisor_pricing_snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cost_manager_api_billing_pricing_hypervisor_v1_hypervisor_pricing_snapshot_proto_goTypes = []any{
	(*HypervisorPricingSnapshotCacheEntryV1)(nil), // 0: costmanager.api.billing.pricing.hypervisor.v1.HypervisorPricingSnapshotCacheEntryV1
	(*HypervisorPricingScalarBracketV1)(nil),      // 1: costmanager.api.billing.pricing.hypervisor.v1.HypervisorPricingScalarBracketV1
}
var file_cost_manager_api_billing_pricing_hypervisor_v1_hypervisor_pricing_snapshot_proto_depIdxs = []int32{
	1, // 0: costmanager.api.billing.pricing.hypervisor.v1.HypervisorPricingSnapshotCacheEntryV1.brackets:type_name -> costmanager.api.billing.pricing.hypervisor.v1.HypervisorPricingScalarBracketV1
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() {
	file_cost_manager_api_billing_pricing_hypervisor_v1_hypervisor_pricing_snapshot_proto_init()
}
func file_cost_manager_api_billing_pricing_hypervisor_v1_hypervisor_pricing_snapshot_proto_init() {
	if File_cost_manager_api_billing_pricing_hypervisor_v1_hypervisor_pricing_snapshot_proto != nil {
		return
	}
	file_cost_manager_api_billing_pricing_hypervisor_v1_hypervisor_pricing_snapshot_proto_msgTypes[0].OneofWrappers = []any{}
	file_cost_manager_api_billing_pricing_hypervisor_v1_hypervisor_pricing_snapshot_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cost_manager_api_billing_pricing_hypervisor_v1_hypervisor_pricing_snapshot_proto_rawDesc), len(file_cost_manager_api_billing_pricing_hypervisor_v1_hypervisor_pricing_snapshot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cost_manager_api_billing_pricing_hypervisor_v1_hypervisor_pricing_snapshot_proto_goTypes,
		DependencyIndexes: file_cost_manager_api_billing_pricing_hypervisor_v1_hypervisor_pricing_snapshot_proto_depIdxs,
		MessageInfos:      file_cost_manager_api_billing_pricing_hypervisor_v1_hypervisor_pricing_snapshot_proto_msgTypes,
	}.Build()
	File_cost_manager_api_billing_pricing_hypervisor_v1_hypervisor_pricing_snapshot_proto = out.File
	file_cost_manager_api_billing_pricing_hypervisor_v1_hypervisor_pricing_snapshot_proto_goTypes = nil
	file_cost_manager_api_billing_pricing_hypervisor_v1_hypervisor_pricing_snapshot_proto_depIdxs = nil
}
