package iamTaxonomy

import "errors"

// Generic errors for workflow results and core logic
var (
	ErrNotFound              = errors.New("iam: not found")
	ErrPreconditionFailed    = errors.New("iam: precondition failed")
	ErrActionNotAllowed      = errors.New("iam: action not allowed")
	ErrGenTOTPFailed         = errors.New("iam: generate totp failed")
	ErrEncryptSecretFailed   = errors.New("iam: encrypt secret failed")
	ErrGenRecoveryCodeFailed = errors.New("iam: generate recovery code failed")
	ErrInvalidCredential     = errors.New("iam: invalid credential")
	ErrRecoveryCodeInvalid   = errors.New("iam: recovery code invalid or consumed")
	ErrTokenIssueFailed      = errors.New("iam: token issue failed")
	ErrUuidGenerateFailed    = errors.New("iam: uuid generate failed")

	ErrDeviceBindingFailed = errors.New("iam: device binding failed")
	ErrDeviceRevoked       = errors.New("iam: device revoked")
	ErrDeviceQuarantined   = errors.New("iam: device quarantined")
	ErrMFAInvalid          = errors.New("iam: mfa invalid")
	ErrMFAColdDown         = errors.New("iam: mfa cooldown")

	ErrTokenSecretInvalid       = errors.New("iam: token secret invalid")
	ErrTokenIDInvalid           = errors.New("iam: token id invalid")
	ErrTokenAccessInvalid       = errors.New("iam: token access invalid")
	ErrTokenRefreshInvalid      = errors.New("iam: token refresh invalid")
	ErrTokenAccessExpired       = errors.New("iam: token access expired")
	ErrTokenRefreshExpired      = errors.New("iam: token refresh expired")
	ErrTokenAccessInactive      = errors.New("iam: token access inactive")
	ErrTokenRefreshInactive     = errors.New("iam: token refresh inactive")
	ErrTokenSecretInactive      = errors.New("iam: token secret inactive")
	ErrTokenNotFound            = errors.New("iam: token not found")
	ErrGetL1CacheFailed         = errors.New("iam cache l1: get failed")
	ErrGetL2CacheFailed         = errors.New("iam cache l2: get failed")
	ErrTokenUpdateFailed        = errors.New("iam: token update failed")
	ErrTokenRevokeFailed        = errors.New("iam: token revoke failed")
	ErrTokenRevokeAuditFailed   = errors.New("iam: token revoke audit failed")
	ErrTokenSecretRotateFailed  = errors.New("iam: token secret rotate failed")
	ErrTokenRefreshRotateFailed = errors.New("iam: token refresh rotate failed")
	ErrSetAccessSessionFailed   = errors.New("iam: set access session failed")
	ErrZoneUnavailable          = errors.New("iam: zone unavailable")

	ErrInvalidArgument           = errors.New("iam: invalid argument")
	ErrInvalidEmail              = errors.New("iam: invalid email")
	ErrInvalidUsername           = errors.New("iam: invalid username")
	ErrPasswordMismatch          = errors.New("iam: password mismatch")
	ErrWeakPassword              = errors.New("iam: weak password")
	ErrUserAlreadyExist          = errors.New("iam: user already exists")
	ErrUserNotFound              = errors.New("iam: user not found")
	ErrInvalidCredentials        = errors.New("iam: invalid credentials")
	ErrVerificationRequired      = errors.New("iam: verification required")
	ErrAuthenticationUnavailable = errors.New("iam: authentication unavailable")
	ErrInvalidSession            = errors.New("iam: invalid session")
	ErrUserAccessSessionInvalid  = errors.New("iam cache: invalid user access session")

	ErrRoleNotFound       = errors.New("iam: role not found")
	ErrPermissionNotFound = errors.New("iam: permission not found")
	ErrRoleRequired       = errors.New("iam: role required")
)

var (
	ErrInternalError    = errors.New("iam: internal error")
	ErrLockAlreadyHeld  = errors.New("iam: lock already held")
	ErrZeroRowsAffected = errors.New("iam: zero rows affected")
)
