// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: internal/hierarchy/transport/rpc/proto/backpressure.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReportBackpressureRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ZoneId         string                 `protobuf:"bytes,1,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	QueueLen       int64                  `protobuf:"varint,2,opt,name=queue_len,json=queueLen,proto3" json:"queue_len,omitempty"`
	PendingLen     int64                  `protobuf:"varint,3,opt,name=pending_len,json=pendingLen,proto3" json:"pending_len,omitempty"`
	Congested      bool                   `protobuf:"varint,4,opt,name=congested,proto3" json:"congested,omitempty"`
	Epoch          int64                  `protobuf:"varint,5,opt,name=epoch,proto3" json:"epoch,omitempty"`
	CongestionRate float64                `protobuf:"fixed64,6,opt,name=congestion_rate,json=congestionRate,proto3" json:"congestion_rate,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReportBackpressureRequest) Reset() {
	*x = ReportBackpressureRequest{}
	mi := &file_internal_hierarchy_transport_rpc_proto_backpressure_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportBackpressureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportBackpressureRequest) ProtoMessage() {}

func (x *ReportBackpressureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_hierarchy_transport_rpc_proto_backpressure_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportBackpressureRequest.ProtoReflect.Descriptor instead.
func (*ReportBackpressureRequest) Descriptor() ([]byte, []int) {
	return file_internal_hierarchy_transport_rpc_proto_backpressure_proto_rawDescGZIP(), []int{0}
}

func (x *ReportBackpressureRequest) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *ReportBackpressureRequest) GetQueueLen() int64 {
	if x != nil {
		return x.QueueLen
	}
	return 0
}

func (x *ReportBackpressureRequest) GetPendingLen() int64 {
	if x != nil {
		return x.PendingLen
	}
	return 0
}

func (x *ReportBackpressureRequest) GetCongested() bool {
	if x != nil {
		return x.Congested
	}
	return false
}

func (x *ReportBackpressureRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *ReportBackpressureRequest) GetCongestionRate() float64 {
	if x != nil {
		return x.CongestionRate
	}
	return 0
}

type ReportBackpressureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportBackpressureResponse) Reset() {
	*x = ReportBackpressureResponse{}
	mi := &file_internal_hierarchy_transport_rpc_proto_backpressure_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportBackpressureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportBackpressureResponse) ProtoMessage() {}

func (x *ReportBackpressureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_hierarchy_transport_rpc_proto_backpressure_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportBackpressureResponse.ProtoReflect.Descriptor instead.
func (*ReportBackpressureResponse) Descriptor() ([]byte, []int) {
	return file_internal_hierarchy_transport_rpc_proto_backpressure_proto_rawDescGZIP(), []int{1}
}

func (x *ReportBackpressureResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_internal_hierarchy_transport_rpc_proto_backpressure_proto protoreflect.FileDescriptor

const file_internal_hierarchy_transport_rpc_proto_backpressure_proto_rawDesc = "" +
	"\n" +
	"9internal/hierarchy/transport/rpc/proto/backpressure.proto\x12\bcore.rpc\"\xcf\x01\n" +
	"\x19ReportBackpressureRequest\x12\x17\n" +
	"\azone_id\x18\x01 \x01(\tR\x06zoneId\x12\x1b\n" +
	"\tqueue_len\x18\x02 \x01(\x03R\bqueueLen\x12\x1f\n" +
	"\vpending_len\x18\x03 \x01(\x03R\n" +
	"pendingLen\x12\x1c\n" +
	"\tcongested\x18\x04 \x01(\bR\tcongested\x12\x14\n" +
	"\x05epoch\x18\x05 \x01(\x03R\x05epoch\x12'\n" +
	"\x0fcongestion_rate\x18\x06 \x01(\x01R\x0econgestionRate\"6\n" +
	"\x1aReportBackpressureResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2v\n" +
	"\x13BackpressureService\x12_\n" +
	"\x12ReportBackpressure\x12#.core.rpc.ReportBackpressureRequest\x1a$.core.rpc.ReportBackpressureResponseB5Z3controlplane/internal/hierarchy/transport/rpc/protob\x06proto3"

var (
	file_internal_hierarchy_transport_rpc_proto_backpressure_proto_rawDescOnce sync.Once
	file_internal_hierarchy_transport_rpc_proto_backpressure_proto_rawDescData []byte
)

func file_internal_hierarchy_transport_rpc_proto_backpressure_proto_rawDescGZIP() []byte {
	file_internal_hierarchy_transport_rpc_proto_backpressure_proto_rawDescOnce.Do(func() {
		file_internal_hierarchy_transport_rpc_proto_backpressure_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_hierarchy_transport_rpc_proto_backpressure_proto_rawDesc), len(file_internal_hierarchy_transport_rpc_proto_backpressure_proto_rawDesc)))
	})
	return file_internal_hierarchy_transport_rpc_proto_backpressure_proto_rawDescData
}

var file_internal_hierarchy_transport_rpc_proto_backpressure_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_hierarchy_transport_rpc_proto_backpressure_proto_goTypes = []any{
	(*ReportBackpressureRequest)(nil),  // 0: core.rpc.ReportBackpressureRequest
	(*ReportBackpressureResponse)(nil), // 1: core.rpc.ReportBackpressureResponse
}
var file_internal_hierarchy_transport_rpc_proto_backpressure_proto_depIdxs = []int32{
	0, // 0: core.rpc.BackpressureService.ReportBackpressure:input_type -> core.rpc.ReportBackpressureRequest
	1, // 1: core.rpc.BackpressureService.ReportBackpressure:output_type -> core.rpc.ReportBackpressureResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_hierarchy_transport_rpc_proto_backpressure_proto_init() }
func file_internal_hierarchy_transport_rpc_proto_backpressure_proto_init() {
	if File_internal_hierarchy_transport_rpc_proto_backpressure_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_hierarchy_transport_rpc_proto_backpressure_proto_rawDesc), len(file_internal_hierarchy_transport_rpc_proto_backpressure_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_hierarchy_transport_rpc_proto_backpressure_proto_goTypes,
		DependencyIndexes: file_internal_hierarchy_transport_rpc_proto_backpressure_proto_depIdxs,
		MessageInfos:      file_internal_hierarchy_transport_rpc_proto_backpressure_proto_msgTypes,
	}.Build()
	File_internal_hierarchy_transport_rpc_proto_backpressure_proto = out.File
	file_internal_hierarchy_transport_rpc_proto_backpressure_proto_goTypes = nil
	file_internal_hierarchy_transport_rpc_proto_backpressure_proto_depIdxs = nil
}
