apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: Loki
    orgId: 1
  - name: Tempo
    orgId: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: false
    # Cấu hình derivedFields để liên kết tự động Log với Trace của Tempo
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "(?:trace_id|traceID|traceId|trace)[=:\\s\"]+([a-fA-F0-9]{32})"
          name: TraceID
          url: '$${__value.raw}'

  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: false
