// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: internal/transport/proto/billing_auth.proto

package proto


import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerifyBillingCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeCode  string                 `protobuf:"bytes,1,opt,name=employee_code,json=employeeCode,proto3" json:"employee_code,omitempty"`
	SecretKey     string                 `protobuf:"bytes,2,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyBillingCredentialsRequest) Reset() {
	*x = VerifyBillingCredentialsRequest{}
	mi := &file_internal_transport_proto_billing_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyBillingCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyBillingCredentialsRequest) ProtoMessage() {}

func (x *VerifyBillingCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_billing_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyBillingCredentialsRequest.ProtoReflect.Descriptor instead.
func (*VerifyBillingCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_billing_auth_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyBillingCredentialsRequest) GetEmployeeCode() string {
	if x != nil {
		return x.EmployeeCode
	}
	return ""
}

func (x *VerifyBillingCredentialsRequest) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

type VerifyBillingCredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleId        string                 `protobuf:"bytes,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	Level         int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	EmployeeCode  string                 `protobuf:"bytes,6,opt,name=employee_code,json=employeeCode,proto3" json:"employee_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyBillingCredentialsResponse) Reset() {
	*x = VerifyBillingCredentialsResponse{}
	mi := &file_internal_transport_proto_billing_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyBillingCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyBillingCredentialsResponse) ProtoMessage() {}

func (x *VerifyBillingCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_billing_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyBillingCredentialsResponse.ProtoReflect.Descriptor instead.
func (*VerifyBillingCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_billing_auth_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyBillingCredentialsResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyBillingCredentialsResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VerifyBillingCredentialsResponse) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *VerifyBillingCredentialsResponse) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *VerifyBillingCredentialsResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *VerifyBillingCredentialsResponse) GetEmployeeCode() string {
	if x != nil {
		return x.EmployeeCode
	}
	return ""
}

var File_internal_transport_proto_billing_auth_proto protoreflect.FileDescriptor

const file_internal_transport_proto_billing_auth_proto_rawDesc = "" +
	"\n" +
	"+internal/transport/proto/billing_auth.proto\x12\vbilling.rpc\"e\n" +
	"\x1fVerifyBillingCredentialsRequest\x12#\n" +
	"\remployee_code\x18\x01 \x01(\tR\femployeeCode\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x02 \x01(\tR\tsecretKey\"\xca\x01\n" +
	" VerifyBillingCredentialsResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\arole_id\x18\x03 \x01(\tR\x06roleId\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12#\n" +
	"\remployee_code\x18\x06 \x01(\tR\femployeeCodeB\x14Z\x12./billingauthprotob\x06proto3"

var (
	file_internal_transport_proto_billing_auth_proto_rawDescOnce sync.Once
	file_internal_transport_proto_billing_auth_proto_rawDescData []byte
)

func file_internal_transport_proto_billing_auth_proto_rawDescGZIP() []byte {
	file_internal_transport_proto_billing_auth_proto_rawDescOnce.Do(func() {
		file_internal_transport_proto_billing_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_transport_proto_billing_auth_proto_rawDesc), len(file_internal_transport_proto_billing_auth_proto_rawDesc)))
	})
	return file_internal_transport_proto_billing_auth_proto_rawDescData
}

var file_internal_transport_proto_billing_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_transport_proto_billing_auth_proto_goTypes = []any{
	(*VerifyBillingCredentialsRequest)(nil),  // 0: billing.rpc.VerifyBillingCredentialsRequest
	(*VerifyBillingCredentialsResponse)(nil), // 1: billing.rpc.VerifyBillingCredentialsResponse
}
var file_internal_transport_proto_billing_auth_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_transport_proto_billing_auth_proto_init() }
func file_internal_transport_proto_billing_auth_proto_init() {
	if File_internal_transport_proto_billing_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_transport_proto_billing_auth_proto_rawDesc), len(file_internal_transport_proto_billing_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_transport_proto_billing_auth_proto_goTypes,
		DependencyIndexes: file_internal_transport_proto_billing_auth_proto_depIdxs,
		MessageInfos:      file_internal_transport_proto_billing_auth_proto_msgTypes,
	}.Build()
	File_internal_transport_proto_billing_auth_proto = out.File
	file_internal_transport_proto_billing_auth_proto_goTypes = nil
	file_internal_transport_proto_billing_auth_proto_depIdxs = nil
}
