// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: internal/hypervisor/transport/rpc/proto/hypervisor_job.proto

package hypervisorproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VmCreateV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	VmId          []byte                 `protobuf:"bytes,2,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	ProviderName  string                 `protobuf:"bytes,3,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	Image         string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	CpuCores      uint32                 `protobuf:"varint,5,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	MemoryMb      uint64                 `protobuf:"varint,6,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	DiskGb        uint64                 `protobuf:"varint,7,opt,name=disk_gb,json=diskGb,proto3" json:"disk_gb,omitempty"`
	SshPublicKey  string                 `protobuf:"bytes,8,opt,name=ssh_public_key,json=sshPublicKey,proto3" json:"ssh_public_key,omitempty"`
	ConfigHash    []byte                 `protobuf:"bytes,9,opt,name=config_hash,json=configHash,proto3" json:"config_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VmCreateV1) Reset() {
	*x = VmCreateV1{}
	mi := &file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmCreateV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmCreateV1) ProtoMessage() {}

func (x *VmCreateV1) ProtoReflect() protoreflect.Message {
	mi := &file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmCreateV1.ProtoReflect.Descriptor instead.
func (*VmCreateV1) Descriptor() ([]byte, []int) {
	return file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_rawDescGZIP(), []int{0}
}

func (x *VmCreateV1) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *VmCreateV1) GetVmId() []byte {
	if x != nil {
		return x.VmId
	}
	return nil
}

func (x *VmCreateV1) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *VmCreateV1) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *VmCreateV1) GetCpuCores() uint32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *VmCreateV1) GetMemoryMb() uint64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *VmCreateV1) GetDiskGb() uint64 {
	if x != nil {
		return x.DiskGb
	}
	return 0
}

func (x *VmCreateV1) GetSshPublicKey() string {
	if x != nil {
		return x.SshPublicKey
	}
	return ""
}

func (x *VmCreateV1) GetConfigHash() []byte {
	if x != nil {
		return x.ConfigHash
	}
	return nil
}

type VmCreateResultV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	VmId          []byte                 `protobuf:"bytes,2,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	ProviderName  string                 `protobuf:"bytes,3,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	ProviderNode  string                 `protobuf:"bytes,4,opt,name=provider_node,json=providerNode,proto3" json:"provider_node,omitempty"`
	ProviderVmid  uint64                 `protobuf:"varint,5,opt,name=provider_vmid,json=providerVmid,proto3" json:"provider_vmid,omitempty"`
	Ipv4Address   string                 `protobuf:"bytes,6,opt,name=ipv4_address,json=ipv4Address,proto3" json:"ipv4_address,omitempty"`
	ConfigHash    []byte                 `protobuf:"bytes,7,opt,name=config_hash,json=configHash,proto3" json:"config_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VmCreateResultV1) Reset() {
	*x = VmCreateResultV1{}
	mi := &file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmCreateResultV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmCreateResultV1) ProtoMessage() {}

func (x *VmCreateResultV1) ProtoReflect() protoreflect.Message {
	mi := &file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmCreateResultV1.ProtoReflect.Descriptor instead.
func (*VmCreateResultV1) Descriptor() ([]byte, []int) {
	return file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_rawDescGZIP(), []int{1}
}

func (x *VmCreateResultV1) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *VmCreateResultV1) GetVmId() []byte {
	if x != nil {
		return x.VmId
	}
	return nil
}

func (x *VmCreateResultV1) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *VmCreateResultV1) GetProviderNode() string {
	if x != nil {
		return x.ProviderNode
	}
	return ""
}

func (x *VmCreateResultV1) GetProviderVmid() uint64 {
	if x != nil {
		return x.ProviderVmid
	}
	return 0
}

func (x *VmCreateResultV1) GetIpv4Address() string {
	if x != nil {
		return x.Ipv4Address
	}
	return ""
}

func (x *VmCreateResultV1) GetConfigHash() []byte {
	if x != nil {
		return x.ConfigHash
	}
	return nil
}

var File_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto protoreflect.FileDescriptor

const file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_rawDesc = "" +
	"\n" +
	"<internal/hypervisor/transport/rpc/proto/hypervisor_job.proto\x12\n" +
	"hypervisor\"\x9d\x02\n" +
	"\n" +
	"VmCreateV1\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x13\n" +
	"\x05vm_id\x18\x02 \x01(\fR\x04vmId\x12#\n" +
	"\rprovider_name\x18\x03 \x01(\tR\fproviderName\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\x12\x1b\n" +
	"\tcpu_cores\x18\x05 \x01(\rR\bcpuCores\x12\x1b\n" +
	"\tmemory_mb\x18\x06 \x01(\x04R\bmemoryMb\x12\x17\n" +
	"\adisk_gb\x18\a \x01(\x04R\x06diskGb\x12$\n" +
	"\x0essh_public_key\x18\b \x01(\tR\fsshPublicKey\x12\x1f\n" +
	"\vconfig_hash\x18\t \x01(\fR\n" +
	"configHash\"\x81\x02\n" +
	"\x10VmCreateResultV1\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x13\n" +
	"\x05vm_id\x18\x02 \x01(\fR\x04vmId\x12#\n" +
	"\rprovider_name\x18\x03 \x01(\tR\fproviderName\x12#\n" +
	"\rprovider_node\x18\x04 \x01(\tR\fproviderNode\x12#\n" +
	"\rprovider_vmid\x18\x05 \x01(\x04R\fproviderVmid\x12!\n" +
	"\fipv4_address\x18\x06 \x01(\tR\vipv4Address\x12\x1f\n" +
	"\vconfig_hash\x18\a \x01(\fR\n" +
	"configHashBFZDcontrolplane/internal/hypervisor/transport/rpc/proto;hypervisorprotob\x06proto3"

var (
	file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_rawDescOnce sync.Once
	file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_rawDescData []byte
)

func file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_rawDescGZIP() []byte {
	file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_rawDescOnce.Do(func() {
		file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_rawDesc), len(file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_rawDesc)))
	})
	return file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_rawDescData
}

var file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_goTypes = []any{
	(*VmCreateV1)(nil),       // 0: hypervisor.VmCreateV1
	(*VmCreateResultV1)(nil), // 1: hypervisor.VmCreateResultV1
}
var file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_init() }
func file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_init() {
	if File_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_rawDesc), len(file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_goTypes,
		DependencyIndexes: file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_depIdxs,
		MessageInfos:      file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_msgTypes,
	}.Build()
	File_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto = out.File
	file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_goTypes = nil
	file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_depIdxs = nil
}
