// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: internal/hypervisor/transport/rpc/proto/hypervisor_job.proto

package hypervisorproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VmCreateV1 struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion        uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	VmId                 []byte                 `protobuf:"bytes,2,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	ProviderName         string                 `protobuf:"bytes,3,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	ImageId              []byte                 `protobuf:"bytes,4,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	CpuCores             uint32                 `protobuf:"varint,5,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	MemoryMb             uint64                 `protobuf:"varint,6,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	DiskGb               uint64                 `protobuf:"varint,7,opt,name=disk_gb,json=diskGb,proto3" json:"disk_gb,omitempty"`
	SshPublicKey         string                 `protobuf:"bytes,8,opt,name=ssh_public_key,json=sshPublicKey,proto3" json:"ssh_public_key,omitempty"`
	ConfigHash           []byte                 `protobuf:"bytes,9,opt,name=config_hash,json=configHash,proto3" json:"config_hash,omitempty"`
	ImageRevision        uint64                 `protobuf:"varint,10,opt,name=image_revision,json=imageRevision,proto3" json:"image_revision,omitempty"`
	ImageSha256          []byte                 `protobuf:"bytes,11,opt,name=image_sha256,json=imageSha256,proto3" json:"image_sha256,omitempty"`
	ProviderTemplateVmid uint64                 `protobuf:"varint,12,opt,name=provider_template_vmid,json=providerTemplateVmid,proto3" json:"provider_template_vmid,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *VmCreateV1) Reset() {
	*x = VmCreateV1{}
	mi := &file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmCreateV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmCreateV1) ProtoMessage() {}

func (x *VmCreateV1) ProtoReflect() protoreflect.Message {
	mi := &file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmCreateV1.ProtoReflect.Descriptor instead.
func (*VmCreateV1) Descriptor() ([]byte, []int) {
	return file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_rawDescGZIP(), []int{0}
}

func (x *VmCreateV1) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *VmCreateV1) GetVmId() []byte {
	if x != nil {
		return x.VmId
	}
	return nil
}

func (x *VmCreateV1) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *VmCreateV1) GetImageId() []byte {
	if x != nil {
		return x.ImageId
	}
	return nil
}

func (x *VmCreateV1) GetCpuCores() uint32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *VmCreateV1) GetMemoryMb() uint64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *VmCreateV1) GetDiskGb() uint64 {
	if x != nil {
		return x.DiskGb
	}
	return 0
}

func (x *VmCreateV1) GetSshPublicKey() string {
	if x != nil {
		return x.SshPublicKey
	}
	return ""
}

func (x *VmCreateV1) GetConfigHash() []byte {
	if x != nil {
		return x.ConfigHash
	}
	return nil
}

func (x *VmCreateV1) GetImageRevision() uint64 {
	if x != nil {
		return x.ImageRevision
	}
	return 0
}

func (x *VmCreateV1) GetImageSha256() []byte {
	if x != nil {
		return x.ImageSha256
	}
	return nil
}

func (x *VmCreateV1) GetProviderTemplateVmid() uint64 {
	if x != nil {
		return x.ProviderTemplateVmid
	}
	return 0
}

type VmCreateResultV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	VmId          []byte                 `protobuf:"bytes,2,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	ProviderName  string                 `protobuf:"bytes,3,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	ProviderNode  string                 `protobuf:"bytes,4,opt,name=provider_node,json=providerNode,proto3" json:"provider_node,omitempty"`
	ProviderVmid  uint64                 `protobuf:"varint,5,opt,name=provider_vmid,json=providerVmid,proto3" json:"provider_vmid,omitempty"`
	Ipv4Address   string                 `protobuf:"bytes,6,opt,name=ipv4_address,json=ipv4Address,proto3" json:"ipv4_address,omitempty"`
	ConfigHash    []byte                 `protobuf:"bytes,7,opt,name=config_hash,json=configHash,proto3" json:"config_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VmCreateResultV1) Reset() {
	*x = VmCreateResultV1{}
	mi := &file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmCreateResultV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmCreateResultV1) ProtoMessage() {}

func (x *VmCreateResultV1) ProtoReflect() protoreflect.Message {
	mi := &file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmCreateResultV1.ProtoReflect.Descriptor instead.
func (*VmCreateResultV1) Descriptor() ([]byte, []int) {
	return file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_rawDescGZIP(), []int{1}
}

func (x *VmCreateResultV1) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *VmCreateResultV1) GetVmId() []byte {
	if x != nil {
		return x.VmId
	}
	return nil
}

func (x *VmCreateResultV1) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *VmCreateResultV1) GetProviderNode() string {
	if x != nil {
		return x.ProviderNode
	}
	return ""
}

func (x *VmCreateResultV1) GetProviderVmid() uint64 {
	if x != nil {
		return x.ProviderVmid
	}
	return 0
}

func (x *VmCreateResultV1) GetIpv4Address() string {
	if x != nil {
		return x.Ipv4Address
	}
	return ""
}

func (x *VmCreateResultV1) GetConfigHash() []byte {
	if x != nil {
		return x.ConfigHash
	}
	return nil
}

type ImageImportV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	ImageId       []byte                 `protobuf:"bytes,2,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	ZoneId        []byte                 `protobuf:"bytes,3,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	Revision      uint64                 `protobuf:"varint,4,opt,name=revision,proto3" json:"revision,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,5,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	Format        string                 `protobuf:"bytes,6,opt,name=format,proto3" json:"format,omitempty"`
	Architecture  string                 `protobuf:"bytes,7,opt,name=architecture,proto3" json:"architecture,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,8,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Sha256        []byte                 `protobuf:"bytes,9,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageImportV1) Reset() {
	*x = ImageImportV1{}
	mi := &file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageImportV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageImportV1) ProtoMessage() {}

func (x *ImageImportV1) ProtoReflect() protoreflect.Message {
	mi := &file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageImportV1.ProtoReflect.Descriptor instead.
func (*ImageImportV1) Descriptor() ([]byte, []int) {
	return file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_rawDescGZIP(), []int{2}
}

func (x *ImageImportV1) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *ImageImportV1) GetImageId() []byte {
	if x != nil {
		return x.ImageId
	}
	return nil
}

func (x *ImageImportV1) GetZoneId() []byte {
	if x != nil {
		return x.ZoneId
	}
	return nil
}

func (x *ImageImportV1) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *ImageImportV1) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *ImageImportV1) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ImageImportV1) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *ImageImportV1) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ImageImportV1) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

type ImageImportResultV1 struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion        uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	ImageId              []byte                 `protobuf:"bytes,2,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	Revision             uint64                 `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	Sha256               []byte                 `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"`
	ProviderTemplateVmid uint64                 `protobuf:"varint,7,opt,name=provider_template_vmid,json=providerTemplateVmid,proto3" json:"provider_template_vmid,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ImageImportResultV1) Reset() {
	*x = ImageImportResultV1{}
	mi := &file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageImportResultV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageImportResultV1) ProtoMessage() {}

func (x *ImageImportResultV1) ProtoReflect() protoreflect.Message {
	mi := &file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageImportResultV1.ProtoReflect.Descriptor instead.
func (*ImageImportResultV1) Descriptor() ([]byte, []int) {
	return file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_rawDescGZIP(), []int{3}
}

func (x *ImageImportResultV1) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *ImageImportResultV1) GetImageId() []byte {
	if x != nil {
		return x.ImageId
	}
	return nil
}

func (x *ImageImportResultV1) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *ImageImportResultV1) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

func (x *ImageImportResultV1) GetProviderTemplateVmid() uint64 {
	if x != nil {
		return x.ProviderTemplateVmid
	}
	return 0
}

type ImageDeleteV1 struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion        uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	ImageId              []byte                 `protobuf:"bytes,2,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	ZoneId               []byte                 `protobuf:"bytes,3,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	Revision             uint64                 `protobuf:"varint,4,opt,name=revision,proto3" json:"revision,omitempty"`
	Sha256               []byte                 `protobuf:"bytes,5,opt,name=sha256,proto3" json:"sha256,omitempty"`
	ObjectKey            string                 `protobuf:"bytes,6,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	ProviderTemplateVmid uint64                 `protobuf:"varint,9,opt,name=provider_template_vmid,json=providerTemplateVmid,proto3" json:"provider_template_vmid,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ImageDeleteV1) Reset() {
	*x = ImageDeleteV1{}
	mi := &file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageDeleteV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageDeleteV1) ProtoMessage() {}

func (x *ImageDeleteV1) ProtoReflect() protoreflect.Message {
	mi := &file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageDeleteV1.ProtoReflect.Descriptor instead.
func (*ImageDeleteV1) Descriptor() ([]byte, []int) {
	return file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_rawDescGZIP(), []int{4}
}

func (x *ImageDeleteV1) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *ImageDeleteV1) GetImageId() []byte {
	if x != nil {
		return x.ImageId
	}
	return nil
}

func (x *ImageDeleteV1) GetZoneId() []byte {
	if x != nil {
		return x.ZoneId
	}
	return nil
}

func (x *ImageDeleteV1) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *ImageDeleteV1) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

func (x *ImageDeleteV1) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *ImageDeleteV1) GetProviderTemplateVmid() uint64 {
	if x != nil {
		return x.ProviderTemplateVmid
	}
	return 0
}

type ImageDeleteResultV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	ImageId       []byte                 `protobuf:"bytes,2,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	Revision      uint64                 `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	Sha256        []byte                 `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageDeleteResultV1) Reset() {
	*x = ImageDeleteResultV1{}
	mi := &file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageDeleteResultV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageDeleteResultV1) ProtoMessage() {}

func (x *ImageDeleteResultV1) ProtoReflect() protoreflect.Message {
	mi := &file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageDeleteResultV1.ProtoReflect.Descriptor instead.
func (*ImageDeleteResultV1) Descriptor() ([]byte, []int) {
	return file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_rawDescGZIP(), []int{5}
}

func (x *ImageDeleteResultV1) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *ImageDeleteResultV1) GetImageId() []byte {
	if x != nil {
		return x.ImageId
	}
	return nil
}

func (x *ImageDeleteResultV1) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *ImageDeleteResultV1) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

var File_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto protoreflect.FileDescriptor

const file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_rawDesc = "" +
	"\n" +
	"<internal/hypervisor/transport/rpc/proto/hypervisor_job.proto\x12\n" +
	"hypervisor\"\xa2\x03\n" +
	"\n" +
	"VmCreateV1\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x13\n" +
	"\x05vm_id\x18\x02 \x01(\fR\x04vmId\x12#\n" +
	"\rprovider_name\x18\x03 \x01(\tR\fproviderName\x12\x19\n" +
	"\bimage_id\x18\x04 \x01(\fR\aimageId\x12\x1b\n" +
	"\tcpu_cores\x18\x05 \x01(\rR\bcpuCores\x12\x1b\n" +
	"\tmemory_mb\x18\x06 \x01(\x04R\bmemoryMb\x12\x17\n" +
	"\adisk_gb\x18\a \x01(\x04R\x06diskGb\x12$\n" +
	"\x0essh_public_key\x18\b \x01(\tR\fsshPublicKey\x12\x1f\n" +
	"\vconfig_hash\x18\t \x01(\fR\n" +
	"configHash\x12%\n" +
	"\x0eimage_revision\x18\n" +
	" \x01(\x04R\rimageRevision\x12!\n" +
	"\fimage_sha256\x18\v \x01(\fR\vimageSha256\x124\n" +
	"\x16provider_template_vmid\x18\f \x01(\x04R\x14providerTemplateVmid\"\x81\x02\n" +
	"\x10VmCreateResultV1\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x13\n" +
	"\x05vm_id\x18\x02 \x01(\fR\x04vmId\x12#\n" +
	"\rprovider_name\x18\x03 \x01(\tR\fproviderName\x12#\n" +
	"\rprovider_node\x18\x04 \x01(\tR\fproviderNode\x12#\n" +
	"\rprovider_vmid\x18\x05 \x01(\x04R\fproviderVmid\x12!\n" +
	"\fipv4_address\x18\x06 \x01(\tR\vipv4Address\x12\x1f\n" +
	"\vconfig_hash\x18\a \x01(\fR\n" +
	"configHash\"\x98\x02\n" +
	"\rImageImportV1\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x19\n" +
	"\bimage_id\x18\x02 \x01(\fR\aimageId\x12\x17\n" +
	"\azone_id\x18\x03 \x01(\fR\x06zoneId\x12\x1a\n" +
	"\brevision\x18\x04 \x01(\x04R\brevision\x12\x1d\n" +
	"\n" +
	"object_key\x18\x05 \x01(\tR\tobjectKey\x12\x16\n" +
	"\x06format\x18\x06 \x01(\tR\x06format\x12\"\n" +
	"\farchitecture\x18\a \x01(\tR\farchitecture\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\b \x01(\x04R\tsizeBytes\x12\x16\n" +
	"\x06sha256\x18\t \x01(\fR\x06sha256\"\xcd\x01\n" +
	"\x13ImageImportResultV1\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x19\n" +
	"\bimage_id\x18\x02 \x01(\fR\aimageId\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x04R\brevision\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\fR\x06sha256\x124\n" +
	"\x16provider_template_vmid\x18\a \x01(\x04R\x14providerTemplateVmidJ\x04\b\x05\x10\x06J\x04\b\x06\x10\a\"\xff\x01\n" +
	"\rImageDeleteV1\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x19\n" +
	"\bimage_id\x18\x02 \x01(\fR\aimageId\x12\x17\n" +
	"\azone_id\x18\x03 \x01(\fR\x06zoneId\x12\x1a\n" +
	"\brevision\x18\x04 \x01(\x04R\brevision\x12\x16\n" +
	"\x06sha256\x18\x05 \x01(\fR\x06sha256\x12\x1d\n" +
	"\n" +
	"object_key\x18\x06 \x01(\tR\tobjectKey\x124\n" +
	"\x16provider_template_vmid\x18\t \x01(\x04R\x14providerTemplateVmidJ\x04\b\a\x10\bJ\x04\b\b\x10\t\"\x8b\x01\n" +
	"\x13ImageDeleteResultV1\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x19\n" +
	"\bimage_id\x18\x02 \x01(\fR\aimageId\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x04R\brevision\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\fR\x06sha256BFZDcontrolplane/internal/hypervisor/transport/rpc/proto;hypervisorprotob\x06proto3"

var (
	file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_rawDescOnce sync.Once
	file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_rawDescData []byte
)

func file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_rawDescGZIP() []byte {
	file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_rawDescOnce.Do(func() {
		file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_rawDesc), len(file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_rawDesc)))
	})
	return file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_rawDescData
}

var file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_goTypes = []any{
	(*VmCreateV1)(nil),          // 0: hypervisor.VmCreateV1
	(*VmCreateResultV1)(nil),    // 1: hypervisor.VmCreateResultV1
	(*ImageImportV1)(nil),       // 2: hypervisor.ImageImportV1
	(*ImageImportResultV1)(nil), // 3: hypervisor.ImageImportResultV1
	(*ImageDeleteV1)(nil),       // 4: hypervisor.ImageDeleteV1
	(*ImageDeleteResultV1)(nil), // 5: hypervisor.ImageDeleteResultV1
}
var file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_init() }
func file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_init() {
	if File_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_rawDesc), len(file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_goTypes,
		DependencyIndexes: file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_depIdxs,
		MessageInfos:      file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_msgTypes,
	}.Build()
	File_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto = out.File
	file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_goTypes = nil
	file_internal_hypervisor_transport_rpc_proto_hypervisor_job_proto_depIdxs = nil
}
