// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: tenant_wallet_provision.proto

package iamproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TenantWalletProvisionRequestedV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       []byte                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	SchemaVersion int32                  `protobuf:"varint,2,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	TenantId      []byte                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ActorUserId   []byte                 `protobuf:"bytes,4,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	OccurredAt    string                 `protobuf:"bytes,6,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantWalletProvisionRequestedV1) Reset() {
	*x = TenantWalletProvisionRequestedV1{}
	mi := &file_tenant_wallet_provision_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantWalletProvisionRequestedV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantWalletProvisionRequestedV1) ProtoMessage() {}

func (x *TenantWalletProvisionRequestedV1) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_wallet_provision_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantWalletProvisionRequestedV1.ProtoReflect.Descriptor instead.
func (*TenantWalletProvisionRequestedV1) Descriptor() ([]byte, []int) {
	return file_tenant_wallet_provision_proto_rawDescGZIP(), []int{0}
}

func (x *TenantWalletProvisionRequestedV1) GetEventId() []byte {
	if x != nil {
		return x.EventId
	}
	return nil
}

func (x *TenantWalletProvisionRequestedV1) GetSchemaVersion() int32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *TenantWalletProvisionRequestedV1) GetTenantId() []byte {
	if x != nil {
		return x.TenantId
	}
	return nil
}

func (x *TenantWalletProvisionRequestedV1) GetActorUserId() []byte {
	if x != nil {
		return x.ActorUserId
	}
	return nil
}

func (x *TenantWalletProvisionRequestedV1) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *TenantWalletProvisionRequestedV1) GetOccurredAt() string {
	if x != nil {
		return x.OccurredAt
	}
	return ""
}

var File_tenant_wallet_provision_proto protoreflect.FileDescriptor

const file_tenant_wallet_provision_proto_rawDesc = "" +
	"\n" +
	"\x1dtenant_wallet_provision.proto\x12\biamproto\"\xe2\x01\n" +
	" TenantWalletProvisionRequestedV1\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\fR\aeventId\x12%\n" +
	"\x0eschema_version\x18\x02 \x01(\x05R\rschemaVersion\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\fR\btenantId\x12\"\n" +
	"\ractor_user_id\x18\x04 \x01(\fR\vactorUserId\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x1f\n" +
	"\voccurred_at\x18\x06 \x01(\tR\n" +
	"occurredAtB4Z2controlplane/internal/iam/transport/proto;iamprotob\x06proto3"

var (
	file_tenant_wallet_provision_proto_rawDescOnce sync.Once
	file_tenant_wallet_provision_proto_rawDescData []byte
)

func file_tenant_wallet_provision_proto_rawDescGZIP() []byte {
	file_tenant_wallet_provision_proto_rawDescOnce.Do(func() {
		file_tenant_wallet_provision_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tenant_wallet_provision_proto_rawDesc), len(file_tenant_wallet_provision_proto_rawDesc)))
	})
	return file_tenant_wallet_provision_proto_rawDescData
}

var file_tenant_wallet_provision_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tenant_wallet_provision_proto_goTypes = []any{
	(*TenantWalletProvisionRequestedV1)(nil), // 0: iamproto.TenantWalletProvisionRequestedV1
}
var file_tenant_wallet_provision_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tenant_wallet_provision_proto_init() }
func file_tenant_wallet_provision_proto_init() {
	if File_tenant_wallet_provision_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tenant_wallet_provision_proto_rawDesc), len(file_tenant_wallet_provision_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tenant_wallet_provision_proto_goTypes,
		DependencyIndexes: file_tenant_wallet_provision_proto_depIdxs,
		MessageInfos:      file_tenant_wallet_provision_proto_msgTypes,
	}.Build()
	File_tenant_wallet_provision_proto = out.File
	file_tenant_wallet_provision_proto_goTypes = nil
	file_tenant_wallet_provision_proto_depIdxs = nil
}
