syntax = "proto3";
package trinity.rpc;

// Request/Response xác thực cho Admin/SRE quản trị hệ thống qua NATS
message VerifyAdminTrinityTokenRequest {
  string access_token = 1;
  string access_key = 2;
  string access_secret = 3;
}

message VerifyAdminTrinityTokenResponse {
  bool valid = 1;
  string user_id = 2;
  string role_id = 3;
}

// Request/Response xác thực cho End-User thông thường qua NATS
message VerifyUserTrinityTokenRequest {
  string access_token = 1;
  string access_key = 2;
  string access_secret = 3;
}

message VerifyUserTrinityTokenResponse {
  bool valid = 1;
  string user_id = 2;
  string role_id = 3;
  string zone_id = 4;
}
