// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: controlplane/internal/storage/transport/rpc/proto/storage_job.proto

package storageproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Cấu hình đồng bộ hóa Bucket vật lý từ Controlplane sang Dataplane
type BucketSync struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                              // ID bucket dạng UUID string
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                          // Tên vật lý của bucket
	ZoneId             string                 `protobuf:"bytes,3,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`                                        // ID zone sở hữu bucket
	WorkspaceId        string                 `protobuf:"bytes,4,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`                         // ID workspace sở hữu bucket
	TenantId           string                 `protobuf:"bytes,5,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                                  // ID tenant sở hữu bucket (nếu là tenant bucket, để trống nếu personal)
	Status             string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`                                                      // Trạng thái (creating, active, suspended, deleted)
	CapacityQuotaBytes int64                  `protobuf:"varint,7,opt,name=capacity_quota_bytes,json=capacityQuotaBytes,proto3" json:"capacity_quota_bytes,omitempty"` // Hạn mức quota bytes
	UpdatedAt          int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                              // Thời điểm cập nhật cuối (Epoch Milliseconds)
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BucketSync) Reset() {
	*x = BucketSync{}
	mi := &file_controlplane_internal_storage_transport_rpc_proto_storage_job_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BucketSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketSync) ProtoMessage() {}

func (x *BucketSync) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_internal_storage_transport_rpc_proto_storage_job_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketSync.ProtoReflect.Descriptor instead.
func (*BucketSync) Descriptor() ([]byte, []int) {
	return file_controlplane_internal_storage_transport_rpc_proto_storage_job_proto_rawDescGZIP(), []int{0}
}

func (x *BucketSync) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BucketSync) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BucketSync) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *BucketSync) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *BucketSync) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *BucketSync) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BucketSync) GetCapacityQuotaBytes() int64 {
	if x != nil {
		return x.CapacityQuotaBytes
	}
	return 0
}

func (x *BucketSync) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// Cấu hình đồng bộ hóa Credential vật lý từ Controlplane sang Dataplane
type CredentialSync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                 // ID credential dạng UUID string
	BucketId      string                 `protobuf:"bytes,2,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`     // ID bucket liên kết
	AccessKey     string                 `protobuf:"bytes,3,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`  // Access Key MinIO
	SecretKey     string                 `protobuf:"bytes,4,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`  // Secret Key MinIO
	Policy        string                 `protobuf:"bytes,5,opt,name=policy,proto3" json:"policy,omitempty"`                         // JSON policy
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`                         // Trạng thái hoạt động (active, revoked)
	UpdatedAt     int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // Thời điểm cập nhật cuối (Epoch Milliseconds)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialSync) Reset() {
	*x = CredentialSync{}
	mi := &file_controlplane_internal_storage_transport_rpc_proto_storage_job_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialSync) ProtoMessage() {}

func (x *CredentialSync) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_internal_storage_transport_rpc_proto_storage_job_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialSync.ProtoReflect.Descriptor instead.
func (*CredentialSync) Descriptor() ([]byte, []int) {
	return file_controlplane_internal_storage_transport_rpc_proto_storage_job_proto_rawDescGZIP(), []int{1}
}

func (x *CredentialSync) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CredentialSync) GetBucketId() string {
	if x != nil {
		return x.BucketId
	}
	return ""
}

func (x *CredentialSync) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *CredentialSync) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *CredentialSync) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

func (x *CredentialSync) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CredentialSync) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

var File_controlplane_internal_storage_transport_rpc_proto_storage_job_proto protoreflect.FileDescriptor

const file_controlplane_internal_storage_transport_rpc_proto_storage_job_proto_rawDesc = "" +
	"\n" +
	"Ccontrolplane/internal/storage/transport/rpc/proto/storage_job.proto\x12\astorage\"\xf2\x01\n" +
	"\n" +
	"BucketSync\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\azone_id\x18\x03 \x01(\tR\x06zoneId\x12!\n" +
	"\fworkspace_id\x18\x04 \x01(\tR\vworkspaceId\x12\x1b\n" +
	"\ttenant_id\x18\x05 \x01(\tR\btenantId\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x120\n" +
	"\x14capacity_quota_bytes\x18\a \x01(\x03R\x12capacityQuotaBytes\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\"\xca\x01\n" +
	"\x0eCredentialSync\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tbucket_id\x18\x02 \x01(\tR\bbucketId\x12\x1d\n" +
	"\n" +
	"access_key\x18\x03 \x01(\tR\taccessKey\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x04 \x01(\tR\tsecretKey\x12\x16\n" +
	"\x06policy\x18\x05 \x01(\tR\x06policy\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAtB@Z>controlplane/internal/storage/transport/rpc/proto;storageprotob\x06proto3"

var (
	file_controlplane_internal_storage_transport_rpc_proto_storage_job_proto_rawDescOnce sync.Once
	file_controlplane_internal_storage_transport_rpc_proto_storage_job_proto_rawDescData []byte
)

func file_controlplane_internal_storage_transport_rpc_proto_storage_job_proto_rawDescGZIP() []byte {
	file_controlplane_internal_storage_transport_rpc_proto_storage_job_proto_rawDescOnce.Do(func() {
		file_controlplane_internal_storage_transport_rpc_proto_storage_job_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_controlplane_internal_storage_transport_rpc_proto_storage_job_proto_rawDesc), len(file_controlplane_internal_storage_transport_rpc_proto_storage_job_proto_rawDesc)))
	})
	return file_controlplane_internal_storage_transport_rpc_proto_storage_job_proto_rawDescData
}

var file_controlplane_internal_storage_transport_rpc_proto_storage_job_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_controlplane_internal_storage_transport_rpc_proto_storage_job_proto_goTypes = []any{
	(*BucketSync)(nil),     // 0: storage.BucketSync
	(*CredentialSync)(nil), // 1: storage.CredentialSync
}
var file_controlplane_internal_storage_transport_rpc_proto_storage_job_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_controlplane_internal_storage_transport_rpc_proto_storage_job_proto_init() }
func file_controlplane_internal_storage_transport_rpc_proto_storage_job_proto_init() {
	if File_controlplane_internal_storage_transport_rpc_proto_storage_job_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controlplane_internal_storage_transport_rpc_proto_storage_job_proto_rawDesc), len(file_controlplane_internal_storage_transport_rpc_proto_storage_job_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_controlplane_internal_storage_transport_rpc_proto_storage_job_proto_goTypes,
		DependencyIndexes: file_controlplane_internal_storage_transport_rpc_proto_storage_job_proto_depIdxs,
		MessageInfos:      file_controlplane_internal_storage_transport_rpc_proto_storage_job_proto_msgTypes,
	}.Build()
	File_controlplane_internal_storage_transport_rpc_proto_storage_job_proto = out.File
	file_controlplane_internal_storage_transport_rpc_proto_storage_job_proto_goTypes = nil
	file_controlplane_internal_storage_transport_rpc_proto_storage_job_proto_depIdxs = nil
}
