// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: storage_job.proto

package storageproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Cấu hình đồng bộ hóa Bucket vật lý từ Controlplane sang Dataplane
type BucketSync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                            // Tên vật lý của bucket
	AccessKey     string                 `protobuf:"bytes,2,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"` // Access Key sẽ được tạo trên MinIO
	SecretKey     string                 `protobuf:"bytes,3,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"` // Secret Key (plaintext trong payload, transit qua internal infra)
	Policy        string                 `protobuf:"bytes,4,opt,name=policy,proto3" json:"policy,omitempty"`                        // JSON policy giới hạn quyền truy cập chỉ vào bucket này
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BucketSync) Reset() {
	*x = BucketSync{}
	mi := &file_storage_job_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BucketSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketSync) ProtoMessage() {}

func (x *BucketSync) ProtoReflect() protoreflect.Message {
	mi := &file_storage_job_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketSync.ProtoReflect.Descriptor instead.
func (*BucketSync) Descriptor() ([]byte, []int) {
	return file_storage_job_proto_rawDescGZIP(), []int{0}
}

func (x *BucketSync) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BucketSync) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *BucketSync) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *BucketSync) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

// Cấu hình đồng bộ hóa Credential vật lý từ Controlplane sang Dataplane
type CredentialSync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                // ID credential dạng UUID string
	AccessKey     string                 `protobuf:"bytes,2,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"` // Access Key MinIO
	SecretKey     string                 `protobuf:"bytes,3,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"` // Secret Key MinIO
	Policy        string                 `protobuf:"bytes,4,opt,name=policy,proto3" json:"policy,omitempty"`                        // JSON policy
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialSync) Reset() {
	*x = CredentialSync{}
	mi := &file_storage_job_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialSync) ProtoMessage() {}

func (x *CredentialSync) ProtoReflect() protoreflect.Message {
	mi := &file_storage_job_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialSync.ProtoReflect.Descriptor instead.
func (*CredentialSync) Descriptor() ([]byte, []int) {
	return file_storage_job_proto_rawDescGZIP(), []int{1}
}

func (x *CredentialSync) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CredentialSync) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *CredentialSync) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *CredentialSync) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

// Cấu hình đồng bộ hóa thay đổi hạn mức (resize) Bucket
type BucketResizeSync struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	BucketId            string                 `protobuf:"bytes,1,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`                                     // ID bucket dạng UUID string để DP ghi log
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                             // Tên vật lý của bucket
	CurrentQuotaBytes   int64                  `protobuf:"varint,3,opt,name=current_quota_bytes,json=currentQuotaBytes,proto3" json:"current_quota_bytes,omitempty"`       // Quota hiện tại
	RequestedQuotaBytes int64                  `protobuf:"varint,4,opt,name=requested_quota_bytes,json=requestedQuotaBytes,proto3" json:"requested_quota_bytes,omitempty"` // Quota muốn thay đổi
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BucketResizeSync) Reset() {
	*x = BucketResizeSync{}
	mi := &file_storage_job_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BucketResizeSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketResizeSync) ProtoMessage() {}

func (x *BucketResizeSync) ProtoReflect() protoreflect.Message {
	mi := &file_storage_job_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketResizeSync.ProtoReflect.Descriptor instead.
func (*BucketResizeSync) Descriptor() ([]byte, []int) {
	return file_storage_job_proto_rawDescGZIP(), []int{2}
}

func (x *BucketResizeSync) GetBucketId() string {
	if x != nil {
		return x.BucketId
	}
	return ""
}

func (x *BucketResizeSync) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BucketResizeSync) GetCurrentQuotaBytes() int64 {
	if x != nil {
		return x.CurrentQuotaBytes
	}
	return 0
}

func (x *BucketResizeSync) GetRequestedQuotaBytes() int64 {
	if x != nil {
		return x.RequestedQuotaBytes
	}
	return 0
}

// Cấu hình đồng bộ hóa xóa Bucket vật lý
type BucketDeleteSync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                               // Tên vật lý của bucket cần xóa
	AccessKeys    []string               `protobuf:"bytes,2,rep,name=access_keys,json=accessKeys,proto3" json:"access_keys,omitempty"` // Danh sách access keys cần thu hồi/xóa sạch
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BucketDeleteSync) Reset() {
	*x = BucketDeleteSync{}
	mi := &file_storage_job_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BucketDeleteSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketDeleteSync) ProtoMessage() {}

func (x *BucketDeleteSync) ProtoReflect() protoreflect.Message {
	mi := &file_storage_job_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketDeleteSync.ProtoReflect.Descriptor instead.
func (*BucketDeleteSync) Descriptor() ([]byte, []int) {
	return file_storage_job_proto_rawDescGZIP(), []int{3}
}

func (x *BucketDeleteSync) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BucketDeleteSync) GetAccessKeys() []string {
	if x != nil {
		return x.AccessKeys
	}
	return nil
}

var File_storage_job_proto protoreflect.FileDescriptor

const file_storage_job_proto_rawDesc = "" +
	"\n" +
	"\x11storage_job.proto\x12\astorage\"v\n" +
	"\n" +
	"BucketSync\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"access_key\x18\x02 \x01(\tR\taccessKey\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x03 \x01(\tR\tsecretKey\x12\x16\n" +
	"\x06policy\x18\x04 \x01(\tR\x06policy\"v\n" +
	"\x0eCredentialSync\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"access_key\x18\x02 \x01(\tR\taccessKey\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x03 \x01(\tR\tsecretKey\x12\x16\n" +
	"\x06policy\x18\x04 \x01(\tR\x06policy\"\xa7\x01\n" +
	"\x10BucketResizeSync\x12\x1b\n" +
	"\tbucket_id\x18\x01 \x01(\tR\bbucketId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12.\n" +
	"\x13current_quota_bytes\x18\x03 \x01(\x03R\x11currentQuotaBytes\x122\n" +
	"\x15requested_quota_bytes\x18\x04 \x01(\x03R\x13requestedQuotaBytes\"G\n" +
	"\x10BucketDeleteSync\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vaccess_keys\x18\x02 \x03(\tR\n" +
	"accessKeysB@Z>controlplane/internal/storage/transport/rpc/proto;storageprotob\x06proto3"

var (
	file_storage_job_proto_rawDescOnce sync.Once
	file_storage_job_proto_rawDescData []byte
)

func file_storage_job_proto_rawDescGZIP() []byte {
	file_storage_job_proto_rawDescOnce.Do(func() {
		file_storage_job_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_job_proto_rawDesc), len(file_storage_job_proto_rawDesc)))
	})
	return file_storage_job_proto_rawDescData
}

var file_storage_job_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_storage_job_proto_goTypes = []any{
	(*BucketSync)(nil),       // 0: storage.BucketSync
	(*CredentialSync)(nil),   // 1: storage.CredentialSync
	(*BucketResizeSync)(nil), // 2: storage.BucketResizeSync
	(*BucketDeleteSync)(nil), // 3: storage.BucketDeleteSync
}
var file_storage_job_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_storage_job_proto_init() }
func file_storage_job_proto_init() {
	if File_storage_job_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_job_proto_rawDesc), len(file_storage_job_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_storage_job_proto_goTypes,
		DependencyIndexes: file_storage_job_proto_depIdxs,
		MessageInfos:      file_storage_job_proto_msgTypes,
	}.Build()
	File_storage_job_proto = out.File
	file_storage_job_proto_goTypes = nil
	file_storage_job_proto_depIdxs = nil
}
