// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: internal/transport/proto/pricing_event.proto

package pricingproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TierVersionPublished chỉ mang identity/version; Engine luôn load full immutable snapshot từ PostgreSQL.
type TierVersionPublished struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	EventId             string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TierId              string                 `protobuf:"bytes,2,opt,name=tier_id,json=tierId,proto3" json:"tier_id,omitempty"`
	TierVersionId       string                 `protobuf:"bytes,3,opt,name=tier_version_id,json=tierVersionId,proto3" json:"tier_version_id,omitempty"`
	VersionNumber       int32                  `protobuf:"varint,4,opt,name=version_number,json=versionNumber,proto3" json:"version_number,omitempty"`
	ServiceType         string                 `protobuf:"bytes,5,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`
	EffectiveFromUnixMs int64                  `protobuf:"varint,6,opt,name=effective_from_unix_ms,json=effectiveFromUnixMs,proto3" json:"effective_from_unix_ms,omitempty"`
	Checksum            string                 `protobuf:"bytes,7,opt,name=checksum,proto3" json:"checksum,omitempty"`
	OccurredAtUnixMs    int64                  `protobuf:"varint,8,opt,name=occurred_at_unix_ms,json=occurredAtUnixMs,proto3" json:"occurred_at_unix_ms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TierVersionPublished) Reset() {
	*x = TierVersionPublished{}
	mi := &file_internal_transport_proto_pricing_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TierVersionPublished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TierVersionPublished) ProtoMessage() {}

func (x *TierVersionPublished) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_proto_pricing_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TierVersionPublished.ProtoReflect.Descriptor instead.
func (*TierVersionPublished) Descriptor() ([]byte, []int) {
	return file_internal_transport_proto_pricing_event_proto_rawDescGZIP(), []int{0}
}

func (x *TierVersionPublished) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *TierVersionPublished) GetTierId() string {
	if x != nil {
		return x.TierId
	}
	return ""
}

func (x *TierVersionPublished) GetTierVersionId() string {
	if x != nil {
		return x.TierVersionId
	}
	return ""
}

func (x *TierVersionPublished) GetVersionNumber() int32 {
	if x != nil {
		return x.VersionNumber
	}
	return 0
}

func (x *TierVersionPublished) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

func (x *TierVersionPublished) GetEffectiveFromUnixMs() int64 {
	if x != nil {
		return x.EffectiveFromUnixMs
	}
	return 0
}

func (x *TierVersionPublished) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *TierVersionPublished) GetOccurredAtUnixMs() int64 {
	if x != nil {
		return x.OccurredAtUnixMs
	}
	return 0
}

var File_internal_transport_proto_pricing_event_proto protoreflect.FileDescriptor

const file_internal_transport_proto_pricing_event_proto_rawDesc = "" +
	"\n" +
	",internal/transport/proto/pricing_event.proto\x12\x12billing.pricing.v1\"\xbc\x02\n" +
	"\x14TierVersionPublished\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\atier_id\x18\x02 \x01(\tR\x06tierId\x12&\n" +
	"\x0ftier_version_id\x18\x03 \x01(\tR\rtierVersionId\x12%\n" +
	"\x0eversion_number\x18\x04 \x01(\x05R\rversionNumber\x12!\n" +
	"\fservice_type\x18\x05 \x01(\tR\vserviceType\x123\n" +
	"\x16effective_from_unix_ms\x18\x06 \x01(\x03R\x13effectiveFromUnixMs\x12\x1a\n" +
	"\bchecksum\x18\a \x01(\tR\bchecksum\x12-\n" +
	"\x13occurred_at_unix_ms\x18\b \x01(\x03R\x10occurredAtUnixMsB8Z6cost-manager/api/internal/transport/proto/pricingprotob\x06proto3"

var (
	file_internal_transport_proto_pricing_event_proto_rawDescOnce sync.Once
	file_internal_transport_proto_pricing_event_proto_rawDescData []byte
)

func file_internal_transport_proto_pricing_event_proto_rawDescGZIP() []byte {
	file_internal_transport_proto_pricing_event_proto_rawDescOnce.Do(func() {
		file_internal_transport_proto_pricing_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_transport_proto_pricing_event_proto_rawDesc), len(file_internal_transport_proto_pricing_event_proto_rawDesc)))
	})
	return file_internal_transport_proto_pricing_event_proto_rawDescData
}

var file_internal_transport_proto_pricing_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_transport_proto_pricing_event_proto_goTypes = []any{
	(*TierVersionPublished)(nil), // 0: billing.pricing.v1.TierVersionPublished
}
var file_internal_transport_proto_pricing_event_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_transport_proto_pricing_event_proto_init() }
func file_internal_transport_proto_pricing_event_proto_init() {
	if File_internal_transport_proto_pricing_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_transport_proto_pricing_event_proto_rawDesc), len(file_internal_transport_proto_pricing_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_transport_proto_pricing_event_proto_goTypes,
		DependencyIndexes: file_internal_transport_proto_pricing_event_proto_depIdxs,
		MessageInfos:      file_internal_transport_proto_pricing_event_proto_msgTypes,
	}.Build()
	File_internal_transport_proto_pricing_event_proto = out.File
	file_internal_transport_proto_pricing_event_proto_goTypes = nil
	file_internal_transport_proto_pricing_event_proto_depIdxs = nil
}
