// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: internal/core/transport/rpc/proto/core_cache.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ZoneCatalog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZoneCatalog) Reset() {
	*x = ZoneCatalog{}
	mi := &file_internal_core_transport_rpc_proto_core_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoneCatalog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneCatalog) ProtoMessage() {}

func (x *ZoneCatalog) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_transport_rpc_proto_core_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneCatalog.ProtoReflect.Descriptor instead.
func (*ZoneCatalog) Descriptor() ([]byte, []int) {
	return file_internal_core_transport_rpc_proto_core_cache_proto_rawDescGZIP(), []int{0}
}

func (x *ZoneCatalog) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ZoneCatalog) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ZoneCatalogList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zones         []*ZoneCatalog         `protobuf:"bytes,1,rep,name=zones,proto3" json:"zones,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZoneCatalogList) Reset() {
	*x = ZoneCatalogList{}
	mi := &file_internal_core_transport_rpc_proto_core_cache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoneCatalogList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneCatalogList) ProtoMessage() {}

func (x *ZoneCatalogList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_transport_rpc_proto_core_cache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneCatalogList.ProtoReflect.Descriptor instead.
func (*ZoneCatalogList) Descriptor() ([]byte, []int) {
	return file_internal_core_transport_rpc_proto_core_cache_proto_rawDescGZIP(), []int{1}
}

func (x *ZoneCatalogList) GetZones() []*ZoneCatalog {
	if x != nil {
		return x.Zones
	}
	return nil
}

type RuntimeSecret struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Secret          []byte                 `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	Fingerprint     string                 `protobuf:"bytes,2,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	CreatedAtUnixNs int64                  `protobuf:"varint,3,opt,name=created_at_unix_ns,json=createdAtUnixNs,proto3" json:"created_at_unix_ns,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RuntimeSecret) Reset() {
	*x = RuntimeSecret{}
	mi := &file_internal_core_transport_rpc_proto_core_cache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeSecret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeSecret) ProtoMessage() {}

func (x *RuntimeSecret) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_transport_rpc_proto_core_cache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeSecret.ProtoReflect.Descriptor instead.
func (*RuntimeSecret) Descriptor() ([]byte, []int) {
	return file_internal_core_transport_rpc_proto_core_cache_proto_rawDescGZIP(), []int{2}
}

func (x *RuntimeSecret) GetSecret() []byte {
	if x != nil {
		return x.Secret
	}
	return nil
}

func (x *RuntimeSecret) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *RuntimeSecret) GetCreatedAtUnixNs() int64 {
	if x != nil {
		return x.CreatedAtUnixNs
	}
	return 0
}

type RuntimeSecrets struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SecretType     string                 `protobuf:"bytes,1,opt,name=secret_type,json=secretType,proto3" json:"secret_type,omitempty"`
	Active         *RuntimeSecret         `protobuf:"bytes,2,opt,name=active,proto3" json:"active,omitempty"`
	Standby        *RuntimeSecret         `protobuf:"bytes,3,opt,name=standby,proto3" json:"standby,omitempty"`
	LoadedAtUnixNs int64                  `protobuf:"varint,4,opt,name=loaded_at_unix_ns,json=loadedAtUnixNs,proto3" json:"loaded_at_unix_ns,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RuntimeSecrets) Reset() {
	*x = RuntimeSecrets{}
	mi := &file_internal_core_transport_rpc_proto_core_cache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeSecrets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeSecrets) ProtoMessage() {}

func (x *RuntimeSecrets) ProtoReflect() protoreflect.Message {
	mi := &file_internal_core_transport_rpc_proto_core_cache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeSecrets.ProtoReflect.Descriptor instead.
func (*RuntimeSecrets) Descriptor() ([]byte, []int) {
	return file_internal_core_transport_rpc_proto_core_cache_proto_rawDescGZIP(), []int{3}
}

func (x *RuntimeSecrets) GetSecretType() string {
	if x != nil {
		return x.SecretType
	}
	return ""
}

func (x *RuntimeSecrets) GetActive() *RuntimeSecret {
	if x != nil {
		return x.Active
	}
	return nil
}

func (x *RuntimeSecrets) GetStandby() *RuntimeSecret {
	if x != nil {
		return x.Standby
	}
	return nil
}

func (x *RuntimeSecrets) GetLoadedAtUnixNs() int64 {
	if x != nil {
		return x.LoadedAtUnixNs
	}
	return 0
}

var File_internal_core_transport_rpc_proto_core_cache_proto protoreflect.FileDescriptor

const file_internal_core_transport_rpc_proto_core_cache_proto_rawDesc = "" +
	"\n" +
	"2internal/core/transport/rpc/proto/core_cache.proto\x12\bcore.rpc\"5\n" +
	"\vZoneCatalog\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\">\n" +
	"\x0fZoneCatalogList\x12+\n" +
	"\x05zones\x18\x01 \x03(\v2\x15.core.rpc.ZoneCatalogR\x05zones\"v\n" +
	"\rRuntimeSecret\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\fR\x06secret\x12 \n" +
	"\vfingerprint\x18\x02 \x01(\tR\vfingerprint\x12+\n" +
	"\x12created_at_unix_ns\x18\x03 \x01(\x03R\x0fcreatedAtUnixNs\"\xc0\x01\n" +
	"\x0eRuntimeSecrets\x12\x1f\n" +
	"\vsecret_type\x18\x01 \x01(\tR\n" +
	"secretType\x12/\n" +
	"\x06active\x18\x02 \x01(\v2\x17.core.rpc.RuntimeSecretR\x06active\x121\n" +
	"\astandby\x18\x03 \x01(\v2\x17.core.rpc.RuntimeSecretR\astandby\x12)\n" +
	"\x11loaded_at_unix_ns\x18\x04 \x01(\x03R\x0eloadedAtUnixNsB0Z.controlplane/internal/core/transport/rpc/protob\x06proto3"

var (
	file_internal_core_transport_rpc_proto_core_cache_proto_rawDescOnce sync.Once
	file_internal_core_transport_rpc_proto_core_cache_proto_rawDescData []byte
)

func file_internal_core_transport_rpc_proto_core_cache_proto_rawDescGZIP() []byte {
	file_internal_core_transport_rpc_proto_core_cache_proto_rawDescOnce.Do(func() {
		file_internal_core_transport_rpc_proto_core_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_core_transport_rpc_proto_core_cache_proto_rawDesc), len(file_internal_core_transport_rpc_proto_core_cache_proto_rawDesc)))
	})
	return file_internal_core_transport_rpc_proto_core_cache_proto_rawDescData
}

var file_internal_core_transport_rpc_proto_core_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_core_transport_rpc_proto_core_cache_proto_goTypes = []any{
	(*ZoneCatalog)(nil),     // 0: core.rpc.ZoneCatalog
	(*ZoneCatalogList)(nil), // 1: core.rpc.ZoneCatalogList
	(*RuntimeSecret)(nil),   // 2: core.rpc.RuntimeSecret
	(*RuntimeSecrets)(nil),  // 3: core.rpc.RuntimeSecrets
}
var file_internal_core_transport_rpc_proto_core_cache_proto_depIdxs = []int32{
	0, // 0: core.rpc.ZoneCatalogList.zones:type_name -> core.rpc.ZoneCatalog
	2, // 1: core.rpc.RuntimeSecrets.active:type_name -> core.rpc.RuntimeSecret
	2, // 2: core.rpc.RuntimeSecrets.standby:type_name -> core.rpc.RuntimeSecret
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_core_transport_rpc_proto_core_cache_proto_init() }
func file_internal_core_transport_rpc_proto_core_cache_proto_init() {
	if File_internal_core_transport_rpc_proto_core_cache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_core_transport_rpc_proto_core_cache_proto_rawDesc), len(file_internal_core_transport_rpc_proto_core_cache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_core_transport_rpc_proto_core_cache_proto_goTypes,
		DependencyIndexes: file_internal_core_transport_rpc_proto_core_cache_proto_depIdxs,
		MessageInfos:      file_internal_core_transport_rpc_proto_core_cache_proto_msgTypes,
	}.Build()
	File_internal_core_transport_rpc_proto_core_cache_proto = out.File
	file_internal_core_transport_rpc_proto_core_cache_proto_goTypes = nil
	file_internal_core_transport_rpc_proto_core_cache_proto_depIdxs = nil
}
