// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: zone.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetZoneListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetZoneListRequest) Reset() {
	*x = GetZoneListRequest{}
	mi := &file_zone_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetZoneListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetZoneListRequest) ProtoMessage() {}

func (x *GetZoneListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zone_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetZoneListRequest.ProtoReflect.Descriptor instead.
func (*GetZoneListRequest) Descriptor() ([]byte, []int) {
	return file_zone_proto_rawDescGZIP(), []int{0}
}

type ZoneEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneId        string                 `protobuf:"bytes,1,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	ZoneCode      string                 `protobuf:"bytes,2,opt,name=zone_code,json=zoneCode,proto3" json:"zone_code,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // Trạng thái hoạt động của zone (active, planned, draining, etc.)
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZoneEntry) Reset() {
	*x = ZoneEntry{}
	mi := &file_zone_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoneEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneEntry) ProtoMessage() {}

func (x *ZoneEntry) ProtoReflect() protoreflect.Message {
	mi := &file_zone_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneEntry.ProtoReflect.Descriptor instead.
func (*ZoneEntry) Descriptor() ([]byte, []int) {
	return file_zone_proto_rawDescGZIP(), []int{1}
}

func (x *ZoneEntry) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *ZoneEntry) GetZoneCode() string {
	if x != nil {
		return x.ZoneCode
	}
	return ""
}

func (x *ZoneEntry) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ZoneEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetZoneListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zones         []*ZoneEntry           `protobuf:"bytes,1,rep,name=zones,proto3" json:"zones,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetZoneListResponse) Reset() {
	*x = GetZoneListResponse{}
	mi := &file_zone_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetZoneListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetZoneListResponse) ProtoMessage() {}

func (x *GetZoneListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zone_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetZoneListResponse.ProtoReflect.Descriptor instead.
func (*GetZoneListResponse) Descriptor() ([]byte, []int) {
	return file_zone_proto_rawDescGZIP(), []int{2}
}

func (x *GetZoneListResponse) GetZones() []*ZoneEntry {
	if x != nil {
		return x.Zones
	}
	return nil
}

var File_zone_proto protoreflect.FileDescriptor

const file_zone_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"zone.proto\x12\bcore.rpc\"\x14\n" +
	"\x12GetZoneListRequest\"m\n" +
	"\tZoneEntry\x12\x17\n" +
	"\azone_id\x18\x01 \x01(\tR\x06zoneId\x12\x1b\n" +
	"\tzone_code\x18\x02 \x01(\tR\bzoneCode\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"@\n" +
	"\x13GetZoneListResponse\x12)\n" +
	"\x05zones\x18\x01 \x03(\v2\x13.core.rpc.ZoneEntryR\x05zones2Y\n" +
	"\vZoneService\x12J\n" +
	"\vGetZoneList\x12\x1c.core.rpc.GetZoneListRequest\x1a\x1d.core.rpc.GetZoneListResponseB0Z.controlplane/internal/core/transport/rpc/protob\x06proto3"

var (
	file_zone_proto_rawDescOnce sync.Once
	file_zone_proto_rawDescData []byte
)

func file_zone_proto_rawDescGZIP() []byte {
	file_zone_proto_rawDescOnce.Do(func() {
		file_zone_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zone_proto_rawDesc), len(file_zone_proto_rawDesc)))
	})
	return file_zone_proto_rawDescData
}

var file_zone_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_zone_proto_goTypes = []any{
	(*GetZoneListRequest)(nil),  // 0: core.rpc.GetZoneListRequest
	(*ZoneEntry)(nil),           // 1: core.rpc.ZoneEntry
	(*GetZoneListResponse)(nil), // 2: core.rpc.GetZoneListResponse
}
var file_zone_proto_depIdxs = []int32{
	1, // 0: core.rpc.GetZoneListResponse.zones:type_name -> core.rpc.ZoneEntry
	0, // 1: core.rpc.ZoneService.GetZoneList:input_type -> core.rpc.GetZoneListRequest
	2, // 2: core.rpc.ZoneService.GetZoneList:output_type -> core.rpc.GetZoneListResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_zone_proto_init() }
func file_zone_proto_init() {
	if File_zone_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zone_proto_rawDesc), len(file_zone_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zone_proto_goTypes,
		DependencyIndexes: file_zone_proto_depIdxs,
		MessageInfos:      file_zone_proto_msgTypes,
	}.Build()
	File_zone_proto = out.File
	file_zone_proto_goTypes = nil
	file_zone_proto_depIdxs = nil
}
