// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: managed_service.proto

package managedserviceproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ManagedServiceOwnerTypeV1 int32

const (
	ManagedServiceOwnerTypeV1_MANAGED_SERVICE_OWNER_TYPE_UNSPECIFIED ManagedServiceOwnerTypeV1 = 0
	ManagedServiceOwnerTypeV1_MANAGED_SERVICE_OWNER_TYPE_PERSONAL    ManagedServiceOwnerTypeV1 = 1
	ManagedServiceOwnerTypeV1_MANAGED_SERVICE_OWNER_TYPE_TENANT      ManagedServiceOwnerTypeV1 = 2
)

// Enum value maps for ManagedServiceOwnerTypeV1.
var (
	ManagedServiceOwnerTypeV1_name = map[int32]string{
		0: "MANAGED_SERVICE_OWNER_TYPE_UNSPECIFIED",
		1: "MANAGED_SERVICE_OWNER_TYPE_PERSONAL",
		2: "MANAGED_SERVICE_OWNER_TYPE_TENANT",
	}
	ManagedServiceOwnerTypeV1_value = map[string]int32{
		"MANAGED_SERVICE_OWNER_TYPE_UNSPECIFIED": 0,
		"MANAGED_SERVICE_OWNER_TYPE_PERSONAL":    1,
		"MANAGED_SERVICE_OWNER_TYPE_TENANT":      2,
	}
)

func (x ManagedServiceOwnerTypeV1) Enum() *ManagedServiceOwnerTypeV1 {
	p := new(ManagedServiceOwnerTypeV1)
	*p = x
	return p
}

func (x ManagedServiceOwnerTypeV1) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ManagedServiceOwnerTypeV1) Descriptor() protoreflect.EnumDescriptor {
	return file_managed_service_proto_enumTypes[0].Descriptor()
}

func (ManagedServiceOwnerTypeV1) Type() protoreflect.EnumType {
	return &file_managed_service_proto_enumTypes[0]
}

func (x ManagedServiceOwnerTypeV1) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ManagedServiceOwnerTypeV1.Descriptor instead.
func (ManagedServiceOwnerTypeV1) EnumDescriptor() ([]byte, []int) {
	return file_managed_service_proto_rawDescGZIP(), []int{0}
}

type ManagedServiceOperationKindV1 int32

const (
	ManagedServiceOperationKindV1_MANAGED_SERVICE_OPERATION_KIND_UNSPECIFIED ManagedServiceOperationKindV1 = 0
	ManagedServiceOperationKindV1_MANAGED_SERVICE_OPERATION_KIND_CREATE      ManagedServiceOperationKindV1 = 1
	ManagedServiceOperationKindV1_MANAGED_SERVICE_OPERATION_KIND_UPDATE      ManagedServiceOperationKindV1 = 2
	ManagedServiceOperationKindV1_MANAGED_SERVICE_OPERATION_KIND_DELETE      ManagedServiceOperationKindV1 = 3
	ManagedServiceOperationKindV1_MANAGED_SERVICE_OPERATION_KIND_RESIZE      ManagedServiceOperationKindV1 = 4
)

// Enum value maps for ManagedServiceOperationKindV1.
var (
	ManagedServiceOperationKindV1_name = map[int32]string{
		0: "MANAGED_SERVICE_OPERATION_KIND_UNSPECIFIED",
		1: "MANAGED_SERVICE_OPERATION_KIND_CREATE",
		2: "MANAGED_SERVICE_OPERATION_KIND_UPDATE",
		3: "MANAGED_SERVICE_OPERATION_KIND_DELETE",
		4: "MANAGED_SERVICE_OPERATION_KIND_RESIZE",
	}
	ManagedServiceOperationKindV1_value = map[string]int32{
		"MANAGED_SERVICE_OPERATION_KIND_UNSPECIFIED": 0,
		"MANAGED_SERVICE_OPERATION_KIND_CREATE":      1,
		"MANAGED_SERVICE_OPERATION_KIND_UPDATE":      2,
		"MANAGED_SERVICE_OPERATION_KIND_DELETE":      3,
		"MANAGED_SERVICE_OPERATION_KIND_RESIZE":      4,
	}
)

func (x ManagedServiceOperationKindV1) Enum() *ManagedServiceOperationKindV1 {
	p := new(ManagedServiceOperationKindV1)
	*p = x
	return p
}

func (x ManagedServiceOperationKindV1) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ManagedServiceOperationKindV1) Descriptor() protoreflect.EnumDescriptor {
	return file_managed_service_proto_enumTypes[1].Descriptor()
}

func (ManagedServiceOperationKindV1) Type() protoreflect.EnumType {
	return &file_managed_service_proto_enumTypes[1]
}

func (x ManagedServiceOperationKindV1) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ManagedServiceOperationKindV1.Descriptor instead.
func (ManagedServiceOperationKindV1) EnumDescriptor() ([]byte, []int) {
	return file_managed_service_proto_rawDescGZIP(), []int{1}
}

type ManagedServiceOutcomeV1 int32

const (
	ManagedServiceOutcomeV1_MANAGED_SERVICE_OUTCOME_UNSPECIFIED       ManagedServiceOutcomeV1 = 0
	ManagedServiceOutcomeV1_MANAGED_SERVICE_OUTCOME_SUCCEEDED         ManagedServiceOutcomeV1 = 1
	ManagedServiceOutcomeV1_MANAGED_SERVICE_OUTCOME_RETRYABLE_FAILURE ManagedServiceOutcomeV1 = 2
	ManagedServiceOutcomeV1_MANAGED_SERVICE_OUTCOME_TERMINAL_FAILURE  ManagedServiceOutcomeV1 = 3
)

// Enum value maps for ManagedServiceOutcomeV1.
var (
	ManagedServiceOutcomeV1_name = map[int32]string{
		0: "MANAGED_SERVICE_OUTCOME_UNSPECIFIED",
		1: "MANAGED_SERVICE_OUTCOME_SUCCEEDED",
		2: "MANAGED_SERVICE_OUTCOME_RETRYABLE_FAILURE",
		3: "MANAGED_SERVICE_OUTCOME_TERMINAL_FAILURE",
	}
	ManagedServiceOutcomeV1_value = map[string]int32{
		"MANAGED_SERVICE_OUTCOME_UNSPECIFIED":       0,
		"MANAGED_SERVICE_OUTCOME_SUCCEEDED":         1,
		"MANAGED_SERVICE_OUTCOME_RETRYABLE_FAILURE": 2,
		"MANAGED_SERVICE_OUTCOME_TERMINAL_FAILURE":  3,
	}
)

func (x ManagedServiceOutcomeV1) Enum() *ManagedServiceOutcomeV1 {
	p := new(ManagedServiceOutcomeV1)
	*p = x
	return p
}

func (x ManagedServiceOutcomeV1) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ManagedServiceOutcomeV1) Descriptor() protoreflect.EnumDescriptor {
	return file_managed_service_proto_enumTypes[2].Descriptor()
}

func (ManagedServiceOutcomeV1) Type() protoreflect.EnumType {
	return &file_managed_service_proto_enumTypes[2]
}

func (x ManagedServiceOutcomeV1) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ManagedServiceOutcomeV1.Descriptor instead.
func (ManagedServiceOutcomeV1) EnumDescriptor() ([]byte, []int) {
	return file_managed_service_proto_rawDescGZIP(), []int{2}
}

type ManagedServiceObservedStateV1 int32

const (
	ManagedServiceObservedStateV1_MANAGED_SERVICE_OBSERVED_STATE_UNSPECIFIED ManagedServiceObservedStateV1 = 0
	ManagedServiceObservedStateV1_MANAGED_SERVICE_OBSERVED_STATE_UNKNOWN     ManagedServiceObservedStateV1 = 1
	ManagedServiceObservedStateV1_MANAGED_SERVICE_OBSERVED_STATE_PROGRESSING ManagedServiceObservedStateV1 = 2
	ManagedServiceObservedStateV1_MANAGED_SERVICE_OBSERVED_STATE_READY       ManagedServiceObservedStateV1 = 3
	ManagedServiceObservedStateV1_MANAGED_SERVICE_OBSERVED_STATE_DEGRADED    ManagedServiceObservedStateV1 = 4
)

// Enum value maps for ManagedServiceObservedStateV1.
var (
	ManagedServiceObservedStateV1_name = map[int32]string{
		0: "MANAGED_SERVICE_OBSERVED_STATE_UNSPECIFIED",
		1: "MANAGED_SERVICE_OBSERVED_STATE_UNKNOWN",
		2: "MANAGED_SERVICE_OBSERVED_STATE_PROGRESSING",
		3: "MANAGED_SERVICE_OBSERVED_STATE_READY",
		4: "MANAGED_SERVICE_OBSERVED_STATE_DEGRADED",
	}
	ManagedServiceObservedStateV1_value = map[string]int32{
		"MANAGED_SERVICE_OBSERVED_STATE_UNSPECIFIED": 0,
		"MANAGED_SERVICE_OBSERVED_STATE_UNKNOWN":     1,
		"MANAGED_SERVICE_OBSERVED_STATE_PROGRESSING": 2,
		"MANAGED_SERVICE_OBSERVED_STATE_READY":       3,
		"MANAGED_SERVICE_OBSERVED_STATE_DEGRADED":    4,
	}
)

func (x ManagedServiceObservedStateV1) Enum() *ManagedServiceObservedStateV1 {
	p := new(ManagedServiceObservedStateV1)
	*p = x
	return p
}

func (x ManagedServiceObservedStateV1) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ManagedServiceObservedStateV1) Descriptor() protoreflect.EnumDescriptor {
	return file_managed_service_proto_enumTypes[3].Descriptor()
}

func (ManagedServiceObservedStateV1) Type() protoreflect.EnumType {
	return &file_managed_service_proto_enumTypes[3]
}

func (x ManagedServiceObservedStateV1) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ManagedServiceObservedStateV1.Descriptor instead.
func (ManagedServiceObservedStateV1) EnumDescriptor() ([]byte, []int) {
	return file_managed_service_proto_rawDescGZIP(), []int{3}
}

type ManagedServiceComponentV1 struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	ComponentId              string                 `protobuf:"bytes,1,opt,name=component_id,json=componentId,proto3" json:"component_id,omitempty"`
	DocumentIndexes          []uint32               `protobuf:"varint,2,rep,packed,name=document_indexes,json=documentIndexes,proto3" json:"document_indexes,omitempty"`
	ApplyOrder               uint32                 `protobuf:"varint,3,opt,name=apply_order,json=applyOrder,proto3" json:"apply_order,omitempty"`
	DeleteOrder              uint32                 `protobuf:"varint,4,opt,name=delete_order,json=deleteOrder,proto3" json:"delete_order,omitempty"`
	ReadinessRule            string                 `protobuf:"bytes,5,opt,name=readiness_rule,json=readinessRule,proto3" json:"readiness_rule,omitempty"`
	ReadinessDeadlineSeconds uint32                 `protobuf:"varint,6,opt,name=readiness_deadline_seconds,json=readinessDeadlineSeconds,proto3" json:"readiness_deadline_seconds,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ManagedServiceComponentV1) Reset() {
	*x = ManagedServiceComponentV1{}
	mi := &file_managed_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagedServiceComponentV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedServiceComponentV1) ProtoMessage() {}

func (x *ManagedServiceComponentV1) ProtoReflect() protoreflect.Message {
	mi := &file_managed_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedServiceComponentV1.ProtoReflect.Descriptor instead.
func (*ManagedServiceComponentV1) Descriptor() ([]byte, []int) {
	return file_managed_service_proto_rawDescGZIP(), []int{0}
}

func (x *ManagedServiceComponentV1) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

func (x *ManagedServiceComponentV1) GetDocumentIndexes() []uint32 {
	if x != nil {
		return x.DocumentIndexes
	}
	return nil
}

func (x *ManagedServiceComponentV1) GetApplyOrder() uint32 {
	if x != nil {
		return x.ApplyOrder
	}
	return 0
}

func (x *ManagedServiceComponentV1) GetDeleteOrder() uint32 {
	if x != nil {
		return x.DeleteOrder
	}
	return 0
}

func (x *ManagedServiceComponentV1) GetReadinessRule() string {
	if x != nil {
		return x.ReadinessRule
	}
	return ""
}

func (x *ManagedServiceComponentV1) GetReadinessDeadlineSeconds() uint32 {
	if x != nil {
		return x.ReadinessDeadlineSeconds
	}
	return 0
}

type ManagedServiceSafeObservedFieldV1 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*ManagedServiceSafeObservedFieldV1_StringValue
	//	*ManagedServiceSafeObservedFieldV1_BoolValue
	//	*ManagedServiceSafeObservedFieldV1_Int64Value
	//	*ManagedServiceSafeObservedFieldV1_DecimalValue
	Value         isManagedServiceSafeObservedFieldV1_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagedServiceSafeObservedFieldV1) Reset() {
	*x = ManagedServiceSafeObservedFieldV1{}
	mi := &file_managed_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagedServiceSafeObservedFieldV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedServiceSafeObservedFieldV1) ProtoMessage() {}

func (x *ManagedServiceSafeObservedFieldV1) ProtoReflect() protoreflect.Message {
	mi := &file_managed_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedServiceSafeObservedFieldV1.ProtoReflect.Descriptor instead.
func (*ManagedServiceSafeObservedFieldV1) Descriptor() ([]byte, []int) {
	return file_managed_service_proto_rawDescGZIP(), []int{1}
}

func (x *ManagedServiceSafeObservedFieldV1) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ManagedServiceSafeObservedFieldV1) GetValue() isManagedServiceSafeObservedFieldV1_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ManagedServiceSafeObservedFieldV1) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*ManagedServiceSafeObservedFieldV1_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *ManagedServiceSafeObservedFieldV1) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*ManagedServiceSafeObservedFieldV1_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *ManagedServiceSafeObservedFieldV1) GetInt64Value() int64 {
	if x != nil {
		if x, ok := x.Value.(*ManagedServiceSafeObservedFieldV1_Int64Value); ok {
			return x.Int64Value
		}
	}
	return 0
}

func (x *ManagedServiceSafeObservedFieldV1) GetDecimalValue() string {
	if x != nil {
		if x, ok := x.Value.(*ManagedServiceSafeObservedFieldV1_DecimalValue); ok {
			return x.DecimalValue
		}
	}
	return ""
}

type isManagedServiceSafeObservedFieldV1_Value interface {
	isManagedServiceSafeObservedFieldV1_Value()
}

type ManagedServiceSafeObservedFieldV1_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type ManagedServiceSafeObservedFieldV1_BoolValue struct {
	BoolValue bool `protobuf:"varint,3,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type ManagedServiceSafeObservedFieldV1_Int64Value struct {
	Int64Value int64 `protobuf:"varint,4,opt,name=int64_value,json=int64Value,proto3,oneof"`
}

type ManagedServiceSafeObservedFieldV1_DecimalValue struct {
	DecimalValue string `protobuf:"bytes,5,opt,name=decimal_value,json=decimalValue,proto3,oneof"`
}

func (*ManagedServiceSafeObservedFieldV1_StringValue) isManagedServiceSafeObservedFieldV1_Value() {}

func (*ManagedServiceSafeObservedFieldV1_BoolValue) isManagedServiceSafeObservedFieldV1_Value() {}

func (*ManagedServiceSafeObservedFieldV1_Int64Value) isManagedServiceSafeObservedFieldV1_Value() {}

func (*ManagedServiceSafeObservedFieldV1_DecimalValue) isManagedServiceSafeObservedFieldV1_Value() {}

type ManagedServiceCommandV1 struct {
	state                 protoimpl.MessageState        `protogen:"open.v1"`
	CommandEventId        []byte                        `protobuf:"bytes,1,opt,name=command_event_id,json=commandEventId,proto3" json:"command_event_id,omitempty"`
	OperationId           []byte                        `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	InstanceId            []byte                        `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	OwnerType             ManagedServiceOwnerTypeV1     `protobuf:"varint,4,opt,name=owner_type,json=ownerType,proto3,enum=aurora.managedservice.v1.ManagedServiceOwnerTypeV1" json:"owner_type,omitempty"`
	OwnerId               []byte                        `protobuf:"bytes,5,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	WorkspaceId           []byte                        `protobuf:"bytes,6,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	ZoneId                []byte                        `protobuf:"bytes,7,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	InstanceCode          string                        `protobuf:"bytes,8,opt,name=instance_code,json=instanceCode,proto3" json:"instance_code,omitempty"`
	OperationKind         ManagedServiceOperationKindV1 `protobuf:"varint,9,opt,name=operation_kind,json=operationKind,proto3,enum=aurora.managedservice.v1.ManagedServiceOperationKindV1" json:"operation_kind,omitempty"`
	Generation            uint64                        `protobuf:"varint,10,opt,name=generation,proto3" json:"generation,omitempty"`
	InstanceRevisionId    []byte                        `protobuf:"bytes,12,opt,name=instance_revision_id,json=instanceRevisionId,proto3" json:"instance_revision_id,omitempty"`
	BlueprintRevisionId   []byte                        `protobuf:"bytes,13,opt,name=blueprint_revision_id,json=blueprintRevisionId,proto3" json:"blueprint_revision_id,omitempty"`
	TemplateYaml          string                        `protobuf:"bytes,14,opt,name=template_yaml,json=templateYaml,proto3" json:"template_yaml,omitempty"`
	Components            []*ManagedServiceComponentV1  `protobuf:"bytes,15,rep,name=components,proto3" json:"components,omitempty"`
	BundleHash            []byte                        `protobuf:"bytes,16,opt,name=bundle_hash,json=bundleHash,proto3" json:"bundle_hash,omitempty"`
	ComponentContractHash []byte                        `protobuf:"bytes,17,opt,name=component_contract_hash,json=componentContractHash,proto3" json:"component_contract_hash,omitempty"`
	InputHash             []byte                        `protobuf:"bytes,18,opt,name=input_hash,json=inputHash,proto3" json:"input_hash,omitempty"`
	DesiredSpecHash       []byte                        `protobuf:"bytes,19,opt,name=desired_spec_hash,json=desiredSpecHash,proto3" json:"desired_spec_hash,omitempty"`
	// Canonical customer values are plaintext only inside this inner command.
	// JobCommandV1.payload protects the entire serialized command, so nested
	// field-level encryption and a second key lifecycle are forbidden.
	ParameterValues       []byte `protobuf:"bytes,20,opt,name=parameter_values,json=parameterValues,proto3" json:"parameter_values,omitempty"`
	ParameterValuesSha256 []byte `protobuf:"bytes,21,opt,name=parameter_values_sha256,json=parameterValuesSha256,proto3" json:"parameter_values_sha256,omitempty"`
	SchemaVersion         uint32 `protobuf:"varint,22,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	IssuedAtUnixMs        int64  `protobuf:"varint,23,opt,name=issued_at_unix_ms,json=issuedAtUnixMs,proto3" json:"issued_at_unix_ms,omitempty"`
	Traceparent           string `protobuf:"bytes,24,opt,name=traceparent,proto3" json:"traceparent,omitempty"`
	Tracestate            string `protobuf:"bytes,25,opt,name=tracestate,proto3" json:"tracestate,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ManagedServiceCommandV1) Reset() {
	*x = ManagedServiceCommandV1{}
	mi := &file_managed_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagedServiceCommandV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedServiceCommandV1) ProtoMessage() {}

func (x *ManagedServiceCommandV1) ProtoReflect() protoreflect.Message {
	mi := &file_managed_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedServiceCommandV1.ProtoReflect.Descriptor instead.
func (*ManagedServiceCommandV1) Descriptor() ([]byte, []int) {
	return file_managed_service_proto_rawDescGZIP(), []int{2}
}

func (x *ManagedServiceCommandV1) GetCommandEventId() []byte {
	if x != nil {
		return x.CommandEventId
	}
	return nil
}

func (x *ManagedServiceCommandV1) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *ManagedServiceCommandV1) GetInstanceId() []byte {
	if x != nil {
		return x.InstanceId
	}
	return nil
}

func (x *ManagedServiceCommandV1) GetOwnerType() ManagedServiceOwnerTypeV1 {
	if x != nil {
		return x.OwnerType
	}
	return ManagedServiceOwnerTypeV1_MANAGED_SERVICE_OWNER_TYPE_UNSPECIFIED
}

func (x *ManagedServiceCommandV1) GetOwnerId() []byte {
	if x != nil {
		return x.OwnerId
	}
	return nil
}

func (x *ManagedServiceCommandV1) GetWorkspaceId() []byte {
	if x != nil {
		return x.WorkspaceId
	}
	return nil
}

func (x *ManagedServiceCommandV1) GetZoneId() []byte {
	if x != nil {
		return x.ZoneId
	}
	return nil
}

func (x *ManagedServiceCommandV1) GetInstanceCode() string {
	if x != nil {
		return x.InstanceCode
	}
	return ""
}

func (x *ManagedServiceCommandV1) GetOperationKind() ManagedServiceOperationKindV1 {
	if x != nil {
		return x.OperationKind
	}
	return ManagedServiceOperationKindV1_MANAGED_SERVICE_OPERATION_KIND_UNSPECIFIED
}

func (x *ManagedServiceCommandV1) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *ManagedServiceCommandV1) GetInstanceRevisionId() []byte {
	if x != nil {
		return x.InstanceRevisionId
	}
	return nil
}

func (x *ManagedServiceCommandV1) GetBlueprintRevisionId() []byte {
	if x != nil {
		return x.BlueprintRevisionId
	}
	return nil
}

func (x *ManagedServiceCommandV1) GetTemplateYaml() string {
	if x != nil {
		return x.TemplateYaml
	}
	return ""
}

func (x *ManagedServiceCommandV1) GetComponents() []*ManagedServiceComponentV1 {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *ManagedServiceCommandV1) GetBundleHash() []byte {
	if x != nil {
		return x.BundleHash
	}
	return nil
}

func (x *ManagedServiceCommandV1) GetComponentContractHash() []byte {
	if x != nil {
		return x.ComponentContractHash
	}
	return nil
}

func (x *ManagedServiceCommandV1) GetInputHash() []byte {
	if x != nil {
		return x.InputHash
	}
	return nil
}

func (x *ManagedServiceCommandV1) GetDesiredSpecHash() []byte {
	if x != nil {
		return x.DesiredSpecHash
	}
	return nil
}

func (x *ManagedServiceCommandV1) GetParameterValues() []byte {
	if x != nil {
		return x.ParameterValues
	}
	return nil
}

func (x *ManagedServiceCommandV1) GetParameterValuesSha256() []byte {
	if x != nil {
		return x.ParameterValuesSha256
	}
	return nil
}

func (x *ManagedServiceCommandV1) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *ManagedServiceCommandV1) GetIssuedAtUnixMs() int64 {
	if x != nil {
		return x.IssuedAtUnixMs
	}
	return 0
}

func (x *ManagedServiceCommandV1) GetTraceparent() string {
	if x != nil {
		return x.Traceparent
	}
	return ""
}

func (x *ManagedServiceCommandV1) GetTracestate() string {
	if x != nil {
		return x.Tracestate
	}
	return ""
}

type ManagedServiceResultV1 struct {
	state                 protoimpl.MessageState               `protogen:"open.v1"`
	ResultEventId         []byte                               `protobuf:"bytes,1,opt,name=result_event_id,json=resultEventId,proto3" json:"result_event_id,omitempty"`
	SourceCommandEventId  []byte                               `protobuf:"bytes,2,opt,name=source_command_event_id,json=sourceCommandEventId,proto3" json:"source_command_event_id,omitempty"`
	OperationId           []byte                               `protobuf:"bytes,3,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	InstanceId            []byte                               `protobuf:"bytes,4,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	ZoneId                []byte                               `protobuf:"bytes,5,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	Generation            uint64                               `protobuf:"varint,6,opt,name=generation,proto3" json:"generation,omitempty"`
	Attempt               uint32                               `protobuf:"varint,7,opt,name=attempt,proto3" json:"attempt,omitempty"`
	InstanceRevisionId    []byte                               `protobuf:"bytes,8,opt,name=instance_revision_id,json=instanceRevisionId,proto3" json:"instance_revision_id,omitempty"`
	BlueprintRevisionId   []byte                               `protobuf:"bytes,9,opt,name=blueprint_revision_id,json=blueprintRevisionId,proto3" json:"blueprint_revision_id,omitempty"`
	BundleHash            []byte                               `protobuf:"bytes,10,opt,name=bundle_hash,json=bundleHash,proto3" json:"bundle_hash,omitempty"`
	ComponentContractHash []byte                               `protobuf:"bytes,11,opt,name=component_contract_hash,json=componentContractHash,proto3" json:"component_contract_hash,omitempty"`
	InputHash             []byte                               `protobuf:"bytes,12,opt,name=input_hash,json=inputHash,proto3" json:"input_hash,omitempty"`
	DesiredSpecHash       []byte                               `protobuf:"bytes,13,opt,name=desired_spec_hash,json=desiredSpecHash,proto3" json:"desired_spec_hash,omitempty"`
	Outcome               ManagedServiceOutcomeV1              `protobuf:"varint,15,opt,name=outcome,proto3,enum=aurora.managedservice.v1.ManagedServiceOutcomeV1" json:"outcome,omitempty"`
	ErrorCode             string                               `protobuf:"bytes,16,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	SanitizedMessage      string                               `protobuf:"bytes,17,opt,name=sanitized_message,json=sanitizedMessage,proto3" json:"sanitized_message,omitempty"`
	ObservedState         ManagedServiceObservedStateV1        `protobuf:"varint,18,opt,name=observed_state,json=observedState,proto3,enum=aurora.managedservice.v1.ManagedServiceObservedStateV1" json:"observed_state,omitempty"`
	SafeObservedOutput    []*ManagedServiceSafeObservedFieldV1 `protobuf:"bytes,19,rep,name=safe_observed_output,json=safeObservedOutput,proto3" json:"safe_observed_output,omitempty"`
	ObservedStateVersion  uint64                               `protobuf:"varint,20,opt,name=observed_state_version,json=observedStateVersion,proto3" json:"observed_state_version,omitempty"`
	SchemaVersion         uint32                               `protobuf:"varint,21,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CompletedAtUnixMs     int64                                `protobuf:"varint,22,opt,name=completed_at_unix_ms,json=completedAtUnixMs,proto3" json:"completed_at_unix_ms,omitempty"`
	Traceparent           string                               `protobuf:"bytes,23,opt,name=traceparent,proto3" json:"traceparent,omitempty"`
	Tracestate            string                               `protobuf:"bytes,24,opt,name=tracestate,proto3" json:"tracestate,omitempty"`
	DeliveryEpoch         uint64                               `protobuf:"varint,25,opt,name=delivery_epoch,json=deliveryEpoch,proto3" json:"delivery_epoch,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ManagedServiceResultV1) Reset() {
	*x = ManagedServiceResultV1{}
	mi := &file_managed_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagedServiceResultV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedServiceResultV1) ProtoMessage() {}

func (x *ManagedServiceResultV1) ProtoReflect() protoreflect.Message {
	mi := &file_managed_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedServiceResultV1.ProtoReflect.Descriptor instead.
func (*ManagedServiceResultV1) Descriptor() ([]byte, []int) {
	return file_managed_service_proto_rawDescGZIP(), []int{3}
}

func (x *ManagedServiceResultV1) GetResultEventId() []byte {
	if x != nil {
		return x.ResultEventId
	}
	return nil
}

func (x *ManagedServiceResultV1) GetSourceCommandEventId() []byte {
	if x != nil {
		return x.SourceCommandEventId
	}
	return nil
}

func (x *ManagedServiceResultV1) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *ManagedServiceResultV1) GetInstanceId() []byte {
	if x != nil {
		return x.InstanceId
	}
	return nil
}

func (x *ManagedServiceResultV1) GetZoneId() []byte {
	if x != nil {
		return x.ZoneId
	}
	return nil
}

func (x *ManagedServiceResultV1) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *ManagedServiceResultV1) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *ManagedServiceResultV1) GetInstanceRevisionId() []byte {
	if x != nil {
		return x.InstanceRevisionId
	}
	return nil
}

func (x *ManagedServiceResultV1) GetBlueprintRevisionId() []byte {
	if x != nil {
		return x.BlueprintRevisionId
	}
	return nil
}

func (x *ManagedServiceResultV1) GetBundleHash() []byte {
	if x != nil {
		return x.BundleHash
	}
	return nil
}

func (x *ManagedServiceResultV1) GetComponentContractHash() []byte {
	if x != nil {
		return x.ComponentContractHash
	}
	return nil
}

func (x *ManagedServiceResultV1) GetInputHash() []byte {
	if x != nil {
		return x.InputHash
	}
	return nil
}

func (x *ManagedServiceResultV1) GetDesiredSpecHash() []byte {
	if x != nil {
		return x.DesiredSpecHash
	}
	return nil
}

func (x *ManagedServiceResultV1) GetOutcome() ManagedServiceOutcomeV1 {
	if x != nil {
		return x.Outcome
	}
	return ManagedServiceOutcomeV1_MANAGED_SERVICE_OUTCOME_UNSPECIFIED
}

func (x *ManagedServiceResultV1) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ManagedServiceResultV1) GetSanitizedMessage() string {
	if x != nil {
		return x.SanitizedMessage
	}
	return ""
}

func (x *ManagedServiceResultV1) GetObservedState() ManagedServiceObservedStateV1 {
	if x != nil {
		return x.ObservedState
	}
	return ManagedServiceObservedStateV1_MANAGED_SERVICE_OBSERVED_STATE_UNSPECIFIED
}

func (x *ManagedServiceResultV1) GetSafeObservedOutput() []*ManagedServiceSafeObservedFieldV1 {
	if x != nil {
		return x.SafeObservedOutput
	}
	return nil
}

func (x *ManagedServiceResultV1) GetObservedStateVersion() uint64 {
	if x != nil {
		return x.ObservedStateVersion
	}
	return 0
}

func (x *ManagedServiceResultV1) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *ManagedServiceResultV1) GetCompletedAtUnixMs() int64 {
	if x != nil {
		return x.CompletedAtUnixMs
	}
	return 0
}

func (x *ManagedServiceResultV1) GetTraceparent() string {
	if x != nil {
		return x.Traceparent
	}
	return ""
}

func (x *ManagedServiceResultV1) GetTracestate() string {
	if x != nil {
		return x.Tracestate
	}
	return ""
}

func (x *ManagedServiceResultV1) GetDeliveryEpoch() uint64 {
	if x != nil {
		return x.DeliveryEpoch
	}
	return 0
}

var File_managed_service_proto protoreflect.FileDescriptor

const file_managed_service_proto_rawDesc = "" +
	"\n" +
	"\x15managed_service.proto\x12\x18aurora.managedservice.v1\"\x98\x02\n" +
	"\x19ManagedServiceComponentV1\x12!\n" +
	"\fcomponent_id\x18\x01 \x01(\tR\vcomponentId\x12)\n" +
	"\x10document_indexes\x18\x02 \x03(\rR\x0fdocumentIndexes\x12\x1f\n" +
	"\vapply_order\x18\x03 \x01(\rR\n" +
	"applyOrder\x12!\n" +
	"\fdelete_order\x18\x04 \x01(\rR\vdeleteOrder\x12%\n" +
	"\x0ereadiness_rule\x18\x05 \x01(\tR\rreadinessRule\x12<\n" +
	"\x1areadiness_deadline_seconds\x18\x06 \x01(\rR\x18readinessDeadlineSecondsJ\x04\b\a\x10\x10\"\xd4\x01\n" +
	"!ManagedServiceSafeObservedFieldV1\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\fstring_value\x18\x02 \x01(\tH\x00R\vstringValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x03 \x01(\bH\x00R\tboolValue\x12!\n" +
	"\vint64_value\x18\x04 \x01(\x03H\x00R\n" +
	"int64Value\x12%\n" +
	"\rdecimal_value\x18\x05 \x01(\tH\x00R\fdecimalValueB\a\n" +
	"\x05valueJ\x04\b\x06\x10\x10\"\xde\b\n" +
	"\x17ManagedServiceCommandV1\x12(\n" +
	"\x10command_event_id\x18\x01 \x01(\fR\x0ecommandEventId\x12!\n" +
	"\foperation_id\x18\x02 \x01(\fR\voperationId\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\fR\n" +
	"instanceId\x12R\n" +
	"\n" +
	"owner_type\x18\x04 \x01(\x0e23.aurora.managedservice.v1.ManagedServiceOwnerTypeV1R\townerType\x12\x19\n" +
	"\bowner_id\x18\x05 \x01(\fR\aownerId\x12!\n" +
	"\fworkspace_id\x18\x06 \x01(\fR\vworkspaceId\x12\x17\n" +
	"\azone_id\x18\a \x01(\fR\x06zoneId\x12#\n" +
	"\rinstance_code\x18\b \x01(\tR\finstanceCode\x12^\n" +
	"\x0eoperation_kind\x18\t \x01(\x0e27.aurora.managedservice.v1.ManagedServiceOperationKindV1R\roperationKind\x12\x1e\n" +
	"\n" +
	"generation\x18\n" +
	" \x01(\x04R\n" +
	"generation\x120\n" +
	"\x14instance_revision_id\x18\f \x01(\fR\x12instanceRevisionId\x122\n" +
	"\x15blueprint_revision_id\x18\r \x01(\fR\x13blueprintRevisionId\x12#\n" +
	"\rtemplate_yaml\x18\x0e \x01(\tR\ftemplateYaml\x12S\n" +
	"\n" +
	"components\x18\x0f \x03(\v23.aurora.managedservice.v1.ManagedServiceComponentV1R\n" +
	"components\x12\x1f\n" +
	"\vbundle_hash\x18\x10 \x01(\fR\n" +
	"bundleHash\x126\n" +
	"\x17component_contract_hash\x18\x11 \x01(\fR\x15componentContractHash\x12\x1d\n" +
	"\n" +
	"input_hash\x18\x12 \x01(\fR\tinputHash\x12*\n" +
	"\x11desired_spec_hash\x18\x13 \x01(\fR\x0fdesiredSpecHash\x12)\n" +
	"\x10parameter_values\x18\x14 \x01(\fR\x0fparameterValues\x126\n" +
	"\x17parameter_values_sha256\x18\x15 \x01(\fR\x15parameterValuesSha256\x12%\n" +
	"\x0eschema_version\x18\x16 \x01(\rR\rschemaVersion\x12)\n" +
	"\x11issued_at_unix_ms\x18\x17 \x01(\x03R\x0eissuedAtUnixMs\x12 \n" +
	"\vtraceparent\x18\x18 \x01(\tR\vtraceparent\x12\x1e\n" +
	"\n" +
	"tracestate\x18\x19 \x01(\tR\n" +
	"tracestateJ\x04\b\v\x10\fJ\x04\b\x1a\x10 \"\x83\t\n" +
	"\x16ManagedServiceResultV1\x12&\n" +
	"\x0fresult_event_id\x18\x01 \x01(\fR\rresultEventId\x125\n" +
	"\x17source_command_event_id\x18\x02 \x01(\fR\x14sourceCommandEventId\x12!\n" +
	"\foperation_id\x18\x03 \x01(\fR\voperationId\x12\x1f\n" +
	"\vinstance_id\x18\x04 \x01(\fR\n" +
	"instanceId\x12\x17\n" +
	"\azone_id\x18\x05 \x01(\fR\x06zoneId\x12\x1e\n" +
	"\n" +
	"generation\x18\x06 \x01(\x04R\n" +
	"generation\x12\x18\n" +
	"\aattempt\x18\a \x01(\rR\aattempt\x120\n" +
	"\x14instance_revision_id\x18\b \x01(\fR\x12instanceRevisionId\x122\n" +
	"\x15blueprint_revision_id\x18\t \x01(\fR\x13blueprintRevisionId\x12\x1f\n" +
	"\vbundle_hash\x18\n" +
	" \x01(\fR\n" +
	"bundleHash\x126\n" +
	"\x17component_contract_hash\x18\v \x01(\fR\x15componentContractHash\x12\x1d\n" +
	"\n" +
	"input_hash\x18\f \x01(\fR\tinputHash\x12*\n" +
	"\x11desired_spec_hash\x18\r \x01(\fR\x0fdesiredSpecHash\x12K\n" +
	"\aoutcome\x18\x0f \x01(\x0e21.aurora.managedservice.v1.ManagedServiceOutcomeV1R\aoutcome\x12\x1d\n" +
	"\n" +
	"error_code\x18\x10 \x01(\tR\terrorCode\x12+\n" +
	"\x11sanitized_message\x18\x11 \x01(\tR\x10sanitizedMessage\x12^\n" +
	"\x0eobserved_state\x18\x12 \x01(\x0e27.aurora.managedservice.v1.ManagedServiceObservedStateV1R\robservedState\x12m\n" +
	"\x14safe_observed_output\x18\x13 \x03(\v2;.aurora.managedservice.v1.ManagedServiceSafeObservedFieldV1R\x12safeObservedOutput\x124\n" +
	"\x16observed_state_version\x18\x14 \x01(\x04R\x14observedStateVersion\x12%\n" +
	"\x0eschema_version\x18\x15 \x01(\rR\rschemaVersion\x12/\n" +
	"\x14completed_at_unix_ms\x18\x16 \x01(\x03R\x11completedAtUnixMs\x12 \n" +
	"\vtraceparent\x18\x17 \x01(\tR\vtraceparent\x12\x1e\n" +
	"\n" +
	"tracestate\x18\x18 \x01(\tR\n" +
	"tracestate\x12%\n" +
	"\x0edelivery_epoch\x18\x19 \x01(\x04R\rdeliveryEpochJ\x04\b\x0e\x10\x0fJ\x04\b\x1a\x10 *\x97\x01\n" +
	"\x19ManagedServiceOwnerTypeV1\x12*\n" +
	"&MANAGED_SERVICE_OWNER_TYPE_UNSPECIFIED\x10\x00\x12'\n" +
	"#MANAGED_SERVICE_OWNER_TYPE_PERSONAL\x10\x01\x12%\n" +
	"!MANAGED_SERVICE_OWNER_TYPE_TENANT\x10\x02*\xfb\x01\n" +
	"\x1dManagedServiceOperationKindV1\x12.\n" +
	"*MANAGED_SERVICE_OPERATION_KIND_UNSPECIFIED\x10\x00\x12)\n" +
	"%MANAGED_SERVICE_OPERATION_KIND_CREATE\x10\x01\x12)\n" +
	"%MANAGED_SERVICE_OPERATION_KIND_UPDATE\x10\x02\x12)\n" +
	"%MANAGED_SERVICE_OPERATION_KIND_DELETE\x10\x03\x12)\n" +
	"%MANAGED_SERVICE_OPERATION_KIND_RESIZE\x10\x04*\xc6\x01\n" +
	"\x17ManagedServiceOutcomeV1\x12'\n" +
	"#MANAGED_SERVICE_OUTCOME_UNSPECIFIED\x10\x00\x12%\n" +
	"!MANAGED_SERVICE_OUTCOME_SUCCEEDED\x10\x01\x12-\n" +
	")MANAGED_SERVICE_OUTCOME_RETRYABLE_FAILURE\x10\x02\x12,\n" +
	"(MANAGED_SERVICE_OUTCOME_TERMINAL_FAILURE\x10\x03*\x82\x02\n" +
	"\x1dManagedServiceObservedStateV1\x12.\n" +
	"*MANAGED_SERVICE_OBSERVED_STATE_UNSPECIFIED\x10\x00\x12*\n" +
	"&MANAGED_SERVICE_OBSERVED_STATE_UNKNOWN\x10\x01\x12.\n" +
	"*MANAGED_SERVICE_OBSERVED_STATE_PROGRESSING\x10\x02\x12(\n" +
	"$MANAGED_SERVICE_OBSERVED_STATE_READY\x10\x03\x12+\n" +
	"'MANAGED_SERVICE_OBSERVED_STATE_DEGRADED\x10\x04BJZHcontrolplane/internal/managedservice/transport/proto;managedserviceprotob\x06proto3"

var (
	file_managed_service_proto_rawDescOnce sync.Once
	file_managed_service_proto_rawDescData []byte
)

func file_managed_service_proto_rawDescGZIP() []byte {
	file_managed_service_proto_rawDescOnce.Do(func() {
		file_managed_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_managed_service_proto_rawDesc), len(file_managed_service_proto_rawDesc)))
	})
	return file_managed_service_proto_rawDescData
}

var file_managed_service_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_managed_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_managed_service_proto_goTypes = []any{
	(ManagedServiceOwnerTypeV1)(0),            // 0: aurora.managedservice.v1.ManagedServiceOwnerTypeV1
	(ManagedServiceOperationKindV1)(0),        // 1: aurora.managedservice.v1.ManagedServiceOperationKindV1
	(ManagedServiceOutcomeV1)(0),              // 2: aurora.managedservice.v1.ManagedServiceOutcomeV1
	(ManagedServiceObservedStateV1)(0),        // 3: aurora.managedservice.v1.ManagedServiceObservedStateV1
	(*ManagedServiceComponentV1)(nil),         // 4: aurora.managedservice.v1.ManagedServiceComponentV1
	(*ManagedServiceSafeObservedFieldV1)(nil), // 5: aurora.managedservice.v1.ManagedServiceSafeObservedFieldV1
	(*ManagedServiceCommandV1)(nil),           // 6: aurora.managedservice.v1.ManagedServiceCommandV1
	(*ManagedServiceResultV1)(nil),            // 7: aurora.managedservice.v1.ManagedServiceResultV1
}
var file_managed_service_proto_depIdxs = []int32{
	0, // 0: aurora.managedservice.v1.ManagedServiceCommandV1.owner_type:type_name -> aurora.managedservice.v1.ManagedServiceOwnerTypeV1
	1, // 1: aurora.managedservice.v1.ManagedServiceCommandV1.operation_kind:type_name -> aurora.managedservice.v1.ManagedServiceOperationKindV1
	4, // 2: aurora.managedservice.v1.ManagedServiceCommandV1.components:type_name -> aurora.managedservice.v1.ManagedServiceComponentV1
	2, // 3: aurora.managedservice.v1.ManagedServiceResultV1.outcome:type_name -> aurora.managedservice.v1.ManagedServiceOutcomeV1
	3, // 4: aurora.managedservice.v1.ManagedServiceResultV1.observed_state:type_name -> aurora.managedservice.v1.ManagedServiceObservedStateV1
	5, // 5: aurora.managedservice.v1.ManagedServiceResultV1.safe_observed_output:type_name -> aurora.managedservice.v1.ManagedServiceSafeObservedFieldV1
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_managed_service_proto_init() }
func file_managed_service_proto_init() {
	if File_managed_service_proto != nil {
		return
	}
	file_managed_service_proto_msgTypes[1].OneofWrappers = []any{
		(*ManagedServiceSafeObservedFieldV1_StringValue)(nil),
		(*ManagedServiceSafeObservedFieldV1_BoolValue)(nil),
		(*ManagedServiceSafeObservedFieldV1_Int64Value)(nil),
		(*ManagedServiceSafeObservedFieldV1_DecimalValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_managed_service_proto_rawDesc), len(file_managed_service_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_managed_service_proto_goTypes,
		DependencyIndexes: file_managed_service_proto_depIdxs,
		EnumInfos:         file_managed_service_proto_enumTypes,
		MessageInfos:      file_managed_service_proto_msgTypes,
	}.Build()
	File_managed_service_proto = out.File
	file_managed_service_proto_goTypes = nil
	file_managed_service_proto_depIdxs = nil
}
