DROP TABLE IF EXISTS tenant_mail_consumer_projection_tombstones CASCADE;
DROP TABLE IF EXISTS personal_mail_consumer_projection_tombstones CASCADE;
DROP TABLE IF EXISTS tenant_mail_template_projection_tombstones CASCADE;
DROP TABLE IF EXISTS personal_mail_template_projection_tombstones CASCADE;
DROP TRIGGER IF EXISTS trg_mail_protected_projection ON mail_outbox_records;
DROP TABLE IF EXISTS mail_protected_projections CASCADE;
DROP FUNCTION IF EXISTS project_mail_protected_payload();
DROP TABLE IF EXISTS mail_outbox_records CASCADE;
DROP TABLE IF EXISTS tenant_mail_consumer_update_versions CASCADE;
DROP TABLE IF EXISTS tenant_mail_consumers CASCADE;
DROP TABLE IF EXISTS personal_mail_consumer_update_versions CASCADE;
DROP TABLE IF EXISTS personal_mail_consumers CASCADE;
DROP TABLE IF EXISTS tenant_mail_template_versions CASCADE;
DROP TABLE IF EXISTS tenant_mail_templates CASCADE;
DROP TABLE IF EXISTS personal_mail_template_versions CASCADE;
DROP TABLE IF EXISTS personal_mail_templates CASCADE;
