DROP TABLE IF EXISTS mail_consumer_projection_tombstones CASCADE;
DROP TABLE IF EXISTS tenant_mail_template_projection_tombstones CASCADE;
DROP TABLE IF EXISTS personal_mail_template_projection_tombstones CASCADE;
DROP TABLE IF EXISTS mail_outbox_records CASCADE;
DROP TABLE IF EXISTS mail_consumer_runtime_reports CASCADE;
DROP TABLE IF EXISTS mail_consumer_update_versions CASCADE;
DROP TABLE IF EXISTS mail_consumers CASCADE;
DROP TRIGGER IF EXISTS trg_tenant_mail_template_versions_immutable ON tenant_mail_template_versions CASCADE;
DROP TRIGGER IF EXISTS trg_personal_mail_template_versions_immutable ON personal_mail_template_versions CASCADE;
DROP FUNCTION IF EXISTS reject_mail_template_version_mutation CASCADE;
DROP TABLE IF EXISTS tenant_mail_template_versions CASCADE;
DROP TABLE IF EXISTS tenant_mail_templates CASCADE;
DROP TABLE IF EXISTS personal_mail_template_versions CASCADE;
DROP TABLE IF EXISTS personal_mail_templates CASCADE;
